'use client'

import React, { useState } from 'react'
import type { RdStBlock as Props } from '@/payload-types'
import { useAmountTokens } from '@/blocks/redesign/_shared/amountTokens'
import type { AppLocale } from '@/i18n/config'

// GENERATED from manifests/section-38.json + bindings/RdSt.json by
// tools/block_component.py — do not hand-edit; regenerate.
//
// Styles copied verbatim from the mockup; bindings replace content only.
// Layout and breakpoints come from rd-st.css — this page's stylesheet,
// ported by port_css.py and rescoped from `.rd-block` to `.rd-st` so it
// cannot reach any other page's blocks. That scope is why this root carries
// `rd-st` and NOT `rd-block`.
//
// Our Standards, one block — the eight screens the mockup draws.


const mediaUrl = (m: unknown): string | undefined =>
  m && typeof m === 'object' && 'url' in m ? ((m as { url?: string }).url ?? undefined) : undefined

const mediaAlt = (m: unknown): string =>
  m && typeof m === 'object' && 'alt' in m ? ((m as { alt?: string }).alt ?? '') : ''

/* GENERATED into the block by --include — the helpers its sections share.
 *
 * MODULE SCOPE, not a component body. The eight sections become eight
 * components in one module once tools/page_assemble.py has run, and a `const`
 * declared inside RdSt's body is not in scope in RdStPlans's. The Science
 * Board learned this the expensive way; see out/board/preamble.tsx.
 */

/** A destination. The field holds a SLUG and the locale is added here, so one
 * stored value is right in all nine. Anything already absolute (a url, mailto,
 * tel, #anchor, or a /path) passes straight through, because an editor who
 * typed one meant it.
 *
 * `locale` is an ARGUMENT rather than a closure: this is module scope, and the
 * component that calls it is not the one that receives the prop. */
const stPath = (s?: string | null, locale?: string | null) => {
  const v = (s || '').trim()
  if (!v) return '#'
  if (/^(?:[a-z][a-z0-9+.-]*:|\/\/|\/|#)/i.test(v)) return v
  return `/${locale || 'en'}/${v}`
}

/** A textarea read as a list, one item per line.
 *
 * Two fields on this page are lists that an array would have made impossible:
 * `plans.tiers[].features` would have produced
 * `_pages_v_blocks_rd_st_plans_tiers_features_locales_locale_parent_id` — 66
 * bytes, past the 63 Postgres truncates at SILENTLY — and `proof.docs[].rows`
 * was within three characters of the same cliff. Blank lines are dropped so a
 * trailing newline does not render an empty row. */
const stLines = (s?: string | null) =>
  (s || '').split('\n').map((l) => l.trim()).filter(Boolean)

/** The spec rows under a proof card: `Label | Value`, one pair per line.
 *
 * The separator is a pipe because no label or value on this page contains one,
 * and because a line that forgets it should still render something an editor
 * can see and fix — so a missing pipe gives the whole line as the label and an
 * empty value, rather than dropping the row. */
const stRows = (s?: string | null) =>
  stLines(s).map((l) => {
    const i = l.indexOf('|')
    return i === -1
      ? { label: l, value: '' }
      : { label: l.slice(0, i).trim(), value: l.slice(i + 1).trim() }
  })

/* GENERATED by tools/page_assemble.py from out/standards/parts.json — do not
 * hand-edit.
 *
 * Our Standards' seven sections below the hero, lifted out of their own
 * generated files so RdSt can include them, plus the one wrapper that mounts
 * them in order.
 *
 * Each takes the field GROUP it reads, not the whole block — `Props['rules']`
 * rather than a `RdStRulesBlock` that does not exist. There is one block here;
 * these are its sections.
 */

const RdStRules: React.FC<{ rules?: Props['rules'] | null }> = ({ rules }) => {
  return (
    <section style={{
      background: "var(--nb1-cool-grey)"
    }} className="rd-st-rules" id="principles" data-screen-label="Principles">
      <div style={{
        maxWidth: "1240px",
        margin: "0px auto",
        padding: "64px 20px"
      }} data-d="pad bigpad">
        <h2 style={{
          fontFamily: "var(--nb1-font-primary)",
          fontWeight: "400",
          fontSize: "clamp(30px, 5cqi, 50px)",
          lineHeight: "1",
          letterSpacing: "-0.025em",
          maxWidth: "22ch",
          textWrap: "balance"
        }}>{rules?.heading}</h2>
        <div style={{
          display: "grid",
          gridTemplateColumns: "1fr",
          gap: "36px 32px",
          marginTop: "56px"
        }} data-m="std4" data-k="rules">
          {(rules?.items || []).map((r, ri) => (
            <div key={ri} style={{
              paddingTop: "22px",
              borderTop: "2px solid var(--nb1-dark-brown)"
            }}>
              <div style={{
                fontFamily: "var(--nb1-font-tertiary)",
                letterSpacing: "0.06em",
                fontSize: "13px",
                color: "rgba(81, 71, 69, 0.8)"
              }}>{r.num}</div>
              <h3 style={{
                fontFamily: "var(--nb1-font-primary)",
                fontWeight: "400",
                fontSize: "clamp(22px, 2.4cqi, 26px)",
                lineHeight: "1.1",
                marginTop: "16px"
              }}>{r.title}</h3>
              <p style={{
                fontFamily: "var(--nb1-font-secondary)",
                fontSize: "16px",
                lineHeight: "1.6",
                color: "rgba(81, 71, 69, 0.86)",
                marginTop: "10px",
                maxWidth: "34ch"
              }}>{r.body}</p>
            </div>
          ))}
        </div>
        <div style={{
          marginTop: "72px",
          padding: "44px 26px",
          borderRadius: "28px",
          background: "var(--nb1-dark-brown)",
          color: "var(--nb1-cool-grey)"
        }} data-d="stdpanel">
          <h3 style={{
            fontFamily: "var(--nb1-font-primary)",
            fontWeight: "400",
            fontSize: "clamp(30px, 5cqi, 52px)",
            lineHeight: "1.04",
            letterSpacing: "-0.025em",
            maxWidth: "22ch",
            textWrap: "balance"
          }}>
            {rules?.panelLead}
            <em style={{
              fontStyle: "italic",
              color: "var(--nb1-lime)"
            }}>{rules?.panelEm}</em>
            {rules?.panelTail}
          </h3>
          <p style={{
            fontFamily: "var(--nb1-font-secondary)",
            fontSize: "17px",
            lineHeight: "1.6",
            color: "rgba(240, 245, 255, 0.86)",
            marginTop: "20px",
            maxWidth: "58ch"
          }}>{rules?.panelBody}</p>
          <div style={{
            display: "grid",
            gridTemplateColumns: "1fr",
            gap: "30px 32px",
            marginTop: "44px"
          }} data-m="std4">
            {(rules?.nots || []).map((n, ni) => (
              <div key={ni} style={{
                paddingTop: "20px",
                borderTop: "1px solid rgba(240, 245, 255, 0.24)"
              }}>
                <div style={{
                  fontFamily: "var(--nb1-font-primary)",
                  fontSize: "20px",
                  lineHeight: "1.15",
                  color: "var(--nb1-cool-grey)"
                }}>{n.title}</div>
                <p style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "15.5px",
                  lineHeight: "1.65",
                  color: "rgba(240, 245, 255, 0.8)",
                  marginTop: "10px"
                }}>{n.body}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}

const RdStSource: React.FC<{ source?: Props['source'] | null }> = ({ source }) => {
  return (
    <section style={{
      background: "var(--tint)",
      borderTop: "1px solid rgba(81, 71, 69, 0.16)",
      borderBottom: "1px solid rgba(81, 71, 69, 0.16)"
    }} className="rd-st-source" id="sourcing" data-screen-label="Sourcing">
      <div style={{
        maxWidth: "1240px",
        margin: "0px auto",
        padding: "64px 20px"
      }} data-d="pad bigpad">
        <h2 style={{
          fontFamily: "var(--nb1-font-primary)",
          fontWeight: "400",
          fontSize: "clamp(30px, 5cqi, 50px)",
          lineHeight: "1",
          letterSpacing: "-0.025em",
          maxWidth: "22ch",
          textWrap: "balance"
        }}>{source?.heading}</h2>
        <p style={{
          fontFamily: "var(--nb1-font-secondary)",
          fontSize: "17px",
          lineHeight: "1.6",
          color: "rgba(81, 71, 69, 0.86)",
          marginTop: "18px",
          maxWidth: "58ch",
          textWrap: "pretty"
        }}>{source?.intro}</p>
        <div style={{
          display: "grid",
          gridTemplateColumns: "1fr",
          gap: "18px",
          marginTop: "36px"
        }} data-m="std3" data-k="src">
          {(source?.cards || []).map((c, ci) => (
            <div key={ci} style={{
              display: "flex",
              flexDirection: "column"
            }}>
              <div style={{
                aspectRatio: "4 / 5",
                borderRadius: "16px",
                overflow: "hidden",
                background: "var(--nb1-warm-grey)"
              }}>
                <img style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                  display: "block"
                }} src={mediaUrl(c.image)} alt={c.imageAlt || mediaAlt(c.image)} />
              </div>
              <h3 style={{
                fontFamily: "var(--nb1-font-primary)",
                fontWeight: "400",
                fontSize: "23px",
                lineHeight: "1.12",
                marginTop: "18px"
              }}>{c.title}</h3>
              <p style={{
                fontFamily: "var(--nb1-font-secondary)",
                fontSize: "16px",
                lineHeight: "1.55",
                color: "rgba(81, 71, 69, 0.86)",
                marginTop: "8px"
              }}>{c.body}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

const RdStFactory: React.FC<{ factory?: Props['factory'] | null }> = ({ factory }) => {
  return (
    <section style={{
      background: "var(--nb1-dark-brown)",
      color: "var(--nb1-cool-grey)"
    }} className="rd-st-factory" id="factory" data-screen-label="Factory">
      <div style={{
        maxWidth: "1240px",
        margin: "0px auto",
        padding: "64px 20px"
      }} data-d="pad bigpad">
        <div style={{
          display: "grid",
          gridTemplateColumns: "1fr",
          gap: "48px",
          alignItems: "center"
        }} data-d="side">
          <div>
            <h2 style={{
              fontFamily: "var(--nb1-font-primary)",
              fontWeight: "400",
              fontSize: "clamp(34px, 5.6cqi, 58px)",
              lineHeight: "1.02",
              letterSpacing: "-0.03em",
              maxWidth: "18ch",
              textWrap: "balance"
            }}>
              {factory?.headingLead}
              <em style={{
                fontStyle: "italic",
                color: "var(--nb1-lime)"
              }}>{factory?.headingEm}</em>
            </h2>
            <p style={{
              fontFamily: "var(--nb1-font-secondary)",
              fontSize: "clamp(17px, 2cqi, 19px)",
              lineHeight: "1.65",
              color: "rgba(240, 245, 255, 0.86)",
              marginTop: "22px",
              maxWidth: "52ch",
              textWrap: "pretty"
            }}>{factory?.intro}</p>
            <div style={{
              display: "grid",
              gridTemplateColumns: "1fr",
              gap: "26px 32px",
              marginTop: "36px"
            }} data-m="std2">
              <div style={{
                paddingTop: "20px",
                borderTop: "1px solid rgba(240, 245, 255, 0.24)"
              }}>
                <svg viewBox="0 0 24 24" width={26} height={26} fill="none" stroke="var(--nb1-lime)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M4 21V9l8-5 8 5v12" />
                  <path d="M9 21v-6h6v6" />
                  <path d="M3 21h18" />
                </svg>
                <div style={{
                  fontFamily: "var(--nb1-font-primary)",
                  fontSize: "20px",
                  lineHeight: "1.15",
                  marginTop: "18px"
                }}>{factory?.items?.[0]?.title}</div>
                <p style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "15.5px",
                  lineHeight: "1.65",
                  color: "rgba(240, 245, 255, 0.8)",
                  marginTop: "8px"
                }}>{factory?.items?.[0]?.body}</p>
              </div>
              <div style={{
                paddingTop: "20px",
                borderTop: "1px solid rgba(240, 245, 255, 0.24)"
              }}>
                <svg viewBox="0 0 24 24" width={26} height={26} fill="none" stroke="var(--nb1-lime)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M12 3l8 3.5v5.5c0 4.6-3.3 7.8-8 9.5-4.7-1.7-8-4.9-8-9.5V6.5z" />
                  <path d="M8.5 12.2l2.4 2.4 4.6-4.8" />
                </svg>
                <div style={{
                  fontFamily: "var(--nb1-font-primary)",
                  fontSize: "20px",
                  lineHeight: "1.15",
                  marginTop: "18px"
                }}>{factory?.items?.[1]?.title}</div>
                <p style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "15.5px",
                  lineHeight: "1.65",
                  color: "rgba(240, 245, 255, 0.8)",
                  marginTop: "8px"
                }}>{factory?.items?.[1]?.body}</p>
              </div>
              <div style={{
                paddingTop: "20px",
                borderTop: "1px solid rgba(240, 245, 255, 0.24)"
              }}>
                <svg viewBox="0 0 24 24" width={26} height={26} fill="none" stroke="var(--nb1-lime)" strokeWidth="1.6" strokeLinecap="round">
                  <circle cx="10.5" cy="10.5" r="6.5" />
                  <path d="M15.5 15.5L21 21" />
                </svg>
                <div style={{
                  fontFamily: "var(--nb1-font-primary)",
                  fontSize: "20px",
                  lineHeight: "1.15",
                  marginTop: "18px"
                }}>{factory?.items?.[2]?.title}</div>
                <p style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "15.5px",
                  lineHeight: "1.65",
                  color: "rgba(240, 245, 255, 0.8)",
                  marginTop: "8px"
                }}>{factory?.items?.[2]?.body}</p>
              </div>
              <div style={{
                paddingTop: "20px",
                borderTop: "1px solid rgba(240, 245, 255, 0.24)"
              }}>
                <svg viewBox="0 0 24 24" width={26} height={26} fill="none" stroke="var(--nb1-lime)" strokeWidth="1.6" strokeLinecap="round">
                  <path d="M4 6h16" />
                  <path d="M4 12h12" />
                  <path d="M4 18h8" />
                </svg>
                <div style={{
                  fontFamily: "var(--nb1-font-primary)",
                  fontSize: "20px",
                  lineHeight: "1.15",
                  marginTop: "18px"
                }}>{factory?.items?.[3]?.title}</div>
                <p style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "15.5px",
                  lineHeight: "1.65",
                  color: "rgba(240, 245, 255, 0.8)",
                  marginTop: "8px"
                }}>{factory?.items?.[3]?.body}</p>
              </div>
            </div>
            <p style={{
              fontFamily: "var(--nb1-font-secondary)",
              fontSize: "14.5px",
              lineHeight: "1.65",
              color: "rgba(240, 245, 255, 0.72)",
              marginTop: "40px",
              maxWidth: "60ch"
            }}>{factory?.outro}</p>
          </div>
          <div style={{
            aspectRatio: "4 / 5",
            borderRadius: "28px",
            overflow: "hidden",
            background: "var(--nb1-warm-grey)"
          }}>
            <img style={{
              width: "100%",
              height: "100%",
              objectFit: "cover",
              display: "block"
            }} src={mediaUrl(factory?.image)} alt={factory?.imageAlt || mediaAlt(factory?.image)} />
          </div>
        </div>
      </div>
    </section>
  )
}

const RdStClean: React.FC<{ clean?: Props['clean'] | null }> = ({ clean }) => {
  // ---------------------------------------------------------------- state
  //
  // ONE ROW OPEN AT A TIME, and the mockup says so rather than this choosing:
  // it draws the first row expanded with a `−` and the other three collapsed
  // with a `+`, and it gives the collapsed rows NO <p> at all — the body is
  // absent from the DOM, not hidden in it. That is `when`, not `show`, and it
  // is why the repeat templates off row 0: the open row is the only one that
  // carries the paragraph to template from.
  //
  // The FAQ page's accordion is deliberately NOT this — there `open` is a Set,
  // because several of its rows stand open at once. Copying that here would
  // have been a plausible-looking mistake: same widget, different behaviour,
  // and only the mockup says which.
  const [open, setOpen] = useState(0)

  // Toggle rather than select, so clicking the open row closes it. -1 is "none
  // open", which is a state the mockup never draws but a visitor can reach.
  const onRow = (i: number) => () => setOpen((prev) => (prev === i ? -1 : i))

  return (
      <section style={{
        background: "var(--tint)",
        borderTop: "1px solid rgba(81, 71, 69, 0.16)",
        borderBottom: "1px solid rgba(81, 71, 69, 0.16)"
      }} className="rd-st-clean" id="clean" data-screen-label="Clean by design">
        <div style={{
          maxWidth: "1240px",
          margin: "0px auto",
          padding: "64px 20px"
        }} data-d="pad bigpad">
          <div style={{
            display: "grid",
            gridTemplateColumns: "1fr",
            gap: "40px",
            alignItems: "start"
          }} data-d="side">
            <div>
              <h2 style={{
                fontFamily: "var(--nb1-font-primary)",
                fontWeight: "400",
                fontSize: "clamp(30px, 5cqi, 50px)",
                lineHeight: "1",
                letterSpacing: "-0.025em",
                maxWidth: "22ch",
                textWrap: "balance"
              }}>{clean?.heading}</h2>
              <p style={{
                fontFamily: "var(--nb1-font-secondary)",
                fontSize: "17px",
                lineHeight: "1.6",
                color: "rgba(81, 71, 69, 0.86)",
                marginTop: "18px",
                maxWidth: "58ch",
                textWrap: "pretty"
              }}>{clean?.intro}</p>
              <div style={{
                display: "flex",
                flexDirection: "column",
                marginTop: "28px",
                borderBottom: "1px solid rgba(81, 71, 69, 0.2)"
              }}>
                {(clean?.items || []).map((cl, cli) => (
                  <div key={cli} style={{
                    borderTop: "1px solid rgba(81, 71, 69, 0.2)"
                  }}>
                    <button style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "14px",
                      width: "100%",
                      padding: "18px 0px",
                      border: "0px",
                      background: "transparent",
                      cursor: "pointer",
                      textAlign: "left",
                      color: "var(--nb1-dark-brown)"
                    }} aria-expanded={open === cli ? 'true' : 'false'} onClick={onRow(cli)}>
                      <span style={{
                        flex: "0 0 auto",
                        width: "24px",
                        height: "24px",
                        borderRadius: "50%",
                        background: "var(--nb1-lime)",
                        color: "var(--nb1-black)",
                        display: "grid",
                        placeItems: "center",
                        fontSize: "13px"
                      }} aria-hidden="true">{"\u2713"}</span>
                      <span style={{
                        flex: "1 1 0%",
                        fontFamily: "var(--nb1-font-primary)",
                        fontSize: "20px",
                        lineHeight: "1.2"
                      }}>{cl.title}</span>
                      <span style={{
                        fontFamily: "var(--nb1-font-secondary)",
                        fontSize: "22px",
                        lineHeight: "1"
                      }} aria-hidden="true">{open === cli ? '−' : '+'}</span>
                    </button>
                    {(open === cli) ? (
                      <p style={{
                        fontFamily: "var(--nb1-font-secondary)",
                        fontSize: "16px",
                        lineHeight: "1.6",
                        color: "rgba(81, 71, 69, 0.86)",
                        padding: "0px 0px 20px 38px",
                        maxWidth: "56ch"
                      }}>{cl.body}</p>
                    ) : null}
                  </div>
                ))}
              </div>
            </div>
            <div style={{
              position: "relative"
            }}>
              <div style={{
                display: "grid",
                gridTemplateColumns: "1fr 1fr",
                gap: "14px"
              }}>
                {(clean?.strip || []).map((sp, spi) => (
                  <div key={spi} style={{
                    aspectRatio: "1 / 1",
                    borderRadius: "22px",
                    overflow: "hidden",
                    background: "var(--nb1-warm-grey)"
                  }}>
                    <img style={{
                      width: "100%",
                      height: "100%",
                      objectFit: "cover",
                      display: "block"
                    }} src={mediaUrl(sp.image)} alt={sp.imageAlt || mediaAlt(sp.image)} />
                  </div>
                ))}
              </div>
              <div style={{
                position: "absolute",
                left: "50%",
                top: "50%",
                transform: "translate(-50%, -50%)",
                width: "clamp(112px, 24%, 144px)",
                aspectRatio: "1 / 1",
                borderRadius: "22px",
                background: "rgb(255, 255, 255)",
                boxShadow: "rgba(81, 71, 69, 0.45) 0px 18px 40px -18px",
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                justifyContent: "center",
                gap: "10px",
                padding: "14px",
                textAlign: "center"
              }}>
                <img style={{
                  width: "72%",
                  height: "auto",
                  display: "block"
                }} src={mediaUrl(clean?.badge)} alt={clean?.badgeAlt || mediaAlt(clean?.badge)} />
              </div>
            </div>
          </div>
        </div>
      </section>
  )
}

const RdStBoard: React.FC<{ board?: Props['board'] | null, locale?: AppLocale }> = ({ board, locale }) => {
  return (
    <section style={{
      background: "var(--nb1-cool-grey)"
    }} className="rd-st-board" id="board" data-screen-label="Science board">
      <div style={{
        maxWidth: "1240px",
        margin: "0px auto",
        padding: "64px 20px"
      }} data-d="pad bigpad">
        <div style={{
          display: "grid",
          gridTemplateColumns: "1fr",
          gap: "40px",
          alignItems: "center"
        }} data-d="side">
          <div style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "flex-start"
          }}>
            <h2 style={{
              fontFamily: "var(--nb1-font-primary)",
              fontWeight: "400",
              fontSize: "clamp(30px, 5cqi, 50px)",
              lineHeight: "1",
              letterSpacing: "-0.025em",
              maxWidth: "22ch",
              textWrap: "balance"
            }}>{board?.heading}</h2>
            <p style={{
              fontFamily: "var(--nb1-font-secondary)",
              fontSize: "17px",
              lineHeight: "1.6",
              color: "rgba(81, 71, 69, 0.86)",
              marginTop: "18px",
              maxWidth: "58ch",
              textWrap: "pretty"
            }}>{board?.body}</p>
            <a style={{
              fontFamily: "var(--nb1-font-tertiary)",
              textTransform: "uppercase",
              letterSpacing: "0.1em",
              fontSize: "12px",
              marginTop: "26px",
              borderBottom: "1.5px solid var(--nb1-dark-brown)",
              paddingBottom: "3px"
            }} href={stPath(board?.ctaHref, locale)}>{board?.ctaLabel}</a>
          </div>
          <div style={{
            background: "rgb(255, 255, 255)",
            borderRadius: "20px",
            padding: "28px 26px",
            boxShadow: "inset 0 0 0 1px var(--nb1-hairline),0 26px 50px -36px rgba(81,71,69,.45)"
          }}>
            <div style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              gap: "20px",
              flexWrap: "wrap"
            }}>
              <div style={{
                display: "flex",
                alignItems: "flex-end",
                gap: "12px"
              }}>
                <span style={{
                  fontFamily: "var(--nb1-font-primary)",
                  fontSize: "72px",
                  lineHeight: "0.85"
                }}>{board?.statValue}</span>
                <span style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "15px",
                  lineHeight: "1.3"
                }}>
                  {board?.statLineOne}
                  <br />
                  {board?.statLineTwo}
                </span>
              </div>
              <div style={{
                display: "flex"
              }}>
                {(board?.avatars || []).map((av, avi) => (
                  <img key={avi} style={{
                    width: "44px",
                    height: "44px",
                    borderRadius: "50%",
                    objectFit: "cover",
                    objectPosition: "center 20%",
                    marginLeft: "-10px",
                    boxShadow: "rgb(255, 255, 255) 0px 0px 0px 3px",
                    background: "var(--nb1-warm-grey)"
                  }} src={mediaUrl(av.image)} alt={av.imageAlt || mediaAlt(av.image)} />
                ))}
              </div>
            </div>
            <p style={{
              fontFamily: "var(--nb1-font-secondary)",
              fontSize: "16px",
              lineHeight: "1.55",
              marginTop: "22px",
              paddingTop: "20px",
              borderTop: "1px solid var(--nb1-hairline)"
            }}>{board?.note}</p>
          </div>
        </div>
      </div>
    </section>
  )
}

const RdStProof: React.FC<{ proof?: Props['proof'] | null }> = ({ proof }) => {
  return (
    <section style={{
      background: "var(--tint)",
      borderTop: "1px solid rgba(81, 71, 69, 0.16)",
      borderBottom: "1px solid rgba(81, 71, 69, 0.16)"
    }} className="rd-st-proof" id="proof" data-screen-label="Proof">
      <div style={{
        maxWidth: "1240px",
        margin: "0px auto",
        padding: "64px 20px"
      }} data-d="pad bigpad">
        <h2 style={{
          fontFamily: "var(--nb1-font-primary)",
          fontWeight: "400",
          fontSize: "clamp(30px, 5cqi, 50px)",
          lineHeight: "1",
          letterSpacing: "-0.025em",
          maxWidth: "22ch",
          textWrap: "balance"
        }}>{proof?.heading}</h2>
        <p style={{
          fontFamily: "var(--nb1-font-secondary)",
          fontSize: "17px",
          lineHeight: "1.6",
          color: "rgba(81, 71, 69, 0.86)",
          marginTop: "18px",
          maxWidth: "58ch",
          textWrap: "pretty"
        }}>{proof?.intro}</p>
        <div style={{
          display: "grid",
          gridTemplateColumns: "1fr",
          gap: "18px",
          marginTop: "36px"
        }} data-m="std3">
          {(proof?.docs || []).map((d, di) => (
            <div key={di} style={{
              display: "flex",
              flexDirection: "column",
              background: "rgb(255, 255, 255)",
              borderRadius: "18px",
              overflow: "hidden",
              boxShadow: "inset 0 0 0 1px var(--nb1-hairline)"
            }}>
              <div style={{
                aspectRatio: "4 / 3",
                background: "var(--nb1-warm-grey)"
              }}>
                <img style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                  display: "block"
                }} src={mediaUrl(d.image)} alt={d.imageAlt || mediaAlt(d.image)} />
              </div>
              <div style={{
                display: "flex",
                flexDirection: "column",
                flex: "1 1 0%",
                padding: "20px 20px 18px"
              }}>
                <div style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  gap: "10px"
                }}>
                  <span style={{
                    fontFamily: "var(--nb1-font-tertiary)",
                    textTransform: "uppercase",
                    letterSpacing: "0.1em",
                    fontSize: "12px",
                    color: "rgba(81, 71, 69, 0.8)"
                  }}>{d.kicker}</span>
                  <span style={{
                    fontFamily: "var(--nb1-font-secondary)",
                    fontSize: "13px",
                    padding: "0.35em 0.8em",
                    borderRadius: "999px",
                    background: "var(--nb1-lime)",
                    color: "var(--nb1-black)"
                  }}>{d.status}</span>
                </div>
                <h3 style={{
                  fontFamily: "var(--nb1-font-primary)",
                  fontWeight: "400",
                  fontSize: "23px",
                  lineHeight: "1.12",
                  marginTop: "16px"
                }}>{d.title}</h3>
                <p style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "15.5px",
                  lineHeight: "1.55",
                  color: "rgba(81, 71, 69, 0.86)",
                  marginTop: "8px"
                }}>{d.body}</p>
                <div style={{
                  display: "flex",
                  flexDirection: "column",
                  marginTop: "16px"
                }}>
                  {(stRows(d.rows) || []).map((rw, rwi) => (
                    <div key={rwi} style={{
                      display: "flex",
                      justifyContent: "space-between",
                      gap: "12px",
                      padding: "9px 0px",
                      borderTop: "1px solid var(--nb1-hairline)",
                      fontFamily: "var(--nb1-font-secondary)",
                      fontSize: "15px"
                    }}>
                      <span style={{
                        color: "rgba(81, 71, 69, 0.8)"
                      }}>{rw.label}</span>
                      <span>{rw.value}</span>
                    </div>
                  ))}
                </div>
                <div style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "13.5px",
                  lineHeight: "1.45",
                  color: "rgba(81, 71, 69, 0.8)",
                  marginTop: "auto",
                  paddingTop: "14px"
                }}>{d.foot}</div>
              </div>
            </div>
          ))}
        </div>
        <p style={{
          fontFamily: "var(--nb1-font-secondary)",
          fontSize: "14px",
          lineHeight: "1.6",
          color: "rgba(81, 71, 69, 0.8)",
          marginTop: "26px",
          maxWidth: "80ch"
        }}>{proof?.note}</p>
      </div>
    </section>
  )
}

const RdStPlans: React.FC<{ plans?: Props['plans'] | null, locale?: AppLocale }> = ({ locale, plans }) => {
  return (
    <section style={{
      background: "var(--nb1-cool-grey)"
    }} className="rd-st-plans" id="plans" data-screen-label="Choose your plan">
      <div style={{
        maxWidth: "1240px",
        margin: "0px auto",
        padding: "64px 20px"
      }} data-d="pad bigpad">
        <div style={{
          textAlign: "center",
          display: "flex",
          flexDirection: "column",
          alignItems: "center"
        }}>
          <h2 style={{
            fontFamily: "var(--nb1-font-primary)",
            fontWeight: "400",
            fontSize: "clamp(30px, 5cqi, 50px)",
            lineHeight: "1",
            letterSpacing: "-0.025em",
            maxWidth: "22ch",
            textWrap: "balance"
          }}>{plans?.heading}</h2>
          <p style={{
            fontFamily: "var(--nb1-font-secondary)",
            fontSize: "17px",
            lineHeight: "1.6",
            color: "rgba(81, 71, 69, 0.86)",
            marginTop: "18px",
            maxWidth: "58ch",
            textWrap: "pretty"
          }}>{plans?.intro}</p>
        </div>
        <div style={{
          display: "grid",
          gridTemplateColumns: "1fr",
          gap: "18px",
          margin: "36px auto 0px",
          maxWidth: "900px"
        }} data-m="std2">
          {(plans?.tiers || []).map((t, ti) => (
            <div key={ti} style={!!t.badge ? {
              display: "flex",
              flexDirection: "column",
              padding: "28px 26px",
              borderRadius: "20px",
              background: "rgb(255, 255, 255)",
              boxShadow: "inset 0 0 0 1.5px var(--nb1-dark-brown), 0 26px 50px -36px rgba(81,71,69,.45)"
            } : {
              display: "flex",
              flexDirection: "column",
              padding: "28px 26px",
              borderRadius: "20px",
              background: "rgb(255, 255, 255)",
              boxShadow: "inset 0 0 0 1px var(--nb1-hairline)"
            }}>
              <div style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                gap: "12px"
              }}>
                <span style={{
                  fontFamily: "var(--nb1-font-primary)",
                  fontSize: "30px",
                  lineHeight: "1"
                }}>{t.name}</span>
                {(t.badge) ? (
                  <span style={{
                    fontFamily: "var(--nb1-font-secondary)",
                    fontSize: "13px",
                    padding: "0.4em 0.9em",
                    borderRadius: "999px",
                    background: "var(--nb1-lime)",
                    color: "var(--nb1-black)"
                  }}>{t.badge}</span>
                ) : null}
              </div>
              <p style={{
                fontFamily: "var(--nb1-font-secondary)",
                fontSize: "16px",
                lineHeight: "1.5",
                color: "rgba(81, 71, 69, 0.86)",
                marginTop: "10px"
              }}>{t.blurb}</p>
              <div style={{
                display: "flex",
                alignItems: "baseline",
                gap: "6px",
                marginTop: "20px"
              }}>
                <span style={{
                  fontFamily: "var(--nb1-font-primary)",
                  fontSize: "46px",
                  lineHeight: "1",
                  letterSpacing: "-0.02em"
                }}>{t.price}</span>
                <span style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "15px",
                  color: "rgba(81, 71, 69, 0.8)"
                }}>{t.priceSuffix}</span>
              </div>
              <p style={{
                fontFamily: "var(--nb1-font-secondary)",
                fontSize: "14.5px",
                lineHeight: "1.5",
                color: "rgba(81, 71, 69, 0.8)",
                marginTop: "8px"
              }}>{t.priceNote}</p>
              <div style={{
                fontFamily: "var(--nb1-font-tertiary)",
                textTransform: "uppercase",
                letterSpacing: "0.1em",
                fontSize: "12px",
                color: "rgba(81, 71, 69, 0.8)",
                marginTop: "22px"
              }}>{t.listHeading}</div>
              <div style={{
                display: "flex",
                flexDirection: "column",
                gap: "9px",
                marginTop: "12px"
              }}>
                {(stLines(t.features) || []).map((f, fi) => (
                  <div key={fi} style={{
                    display: "flex",
                    gap: "10px",
                    fontFamily: "var(--nb1-font-secondary)",
                    fontSize: "15.5px",
                    lineHeight: "1.4"
                  }}>
                    <span aria-hidden="true">{"\u2713"}</span>
                    <span>{f}</span>
                  </div>
                ))}
              </div>
              <div style={{
                marginTop: "auto",
                paddingTop: "26px"
              }}>
                <a style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: "1.1em",
                  borderRadius: "999px",
                  background: "var(--nb1-lime)",
                  color: "var(--nb1-black)",
                  fontFamily: "var(--nb1-font-tertiary)",
                  textTransform: "uppercase",
                  letterSpacing: "0.08em",
                  fontSize: "14px",
                  padding: "0.95em 1.4em",
                  whiteSpace: "nowrap",
                  flexShrink: "0"
                }} href={stPath(t.ctaHref, locale)}>
                  <span>{t.ctaLabel}</span>
                  <span style={{
                    fontSize: "1.05em",
                    lineHeight: "1"
                  }}>{"\u2197"}</span>
                </a>
              </div>
            </div>
          ))}
        </div>
        <p style={{
          fontFamily: "var(--nb1-font-secondary)",
          fontSize: "14.5px",
          lineHeight: "1.6",
          color: "rgba(81, 71, 69, 0.8)",
          marginTop: "24px",
          textAlign: "center"
        }}>{plans?.note}</p>
      </div>
    </section>
  )
}

/** The seven sections below the hero, in document order.
 *
 * RdSt mounts this once through `append.outside`, which takes a single
 * component — so this is where "eight screens, one block" is actually spelled
 * out. Adding a ninth section means adding it here and nowhere else.
 *
 * `locale` is threaded through because the board and plan CTAs resolve a slug
 * against it; the five sections without one ignore it.
 */
const RdStRest: React.FC<{
  rules?: Props['rules'] | null
  source?: Props['source'] | null
  factory?: Props['factory'] | null
  clean?: Props['clean'] | null
  board?: Props['board'] | null
  proof?: Props['proof'] | null
  plans?: Props['plans'] | null
  locale?: AppLocale
}> = ({ rules, source, factory, clean, board, proof, plans, locale }) => (
  <>
    <RdStRules rules={rules} />
    <RdStSource source={source} />
    <RdStFactory factory={factory} />
    <RdStClean clean={clean} />
    <RdStBoard board={board} locale={locale} />
    <RdStProof proof={proof} />
    <RdStPlans plans={plans} locale={locale} />
  </>
)

export const RdStInner: React.FC<Props & { locale?: AppLocale }> = ({ anchorId, board, clean, factory, hero, locale, plans, proof, rules, source }) => {
  return (
    <>
      <section style={{
        background: "var(--tint)",
        borderBottom: "1px solid rgba(81, 71, 69, 0.16)"
      }} className="rd-st" id={anchorId || undefined} data-screen-label="Hero">
        <div style={{
          maxWidth: "1240px",
          margin: "0px auto",
          padding: "96px 20px 64px"
        }} data-d="pad" data-m="stdhero">
          <h1 style={{
            fontFamily: "var(--nb1-font-primary)",
            fontWeight: "400",
            fontSize: "clamp(38px, 8cqi, 60px)",
            lineHeight: "1.02",
            letterSpacing: "-0.035em",
            maxWidth: "17ch",
            textWrap: "balance"
          }} data-d="bigh">{hero?.heading}</h1>
          <p style={{
            fontFamily: "var(--nb1-font-secondary)",
            fontSize: "clamp(17px, 2.2cqi, 20px)",
            lineHeight: "1.6",
            color: "rgba(81, 71, 69, 0.86)",
            marginTop: "24px",
            maxWidth: "58ch",
            textWrap: "pretty"
          }}>{hero?.intro}</p>
        </div>
      </section>
      <RdStRest rules={rules} source={source} factory={factory} clean={clean} board={board} proof={proof} plans={plans} locale={locale} />
    </>
  )
}

/* ── Exported wrapper (amount tokens) ─────────────────────────────────
 *
 * The plan cards quote money — £99 and £149 a month, £94 and £144 on a
 * four-month cycle. The mockup is drawn in pounds, so seeded verbatim a German
 * visitor reads pounds, which is the fault already fixed on the order, checkout
 * and FAQ pages.
 *
 * So the seed carries tokens instead: `{{99}}`, `{{94}}`, `{{149}}`, `{{144}}`.
 * RenderBlocks already resolved the REFS before this block rendered —
 * `usePriceTokens` walks every block's props — but it resolves only `price:`
 * and `fee:`, because `hasToken()` tests for those two words. A plain amount
 * matches neither and would reach the page literally.
 *
 * So the amounts are resolved HERE, at the root, once, over the whole props
 * tree — and that is why it sits on RdSt rather than on RdStPlans, which is
 * where the prices actually render. RdSt hands `plans` down to RdStRest and
 * RdStRest hands it to RdStPlans, so resolving at the top means every section
 * below is handed values that are already right. A wrapper on RdStPlans would
 * work too and would have to be remembered the next time a section quotes a
 * number.
 *
 * See _shared/amountTokens.ts for why this is per-block rather than one line
 * in usePriceTokens.
 */
export const RdSt: React.FC<Props & { locale?: AppLocale }> = (props) => (
  <RdStInner {...useAmountTokens(props, props.locale)} />
)

// RenderBlocks.client.tsx imports every block as `<Name>Component`; the alias
// keeps that one import name stable whatever the component itself is called.
export const RdStComponent = RdSt

export default RdSt
