'use client'

import React, { useState } from 'react'
import RichText from '@/components/RichText'
import type { RdFaqBlock as Props } from '@/payload-types'
import { useAmountTokens } from '@/blocks/redesign/_shared/amountTokens'
import type { AppLocale } from '@/i18n/config'

// GENERATED from manifests/section-23.json + bindings/RdFaq.json by
// tools/block_component.py — do not hand-edit; regenerate.
//
// Styles copied verbatim from the mockup; bindings replace content only.
// Layout and breakpoints come from rd-faq.css — this page's stylesheet,
// ported by port_css.py and rescoped from `.rd-block` to `.rd-faq` so it
// cannot reach any other page's blocks. That scope is why this root carries
// `rd-faq` and NOT `rd-block`.
//
// The FAQ page, one block — the hero and the questions the mockup draws as two screens.


/* GENERATED by tools/faq_assemble.py — do not hand-edit.
 *
 * The FAQ hero, lifted out of out/faqhero/Component.tsx so RdFaq can include
 * it. RdFaq mounts it as its own SIBLING (prepend.outside), because the mockup
 * draws the hero and the questions as two screens and a visitor sees one page.
 */

/** The `hero` field group of the block — not a block of its own.
 *
 * `Props` is what block_component.py aliases RdFaqBlock to at the top of the
 * generated module, and that alias is the only name in scope here: naming
 * RdFaqBlock directly asked for an identifier the file never imports. */
type FaqHeroProps = { hero?: Props['hero'] | null }

const RdFaqHero: React.FC<FaqHeroProps> = ({ hero }) => {
  return (
    <section style={{
      background: "var(--tint)",
      borderBottom: "1px solid rgba(81, 71, 69, 0.16)"
    }} className="rd-faq-hero" id="top" data-screen-label="Hero">
      <div style={{
        maxWidth: "1240px",
        margin: "0px auto",
        padding: "72px 20px 48px"
      }} data-d="pad">
        <h1 style={{
          fontFamily: "var(--nb1-font-primary)",
          fontWeight: "400",
          fontSize: "clamp(38px, 7cqi, 60px)",
          lineHeight: "1.02",
          letterSpacing: "-0.035em",
          maxWidth: "17ch",
          textWrap: "balance",
          margin: "0px"
        }} data-d="bigh">{hero?.heading}</h1>
        <p style={{
          fontFamily: "var(--nb1-font-secondary)",
          fontSize: "clamp(17px, 2.2cqi, 20px)",
          lineHeight: "1.6",
          color: "rgba(81, 71, 69, 0.86)",
          margin: "20px 0px 0px",
          maxWidth: "58ch",
          textWrap: "pretty"
        }}>{hero?.intro}</p>
      </div>
    </section>
  )
}

export const RdFaqInner: React.FC<Props & { locale?: AppLocale }> = ({ anchorId, calloutBody, calloutCtaHref, calloutCtaLabel, calloutHeading, groups, hero, locale }) => {
  // ---------------------------------------------------------------- state
  //
  // THE CURRENT FAQ PAGE'S LOGIC, carried across rather than reinvented —
  // src/blocks/FaqPage/Component.tsx. Three pieces, and each one is a decision
  // that page already made:
  //
  //   `open` is a SET, not an index. Several rows stand open at once; closing
  //   one leaves the others alone. The funnel's duration FAQ is the opposite —
  //   one row at a time — so this is not a detail to guess at.
  //   `groupId` gives each group a stable anchor the chips jump to.
  //   `pad` derives 01, 02 … from position.
  const [open, setOpen] = useState<Set<string>>(new Set())

  const isOpen = (gi: number, ii: number) => open.has(`${gi}-${ii}`)

  // The row is a native <details>, so a click would toggle it in the DOM on its
  // own and React would overwrite that on the next render — the two would
  // disagree, visibly, every other click. preventDefault leaves the open state
  // in exactly one place.
  const onRow = (gi: number, ii: number) => (e: React.MouseEvent) => {
    e.preventDefault()
    const k = `${gi}-${ii}`
    setOpen((prev) => {
      const next = new Set(prev)
      if (next.has(k)) next.delete(k)
      else next.add(k)
      return next
    })
  }

  // VERBATIM from the current FAQ page: the anchor a chip jumps to. Kebab from
  // the label, falling back to the index when a label is punctuation only —
  // `#faq-` repeated would make every chip jump to the first group.
  const groupId = (s?: string | null, i = 0) =>
    `faq-${(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || `g${i}`}`

  const pad = (n: number) => String(n).padStart(2, '0')

  // The callout's destination. The FAQ page that ships today writes
  // `href={calloutCtaHref || '#'}` raw, and that is the one place this block
  // does NOT copy it — because raw is how a link dies quietly.
  //
  // A bare `contact` is a RELATIVE url: from /en/faq-v2 the browser resolves it
  // to /en/contact, which looks right, and from /en/faq-v2/ it resolves to
  // /en/faq-v2/contact, which 404s. One trailing slash is the whole difference.
  // Worse, a bare slug can never be locale-correct on its own.
  //
  // So a bare slug is given the locale here, exactly as the order and duration
  // blocks do with their own `nextSlug` fields: the field holds a SLUG and the
  // locale is added at render, so one stored value is right in all nine.
  // Anything already absolute — a full url, a mailto, a tel, a hash, or a path
  // that starts with `/` — is passed through untouched, because an editor who
  // typed one of those meant it.
  const path = (s?: string | null) => {
    const v = (s || '').trim()
    if (!v) return '#'
    if (/^(?:[a-z][a-z0-9+.-]*:|\/\/|\/|#)/i.test(v)) return v
    return `/${locale || 'en'}/${v}`
  }

  return (
      <>
        <RdFaqHero hero={hero} />
        <section style={{
          background: "var(--nb1-cool-grey)"
        }} className="rd-faq" id={anchorId || 'faq'} data-screen-label="Questions">
          <div style={{
            maxWidth: "1240px",
            margin: "0px auto",
            padding: "40px 20px 88px"
          }} data-d="pad">
            <div style={{
              maxWidth: "860px"
            }}>
              {((groups?.length ?? 0) > 1) ? (
                <div style={{
                  display: "flex",
                  flexWrap: "wrap",
                  gap: "8px"
                }}>
                  {(groups || []).map((c, ci) => (
                    <a key={ci} style={{
                      fontFamily: "var(--nb1-font-secondary)",
                      fontSize: "15px",
                      padding: "0.6em 1.05em",
                      borderRadius: "999px",
                      boxShadow: "rgba(81, 71, 69, 0.28) 0px 0px 0px 1px inset",
                      color: "var(--nb1-dark-brown)"
                    }} href={`#${groupId(c.label, ci)}`}>{c.label}</a>
                  ))}
                </div>
              ) : null}
              {(groups || []).map((g, gi) => (
                <div key={gi} style={{
                  marginTop: "48px",
                  scrollMarginTop: "96px"
                }} id={groupId(g.label, gi)}>
                  <h2 style={{
                    display: "flex",
                    alignItems: "baseline",
                    gap: "14px",
                    fontFamily: "var(--nb1-font-primary)",
                    fontWeight: "400",
                    fontSize: "clamp(26px, 3.4cqi, 34px)",
                    lineHeight: "1.1",
                    margin: "0px 0px 14px"
                  }}>
                    <span style={{
                      fontFamily: "var(--nb1-font-tertiary)",
                      fontSize: "14px",
                      color: "rgba(81, 71, 69, 0.7)"
                    }}>{pad(gi + 1)}</span>
                    {g.label}
                  </h2>
                  {(g.items || []).map((it, ii) => (
                    <details key={ii} style={{
                      borderTop: "1px solid rgba(81, 71, 69, 0.2)"
                    }} open={isOpen(gi, ii) || undefined}>
                      <summary style={{
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "space-between",
                        gap: "18px",
                        padding: "20px 0px",
                        cursor: "pointer",
                        listStyle: "none",
                        fontFamily: "var(--nb1-font-primary)",
                        fontSize: "clamp(19px, 2.4cqi, 22px)",
                        lineHeight: "1.2"
                      }} onClick={onRow(gi, ii)}>
                        {it.question}
                        <span style={{
                          fontFamily: "var(--nb1-font-secondary)",
                          fontSize: "22px",
                          lineHeight: "1",
                          flex: "0 0 auto"
                        }} aria-hidden="true">{isOpen(gi, ii) ? '−' : '+'}</span>
                      </summary>
                      <div style={{
                        fontFamily: "var(--nb1-font-secondary)",
                        fontSize: "16px",
                        lineHeight: "1.65",
                        color: "rgba(81, 71, 69, 0.88)",
                        margin: "0px",
                        padding: "0px 0px 22px",
                        maxWidth: "64ch"
                      }}>
                        {(it.answer)?.root ? (
                          <RichText data={it.answer} enableGutter={false} enableProse={false} />
                        ) : null}
                      </div>
                    </details>
                  ))}
                  <div style={{
                    borderTop: "1px solid rgba(81, 71, 69, 0.2)"
                  }} />
                </div>
              ))}
              {(calloutHeading) ? (
                <div style={{
                  display: "flex",
                  flexWrap: "wrap",
                  alignItems: "center",
                  justifyContent: "space-between",
                  gap: "20px 32px",
                  marginTop: "40px",
                  background: "rgb(255, 255, 255)",
                  borderRadius: "22px",
                  padding: "28px 26px",
                  boxShadow: "inset 0 0 0 1px var(--nb1-hairline)"
                }}>
                  <div style={{
                    display: "flex",
                    flexDirection: "column",
                    gap: "6px",
                    maxWidth: "52ch"
                  }}>
                    <h3 style={{
                      fontFamily: "var(--nb1-font-primary)",
                      fontWeight: "400",
                      fontSize: "26px",
                      lineHeight: "1.1",
                      margin: "0px"
                    }}>{calloutHeading}</h3>
                    <p style={{
                      fontFamily: "var(--nb1-font-secondary)",
                      fontSize: "16px",
                      lineHeight: "1.65",
                      color: "rgba(81, 71, 69, 0.88)",
                      margin: "0px"
                    }}>{calloutBody}</p>
                  </div>
                  <a style={{
                    display: "inline-flex",
                    alignItems: "center",
                    gap: "1.1em",
                    borderRadius: "999px",
                    background: "var(--nb1-lime)",
                    color: "var(--nb1-black)",
                    fontFamily: "var(--nb1-font-tertiary)",
                    textTransform: "uppercase",
                    letterSpacing: "0.08em",
                    fontSize: "13px",
                    padding: "0.95em 1.4em",
                    whiteSpace: "nowrap",
                    flexShrink: "0"
                  }} href={path(calloutCtaHref)}>
                    <span>{calloutCtaLabel}</span>
                    <span style={{
                      fontSize: "1.05em",
                      lineHeight: "1"
                    }}>{"\u2197"}</span>
                  </a>
                </div>
              ) : null}
            </div>
          </div>
        </section>
      </>
  )
}

/* ── Exported wrapper (amount tokens) ─────────────────────────────────
 *
 * The FAQ answers quote money — "Core is £99 a month and Advanced £149",
 * "the price drops by £5 a month", "a one-time £49 kit fee". The mockup is
 * drawn in pounds, so seeded verbatim a German visitor reads pounds, which is
 * the same fault that was fixed on the order and checkout pages.
 *
 * So the seed carries tokens instead: `{{99}}`, `{{149}}`, `{{5}}`, `{{10}}`
 * and `{{fee:kit}}`. RenderBlocks already resolved the REFS before this block
 * rendered — `usePriceTokens` walks every block's props and its comment says
 * "including rich text" — but it resolves only `price:` and `fee:`, because
 * `hasToken()` tests for those two words. A plain amount matches neither and
 * would reach the page literally.
 *
 * So the amounts are resolved here, once, over the whole props tree. That walk
 * recurses through objects and arrays, which is what makes it reach the text
 * nodes inside a Lexical answer and not just the top-level strings.
 *
 * See _shared/amountTokens.ts for why this is per-block rather than one line
 * in usePriceTokens.
 */
export const RdFaq: React.FC<Props & { locale?: AppLocale }> = (props) => (
  <RdFaqInner {...useAmountTokens(props, props.locale)} />
)

// RenderBlocks.client.tsx imports every block as `<Name>Component`; the alias
// keeps that one import name stable whatever the component itself is called.
export const RdFaqComponent = RdFaq

export default RdFaq
