'use client'

import React, { useState } from 'react'
import RichText from '@/components/RichText'
import type { RdPgPlansBlock as Props } from '@/payload-types'

// GENERATED from manifests/section-02.json + bindings/RdPgPlans.json by
// tools/block_component.py — do not hand-edit; regenerate.
//
// Styles copied verbatim from the mockup; bindings replace content only.
// Layout and breakpoints come from rd-pg.css — the Our Plans stylesheet, ported
// by port_css.py and scoped to `.rd-pg` so it cannot reach the homepage's
// blocks. That scope is why every root here carries `rd-block rd-pg rd-<name>`.
//
// The comparison table is hidden until the button under the cards is pressed; `compareOpen` drives both the table's display and the chevron's rotation.


/**
 * The comparison grid.
 *
 * GENERATED by tools/plans_grid.py — do not hand-edit; the styles below are
 * lifted from the manifest, not retyped.
 *
 * Written as code rather than mapped from the mockup's markup, because the
 * mockup's markup cannot be mapped: the table is ONE CSS grid whose 57 children
 * are a flat list — a header row, then for each section a heading cell plus two
 * empty ones, then three cells per row, then a spacer and two CTA cells. A
 * `repeat` maps a container's element children over one template, and there is
 * no template here; the children are not alike.
 *
 * So the cells are generated from the data instead. The Advanced column is NOT
 * the Core column with different text: its value cells are tinted, its third
 * group heading is a stronger tint, and its plan name is coloured rather than
 * dimmed. Those three are separate styles below for that reason.
 *
 * The three value kinds — a round check, a dimmed dash, free text — are told
 * apart in the mockup by their styling, which is how the defaults were derived,
 * and they are explicit fields here so an editor is never guessing which string
 * renders as a tick.
 */
type Plan = { name?: string | null; price?: string | null; priceSuffix?: string | null }
type Row = {
  label?: string | null
  coreKind?: string | null
  coreText?: string | null
  advancedKind?: string | null
  advancedText?: string | null
}
type Group = { title?: string | null; rows?: Row[] | null }
type Cta = {
  coreUrl?: string | null
  coreLabel?: string | null
  advancedUrl?: string | null
  advancedLabel?: string | null
}

const CompareValue: React.FC<{ kind?: string | null; text?: string | null }> = ({ kind, text }) => {
  if (kind === 'included') return <span style={{
    width: "22px",
    height: "22px",
    borderRadius: "50%",
    background: "var(--nb1-blue-grey)",
    color: "var(--nb1-dark-brown)",
    display: "inline-grid",
    placeItems: "center",
    fontSize: "11px"
  }}>{'\u2713'}</span>
  if (kind === 'text') return <span style={{
    fontFamily: "var(--nb1-font-secondary)",
    fontSize: "13.5px"
  }}>{text}</span>
  return <span style={{
    opacity: "0.35",
    fontSize: "15px"
  }}>{'\u2014'}</span>
}

const PlanHead: React.FC<{ plan?: Plan | null; cell: React.CSSProperties; name: React.CSSProperties }> = ({
  plan,
  cell,
  name,
}) => (
  <div style={cell}>
    <div style={name}>{plan?.name}</div>
    <div style={{
      fontFamily: "var(--nb1-font-primary)",
      fontSize: "26px",
      lineHeight: "1",
      marginTop: "6px"
    }} data-m="cmpprice">
      {plan?.price}
      <span style={{
        fontFamily: "var(--nb1-font-secondary)",
        fontSize: "13px",
        opacity: "0.6"
      }}>{plan?.priceSuffix}</span>
    </div>
  </div>
)

const PlansCompareGrid: React.FC<{
  groups?: Group[] | null
  core?: Plan | null
  advanced?: Plan | null
  cta?: Cta | null
}> = ({ groups, core, advanced, cta }) => (
  <>
    <div style={{
      background: "var(--nb1-dark-brown)"
    }} />
    <PlanHead plan={core} cell={{
      background: "var(--nb1-dark-brown)",
      color: "var(--nb1-cool-grey)",
      textAlign: "center",
      padding: "22px 20px"
    }} name={{
      fontFamily: "var(--nb1-font-tertiary)",
      textTransform: "uppercase",
      letterSpacing: "0.1em",
      fontSize: "11px",
      opacity: "0.7"
    }} />
    <PlanHead plan={advanced} cell={{
      background: "rgb(70, 60, 58)",
      color: "var(--nb1-cool-grey)",
      textAlign: "center",
      padding: "22px 20px"
    }} name={{
      fontFamily: "var(--nb1-font-tertiary)",
      textTransform: "uppercase",
      letterSpacing: "0.1em",
      fontSize: "11px",
      color: "var(--nb1-blue)"
    }} />
    {(groups ?? []).map((group, gi) => (
      <React.Fragment key={gi}>
        <div style={{
          fontFamily: "var(--nb1-font-tertiary)",
          textTransform: "uppercase",
          letterSpacing: "0.1em",
          fontSize: "11px",
          color: "var(--nb1-dark-brown)",
          opacity: "0.72",
          padding: "16px 20px",
          background: "rgba(179, 231, 243, 0.42)"
        }}>{group.title}</div>
        <div style={{
          fontFamily: "var(--nb1-font-tertiary)",
          textTransform: "uppercase",
          letterSpacing: "0.1em",
          fontSize: "11px",
          color: "var(--nb1-dark-brown)",
          opacity: "0.72",
          padding: "16px 20px",
          background: "rgba(179, 231, 243, 0.42)"
        }} />
        <div style={{
          fontFamily: "var(--nb1-font-tertiary)",
          textTransform: "uppercase",
          letterSpacing: "0.1em",
          fontSize: "11px",
          color: "var(--nb1-dark-brown)",
          opacity: "0.72",
          padding: "16px 20px",
          background: "rgba(179, 231, 243, 0.55)"
        }} />
        {(group.rows ?? []).map((row, ri) => (
          <React.Fragment key={ri}>
            <div style={{
              fontFamily: "var(--nb1-font-secondary)",
              fontSize: "14.5px",
              padding: "15px 20px",
              borderTop: "1px solid rgba(81, 71, 69, 0.12)"
            }}>{row.label}</div>
            <div style={{
              textAlign: "center",
              padding: "15px 20px",
              borderTop: "1px solid rgba(81, 71, 69, 0.12)"
            }}>
              <CompareValue kind={row.coreKind} text={row.coreText} />
            </div>
            <div style={{
              textAlign: "center",
              padding: "15px 20px",
              borderTop: "1px solid rgba(81, 71, 69, 0.12)",
              background: "rgba(179, 231, 243, 0.18)"
            }}>
              <CompareValue kind={row.advancedKind} text={row.advancedText} />
            </div>
          </React.Fragment>
        ))}
      </React.Fragment>
    ))}
    <div style={{
      borderTop: "1px solid rgba(81, 71, 69, 0.12)"
    }} />
    <div style={{
      borderTop: "1px solid rgba(81, 71, 69, 0.12)",
      padding: "22px 16px",
      display: "flex",
      justifyContent: "center"
    }}>
      <a href={cta?.coreUrl || '#'} style={{
        fontFamily: "var(--nb1-font-tertiary)",
        textTransform: "uppercase",
        letterSpacing: "0.08em",
        fontSize: "12px",
        border: "1.5px solid var(--nb1-dark-brown)",
        color: "var(--nb1-dark-brown)",
        padding: "0.9em 1.4em",
        borderRadius: "999px",
        whiteSpace: "nowrap"
      }}>
        {cta?.coreLabel}
      </a>
    </div>
    <div style={{
      borderTop: "1px solid rgba(81, 71, 69, 0.12)",
      background: "rgba(179, 231, 243, 0.18)",
      padding: "22px 16px",
      display: "flex",
      justifyContent: "center"
    }}>
      <a href={cta?.advancedUrl || '#'} style={{
        display: "inline-flex",
        alignItems: "center",
        gap: "1.1em",
        fontFamily: "var(--nb1-font-tertiary)",
        textTransform: "uppercase",
        letterSpacing: "0.08em",
        fontSize: "12px",
        background: "var(--cta)",
        color: "var(--nb1-black)",
        padding: "0.9em 1.4em",
        borderRadius: "999px",
        whiteSpace: "nowrap",
        flexShrink: "0"
      }}>
        <span>{cta?.advancedLabel}</span>
        <span style={{
          fontSize: "1.05em",
          lineHeight: "1"
        }}>{'\u2197'}</span>
      </a>
    </div>
  </>
)

export const RdPgPlans: React.FC<Props> = ({ advanced, anchorId, assurances, compare, compareCloseLabel, compareCta, compareOpenLabel, core, heading, intro }) => {
  const [compareOpen, setCompareOpen] = useState(false)

  return (
      <section style={{
        maxWidth: "1240px",
        margin: "0px auto",
        padding: "96px 48px"
      }} className="rd-pg rd-pgplans" id={anchorId || undefined}>
        <div style={{
          textAlign: "center",
          maxWidth: "640px",
          margin: "0px auto 52px"
        }}>
          <div style={{
            fontFamily: "var(--nb1-font-primary)",
            fontWeight: "400",
            fontSize: "clamp(40px, 5vw, 58px)",
            lineHeight: "0.95",
            letterSpacing: "-0.02em"
          }}>
            {(heading)?.root ? (
              <RichText data={heading} enableGutter={false} enableProse={false} />
            ) : null}
          </div>
          <p style={{
            fontFamily: "var(--nb1-font-secondary)",
            fontSize: "19px",
            lineHeight: "1.4",
            opacity: "0.78",
            marginTop: "18px"
          }}>{intro}</p>
        </div>
        <div style={{
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gap: "22px",
          alignItems: "stretch"
        }}>
          <article style={{
            background: "var(--nb1-cool-grey)",
            border: "1.5px solid rgba(81, 71, 69, 0.18)",
            borderRadius: "24px",
            padding: "38px 34px",
            display: "flex",
            flexDirection: "column",
            boxShadow: "rgba(81, 71, 69, 0.5) 0px 30px 60px -46px"
          }}>
            <div style={{
              fontFamily: "var(--nb1-font-tertiary)",
              textTransform: "uppercase",
              letterSpacing: "0.12em",
              fontSize: "13px"
            }}>{core?.name}</div>
            <p style={{
              fontFamily: "var(--nb1-font-secondary)",
              fontSize: "17px",
              lineHeight: "1.35",
              opacity: "0.78",
              marginTop: "12px",
              minHeight: "48px"
            }}>{core?.tagline}</p>
            <div style={{
              fontFamily: "var(--nb1-font-primary)",
              fontSize: "56px",
              lineHeight: "1",
              marginTop: "16px"
            }}>
              {core?.price}
              <span style={{
                fontFamily: "var(--nb1-font-secondary)",
                fontSize: "18px",
                opacity: "0.6"
              }}>{core?.priceSuffix}</span>
            </div>
            <p style={{
              fontFamily: "var(--nb1-font-secondary)",
              fontSize: "14.5px",
              opacity: "0.7",
              marginTop: "12px"
            }}>{core?.terms}</p>
            <div style={{
              fontFamily: "var(--nb1-font-tertiary)",
              textTransform: "uppercase",
              letterSpacing: "0.1em",
              fontSize: "11px",
              opacity: "0.55",
              margin: "24px 0px 14px",
              borderTop: "1px solid rgba(81, 71, 69, 0.14)",
              paddingTop: "20px"
            }}>{core?.listLabel}</div>
            <ul style={{
              listStyle: "none",
              padding: "0px",
              margin: "0px",
              display: "flex",
              flexDirection: "column",
              gap: "12px",
              flex: "1 1 0%"
            }}>
              {(core?.features || []).map((feat, featIdx) => (
                <li key={featIdx} style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "12px",
                  fontSize: "15px"
                }}>
                  <span style={{
                    width: "22px",
                    height: "22px",
                    flex: "0 0 auto",
                    borderRadius: "50%",
                    background: "var(--nb1-blue-grey)",
                    color: "var(--nb1-dark-brown)",
                    display: "grid",
                    placeItems: "center",
                    fontSize: "11px"
                  }}>{"\u2713"}</span>
                  {feat.label}
                </li>
              ))}
            </ul>
            <a style={{
              marginTop: "26px",
              textAlign: "center",
              fontFamily: "var(--nb1-font-tertiary)",
              textTransform: "uppercase",
              letterSpacing: "0.08em",
              fontSize: "14px",
              border: "1.5px solid var(--nb1-dark-brown)",
              color: "var(--nb1-dark-brown)",
              padding: "1.1em",
              borderRadius: "999px"
            }} href={core?.cta?.url || '#'}>{core?.cta?.label}</a>
            <p style={{
              fontFamily: "var(--nb1-font-secondary)",
              fontSize: "13px",
              lineHeight: "1.4",
              opacity: "0.6",
              textAlign: "center",
              marginTop: "14px"
            }}>{core?.note}</p>
          </article>
          <article style={{
            background: "var(--nb1-dark-brown)",
            color: "var(--nb1-cool-grey)",
            borderRadius: "24px",
            padding: "38px 34px",
            display: "flex",
            flexDirection: "column",
            position: "relative",
            boxShadow: "rgba(81, 71, 69, 0.7) 0px 40px 80px -40px"
          }}>
            <span style={{
              position: "absolute",
              top: "-13px",
              left: "34px",
              fontFamily: "var(--nb1-font-tertiary)",
              textTransform: "uppercase",
              letterSpacing: "0.08em",
              fontSize: "12px",
              background: "var(--cta)",
              color: "var(--nb1-black)",
              padding: "0.6em 1em",
              borderRadius: "999px"
            }}>{advanced?.badge}</span>
            <div style={{
              fontFamily: "var(--nb1-font-tertiary)",
              textTransform: "uppercase",
              letterSpacing: "0.12em",
              fontSize: "13px"
            }}>{advanced?.name}</div>
            <p style={{
              fontFamily: "var(--nb1-font-secondary)",
              fontSize: "17px",
              lineHeight: "1.35",
              opacity: "0.82",
              marginTop: "12px",
              minHeight: "48px"
            }}>{advanced?.tagline}</p>
            <div style={{
              fontFamily: "var(--nb1-font-primary)",
              fontSize: "56px",
              lineHeight: "1",
              marginTop: "16px"
            }}>
              {advanced?.price}
              <span style={{
                fontFamily: "var(--nb1-font-secondary)",
                fontSize: "18px",
                opacity: "0.6"
              }}>{advanced?.priceSuffix}</span>
            </div>
            <p style={{
              fontFamily: "var(--nb1-font-secondary)",
              fontSize: "14.5px",
              opacity: "0.72",
              marginTop: "12px"
            }}>{advanced?.terms}</p>
            <div style={{
              fontFamily: "var(--nb1-font-tertiary)",
              textTransform: "uppercase",
              letterSpacing: "0.1em",
              fontSize: "11px",
              opacity: "0.55",
              margin: "24px 0px 14px",
              borderTop: "1px solid rgba(240, 245, 255, 0.16)",
              paddingTop: "20px"
            }}>{advanced?.listLabel}</div>
            <ul style={{
              listStyle: "none",
              padding: "0px",
              margin: "0px",
              display: "flex",
              flexDirection: "column",
              gap: "12px",
              flex: "1 1 0%"
            }}>
              {(advanced?.features || []).map((aFeat, aFeatIdx) => (
                <li key={aFeatIdx} style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "12px",
                  fontSize: "15px"
                }}>
                  <span style={{
                    width: "22px",
                    height: "22px",
                    flex: "0 0 auto",
                    borderRadius: "50%",
                    background: "var(--cta)",
                    color: "var(--nb1-black)",
                    display: "grid",
                    placeItems: "center",
                    fontSize: "11px"
                  }}>{"\u2713"}</span>
                  {aFeat.label}
                </li>
              ))}
            </ul>
            <a style={{
              marginTop: "26px",
              textAlign: "center",
              fontFamily: "var(--nb1-font-tertiary)",
              textTransform: "uppercase",
              letterSpacing: "0.08em",
              fontSize: "14px",
              background: "var(--cta)",
              color: "var(--nb1-black)",
              padding: "1.1em",
              borderRadius: "999px"
            }} href={advanced?.cta?.url || '#'}>{advanced?.cta?.label}</a>
            <p style={{
              fontFamily: "var(--nb1-font-secondary)",
              fontSize: "13px",
              lineHeight: "1.4",
              opacity: "0.6",
              textAlign: "center",
              marginTop: "14px"
            }}>{advanced?.note}</p>
          </article>
        </div>
        <div style={{
          display: "flex",
          justifyContent: "center",
          marginTop: "34px"
        }}>
          <button style={{
            display: "inline-flex",
            alignItems: "center",
            gap: "14px",
            fontFamily: "var(--nb1-font-tertiary)",
            textTransform: "uppercase",
            letterSpacing: "0.08em",
            fontSize: "13px",
            background: "transparent",
            color: "var(--nb1-dark-brown)",
            border: "1.5px solid rgba(81, 71, 69, 0.28)",
            borderRadius: "999px",
            padding: "1em 1.6em",
            cursor: "pointer",
            whiteSpace: "nowrap"
          }} type={'button'} aria-expanded={compareOpen} onClick={() => setCompareOpen((v: boolean) => !v)}>
            <span>{compareOpen ? (compareCloseLabel || 'Hide the full comparison') : (compareOpenLabel || 'Compare in full')}</span>
            <span style={{
              width: "26px",
              height: "26px",
              flex: "0 0 auto",
              borderRadius: "50%",
              background: "var(--nb1-blue-grey)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center"
            }}>
              <svg style={{ ...{
                transition: "transform 0.2s",
                display: "block"
              }, transform: compareOpen ? 'rotate(180deg)' : 'none' }} viewBox="0 0 24 24" width="12" height="12" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="6 9 12 15 18 9" />
              </svg>
            </span>
          </button>
        </div>
        <div style={{ display: compareOpen ? undefined : 'none' }}>
          <div style={{
            marginTop: "28px",
            border: "1.5px solid rgba(81, 71, 69, 0.16)",
            borderRadius: "22px",
            overflow: "hidden",
            background: "var(--nb1-cool-grey)"
          }}>
            <div style={{
              display: "grid",
              gridTemplateColumns: "1.6fr 0.7fr 0.7fr"
            }} data-keepcols="1" data-cmprow="1">
              <PlansCompareGrid groups={compare} core={core} advanced={advanced} cta={compareCta} />
            </div>
          </div>
        </div>
        <div style={{
          display: "grid",
          gridTemplateColumns: "repeat(3, 1fr)",
          gap: "20px",
          marginTop: "26px"
        }}>
          {(assurances || []).map((ass, assIdx) => (
            <div key={assIdx} style={{
              display: "flex",
              gap: "14px",
              alignItems: "flex-start",
              padding: "22px 0px 0px",
              borderTop: "1px solid var(--nb1-hairline,rgba(81,71,69,.18))"
            }}>
              <span style={{
                width: "30px",
                height: "30px",
                flex: "0 0 auto",
                borderRadius: "50%",
                background: "radial-gradient(circle closest-side,var(--nb1-cool-grey) 0% 52%,var(--nb1-blue-grey) 52% 100%)",
                display: "grid",
                placeItems: "center",
                fontSize: "13px"
              }}>{ass.glyph}</span>
              <div>
                <h4 style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontWeight: "350",
                  fontSize: "15px"
                }}>{ass.title}</h4>
                <p style={{
                  fontSize: "13px",
                  opacity: "0.72",
                  marginTop: "4px",
                  lineHeight: "1.4"
                }}>{ass.body}</p>
              </div>
            </div>
          ))}
        </div>
      </section>
  )
}

// RenderBlocks.client.tsx imports every block as `<Name>Component`; the alias
// keeps that one import name stable whatever the component itself is called.
export const RdPgPlansComponent = RdPgPlans

export default RdPgPlans
