'use client'

import React from 'react'
import type { RdSbBlock as Props } from '@/payload-types'
import type { AppLocale } from '@/i18n/config'

// GENERATED from manifests/section-26.json + bindings/RdSb.json by
// tools/block_component.py — do not hand-edit; regenerate.
//
// Styles copied verbatim from the mockup; bindings replace content only.
// Layout and breakpoints come from rd-sb.css — this page's stylesheet,
// ported by port_css.py and rescoped from `.rd-block` to `.rd-sb` so it
// cannot reach any other page's blocks. That scope is why this root carries
// `rd-sb` and NOT `rd-block`.
//
// The Science Board page, one block — the five screens the mockup draws.


const mediaUrl = (m: unknown): string | undefined =>
  m && typeof m === 'object' && 'url' in m ? ((m as { url?: string }).url ?? undefined) : undefined

const mediaAlt = (m: unknown): string =>
  m && typeof m === 'object' && 'alt' in m ? ((m as { alt?: string }).alt ?? '') : ''

/* GENERATED into the block by --include — the two helpers its sections share.
 *
 * MODULE SCOPE, not a component body, and that is the whole point. The five
 * screens are five components in one module after tools/sb_assemble.py runs,
 * and a `const` declared inside RdSb's body is not in scope in RdSbClose's.
 * The first version put both helpers in --body and tsc said
 * `Cannot find name 'locale'` three times — the right error for the wrong
 * reason: the real fault was the scope, and the missing prop was a symptom.
 */

/** The credential chips under a person, one per line.
 *
 * `tags` is a TEXTAREA, not a nested array. An array would have produced
 * `_pages_v_blocks_rd_sb_board_people_chips_locales_locale_parent_id` — 65
 * bytes, past the 63 Postgres truncates at silently — and it buys an editor
 * nothing over three lines of text. Blank lines are dropped so a trailing
 * newline does not render an empty pill. */
const sbLines = (s?: string | null) =>
  (s || '').split('\n').map((l) => l.trim()).filter(Boolean)

/** A destination. The field holds a SLUG and the locale is added here, so one
 * stored value is right in all nine — the same helper the FAQ and contact
 * blocks carry. Anything already absolute (a url, mailto, tel, #anchor, or a
 * /path) passes through, because an editor who typed one meant it.
 *
 * `locale` is an ARGUMENT rather than a closure, because this is module scope
 * and the component that calls it is not the one that receives the prop. */
const sbPath = (s?: string | null, locale?: string | null) => {
  const v = (s || '').trim()
  if (!v) return '#'
  if (/^(?:[a-z][a-z0-9+.-]*:|\/\/|\/|#)/i.test(v)) return v
  return `/${locale || 'en'}/${v}`
}

/* GENERATED by tools/sb_assemble.py — do not hand-edit.
 *
 * The Science Board's four screens below the hero, lifted out of their own
 * generated files so RdSb can include them, plus the one wrapper that mounts
 * them in order.
 *
 * Each takes the field GROUP it reads, not the whole block — `Props['leads']`
 * rather than a `RdSbLeadsBlock` that does not exist. There is one block here;
 * these are its sections.
 */


const RdSbLeads: React.FC<{ leads?: Props['leads'] | null }> = ({ leads }) => {
  return (
    <section style={{
      background: "var(--nb1-cool-grey)"
    }} className="rd-sb-leads" id="leads" data-screen-label="Who leads">
      <div style={{
        maxWidth: "1240px",
        margin: "0px auto",
        padding: "64px 20px"
      }} data-d="pad bigpad">
        <h2 style={{
          fontFamily: "var(--nb1-font-primary)",
          fontWeight: "400",
          fontSize: "clamp(30px, 5cqi, 50px)",
          lineHeight: "1",
          letterSpacing: "-0.025em"
        }}>{leads?.heading}</h2>
        <p style={{
          fontFamily: "var(--nb1-font-secondary)",
          fontSize: "17px",
          lineHeight: "1.6",
          color: "rgba(81, 71, 69, 0.86)",
          marginTop: "18px",
          maxWidth: "56ch",
          textWrap: "pretty"
        }}>{leads?.intro}</p>
        <div style={{
          display: "flex",
          flexDirection: "column",
          marginTop: "44px"
        }}>
          {(leads?.people || []).map((p, pi) => (
            <div key={pi} style={{
              display: "grid",
              gridTemplateColumns: "1fr",
              gap: "28px",
              alignItems: "center",
              padding: "40px 0px",
              borderTop: "1px solid var(--nb1-hairline)"
            }} data-d="side">
              <div style={{
                position: "relative",
                width: "100%",
                maxWidth: "380px",
                aspectRatio: "4 / 5",
                borderRadius: "20px",
                overflow: "hidden",
                background: "rgb(255, 255, 255)",
                boxShadow: "rgba(81, 71, 69, 0.08) 0px 1px 2px, rgba(81, 71, 69, 0.45) 0px 34px 66px -38px"
              }}>
                <img style={{
                  position: "absolute",
                  inset: "0px",
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                  objectPosition: "center 18%"
                }} src={mediaUrl(p.photo)} alt={mediaAlt(p.photo) || p.name || ''} />
              </div>
              <div style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "flex-start"
              }}>
                <span style={{
                  fontFamily: "var(--nb1-font-tertiary)",
                  textTransform: "uppercase",
                  letterSpacing: "0.1em",
                  fontSize: "12px",
                  padding: "0.6em 1em",
                  borderRadius: "999px",
                  background: "var(--nb1-dark-brown)",
                  color: "var(--nb1-cool-grey)"
                }}>{p.role}</span>
                <h3 style={{
                  fontFamily: "var(--nb1-font-primary)",
                  fontWeight: "400",
                  fontSize: "clamp(26px, 3.4cqi, 37px)",
                  lineHeight: "1.04",
                  letterSpacing: "-0.01em",
                  marginTop: "16px"
                }}>{p.name}</h3>
                <p style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "15.5px",
                  lineHeight: "1.5",
                  color: "rgba(81, 71, 69, 0.8)",
                  marginTop: "10px",
                  maxWidth: "46ch"
                }}>{p.credential}</p>
                <p style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "16.5px",
                  lineHeight: "1.65",
                  marginTop: "16px",
                  maxWidth: "52ch",
                  textWrap: "pretty"
                }}>{p.bio}</p>
                <div style={{
                  display: "flex",
                  flexWrap: "wrap",
                  gap: "8px",
                  marginTop: "20px"
                }}>
                  {(sbLines(p.tags) || []).map((tg, tgi) => (
                    <span key={tgi} style={{
                      fontFamily: "var(--nb1-font-secondary)",
                      fontSize: "13.5px",
                      padding: "0.5em 0.95em",
                      borderRadius: "999px",
                      boxShadow: "rgba(81, 71, 69, 0.22) 0px 0px 0px 1px inset"
                    }}>{tg}</span>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

const RdSbBoard: React.FC<{ board?: Props['board'] | null }> = ({ board }) => {
  return (
    <section style={{
      background: "var(--tint)",
      borderTop: "1px solid rgba(81, 71, 69, 0.16)",
      borderBottom: "1px solid rgba(81, 71, 69, 0.16)"
    }} className="rd-sb-board" id="board" data-screen-label="Board">
      <div style={{
        maxWidth: "1240px",
        margin: "0px auto",
        padding: "64px 20px"
      }} data-d="pad bigpad">
        <h2 style={{
          fontFamily: "var(--nb1-font-primary)",
          fontWeight: "400",
          fontSize: "clamp(30px, 5cqi, 50px)",
          lineHeight: "1",
          letterSpacing: "-0.025em",
          maxWidth: "24ch"
        }}>{board?.heading}</h2>
        <p style={{
          fontFamily: "var(--nb1-font-secondary)",
          fontSize: "17px",
          lineHeight: "1.6",
          color: "rgba(81, 71, 69, 0.86)",
          marginTop: "18px",
          maxWidth: "56ch",
          textWrap: "pretty"
        }}>{board?.intro}</p>
        <div style={{
          display: "flex",
          flexDirection: "column",
          marginTop: "44px"
        }}>
          {(board?.people || []).map((p, pi) => (
            <div key={pi} style={{
              display: "grid",
              gridTemplateColumns: "1fr",
              gap: "28px",
              alignItems: "center",
              padding: "40px 0px",
              borderTop: "1px solid var(--nb1-hairline)"
            }} data-d="side">
              <div style={{
                position: "relative",
                width: "100%",
                maxWidth: "380px",
                aspectRatio: "4 / 5",
                borderRadius: "20px",
                overflow: "hidden",
                background: "var(--nb1-warm-grey)",
                boxShadow: "rgba(81, 71, 69, 0.55) 0px 34px 66px -38px"
              }}>
                <img style={{
                  position: "absolute",
                  inset: "0px",
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                  objectPosition: "center 18%"
                }} src={mediaUrl(p.photo)} alt={mediaAlt(p.photo) || p.name || ''} />
              </div>
              <div style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "flex-start"
              }}>
                <span style={{
                  fontFamily: "var(--nb1-font-tertiary)",
                  textTransform: "uppercase",
                  letterSpacing: "0.1em",
                  fontSize: "12px",
                  padding: "0.6em 1em",
                  borderRadius: "999px",
                  background: "var(--nb1-dark-brown)",
                  color: "var(--nb1-cool-grey)"
                }}>{p.role}</span>
                <h3 style={{
                  fontFamily: "var(--nb1-font-primary)",
                  fontWeight: "400",
                  fontSize: "clamp(26px, 3.4cqi, 37px)",
                  lineHeight: "1.04",
                  letterSpacing: "-0.01em",
                  marginTop: "16px"
                }}>{p.name}</h3>
                <p style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "15.5px",
                  lineHeight: "1.5",
                  color: "rgba(81, 71, 69, 0.8)",
                  marginTop: "10px",
                  maxWidth: "46ch"
                }}>{p.credential}</p>
                <p style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "16.5px",
                  lineHeight: "1.65",
                  marginTop: "16px",
                  maxWidth: "52ch",
                  textWrap: "pretty"
                }}>{p.bio}</p>
                <div style={{
                  display: "flex",
                  flexWrap: "wrap",
                  gap: "8px",
                  marginTop: "20px"
                }}>
                  {(sbLines(p.tags) || []).map((tg, tgi) => (
                    <span key={tgi} style={{
                      fontFamily: "var(--nb1-font-secondary)",
                      fontSize: "13.5px",
                      padding: "0.5em 0.95em",
                      borderRadius: "999px",
                      boxShadow: "rgba(81, 71, 69, 0.22) 0px 0px 0px 1px inset"
                    }}>{tg}</span>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

const RdSbTeam: React.FC<{ team?: Props['team'] | null }> = ({ team }) => {
  return (
    <section style={{
      background: "var(--nb1-cool-grey)"
    }} className="rd-sb-team" id="team" data-screen-label="Team">
      <div style={{
        maxWidth: "1240px",
        margin: "0px auto",
        padding: "64px 20px"
      }} data-d="pad bigpad">
        <h2 style={{
          fontFamily: "var(--nb1-font-primary)",
          fontWeight: "400",
          fontSize: "clamp(30px, 5cqi, 50px)",
          lineHeight: "1",
          letterSpacing: "-0.025em"
        }}>{team?.heading}</h2>
        <p style={{
          fontFamily: "var(--nb1-font-secondary)",
          fontSize: "17px",
          lineHeight: "1.6",
          color: "rgba(81, 71, 69, 0.86)",
          marginTop: "18px",
          maxWidth: "56ch",
          textWrap: "pretty"
        }}>{team?.intro}</p>
        <div style={{
          display: "flex",
          flexDirection: "column",
          marginTop: "44px"
        }}>
          {(team?.people || []).map((p, pi) => (
            <div key={pi} style={{
              display: "grid",
              gridTemplateColumns: "1fr",
              gap: "28px",
              alignItems: "center",
              padding: "40px 0px",
              borderTop: "1px solid var(--nb1-hairline)"
            }} data-d="side">
              <div style={{
                position: "relative",
                width: "100%",
                maxWidth: "380px",
                aspectRatio: "4 / 5",
                borderRadius: "20px",
                overflow: "hidden",
                background: "var(--nb1-warm-grey)",
                boxShadow: "rgba(81, 71, 69, 0.55) 0px 34px 66px -38px"
              }}>
                <img style={{
                  position: "absolute",
                  inset: "0px",
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                  objectPosition: "center 18%"
                }} src={mediaUrl(p.photo)} alt={mediaAlt(p.photo) || p.name || ''} />
              </div>
              <div style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "flex-start"
              }}>
                <span style={{
                  fontFamily: "var(--nb1-font-tertiary)",
                  textTransform: "uppercase",
                  letterSpacing: "0.1em",
                  fontSize: "12px",
                  padding: "0.6em 1em",
                  borderRadius: "999px",
                  background: "var(--nb1-dark-brown)",
                  color: "var(--nb1-cool-grey)"
                }}>{p.role}</span>
                <h3 style={{
                  fontFamily: "var(--nb1-font-primary)",
                  fontWeight: "400",
                  fontSize: "clamp(26px, 3.4cqi, 37px)",
                  lineHeight: "1.04",
                  letterSpacing: "-0.01em",
                  marginTop: "16px"
                }}>{p.name}</h3>
                <p style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "15.5px",
                  lineHeight: "1.5",
                  color: "rgba(81, 71, 69, 0.8)",
                  marginTop: "10px",
                  maxWidth: "46ch"
                }}>{p.credential}</p>
                <p style={{
                  fontFamily: "var(--nb1-font-secondary)",
                  fontSize: "16.5px",
                  lineHeight: "1.65",
                  marginTop: "16px",
                  maxWidth: "52ch",
                  textWrap: "pretty"
                }}>{p.bio}</p>
                <div style={{
                  display: "flex",
                  flexWrap: "wrap",
                  gap: "8px",
                  marginTop: "20px"
                }}>
                  {(sbLines(p.tags) || []).map((tg, tgi) => (
                    <span key={tgi} style={{
                      fontFamily: "var(--nb1-font-secondary)",
                      fontSize: "13.5px",
                      padding: "0.5em 0.95em",
                      borderRadius: "999px",
                      boxShadow: "rgba(81, 71, 69, 0.22) 0px 0px 0px 1px inset"
                    }}>{tg}</span>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

const RdSbClose: React.FC<{ close?: Props['close'] | null, locale?: AppLocale }> = ({ close, locale }) => {
  return (
    <section style={{
      background: "var(--nb1-dark-brown)",
      color: "var(--nb1-cool-grey)"
    }} className="rd-sb-close" id="close" data-screen-label="Close">
      <div style={{
        maxWidth: "1000px",
        margin: "0px auto",
        padding: "72px 20px",
        textAlign: "center",
        display: "flex",
        flexDirection: "column",
        alignItems: "center"
      }} data-d="pad bigpad">
        <h2 style={{
          fontFamily: "var(--nb1-font-primary)",
          fontWeight: "400",
          fontSize: "clamp(30px, 5cqi, 50px)",
          lineHeight: "1",
          letterSpacing: "-0.025em",
          color: "var(--nb1-cool-grey)",
          maxWidth: "20ch"
        }}>{close?.heading}</h2>
        <p style={{
          fontFamily: "var(--nb1-font-secondary)",
          fontSize: "17px",
          lineHeight: "1.6",
          color: "rgba(240, 245, 255, 0.86)",
          marginTop: "18px",
          maxWidth: "56ch",
          textWrap: "pretty",
          marginLeft: "auto",
          marginRight: "auto"
        }}>{close?.body}</p>
        <a style={{
          display: "inline-flex",
          alignItems: "center",
          gap: "1.1em",
          borderRadius: "999px",
          background: "var(--nb1-lime)",
          color: "var(--nb1-black)",
          fontFamily: "var(--nb1-font-tertiary)",
          textTransform: "uppercase",
          letterSpacing: "0.08em",
          fontSize: "14px",
          padding: "1.1em 1.7em",
          whiteSpace: "nowrap",
          flexShrink: "0",
          marginTop: "32px"
        }} href={sbPath(close?.ctaHref, locale)}>
          <span>{close?.ctaLabel}</span>
          <span style={{
            fontSize: "1.05em",
            lineHeight: "1"
          }}>{"\u2197"}</span>
        </a>
      </div>
    </section>
  )
}


/** The four screens below the hero, in document order.
 *
 * RdSb mounts this once through `append.outside`, which takes a single
 * component — so this is where "five screens, one block" is actually spelled
 * out. Adding a sixth screen means adding it here and nowhere else.
 *
 * `locale` is threaded through because the close CTA resolves a slug against
 * it; the three people screens ignore it.
 */
const RdSbRest: React.FC<{
  leads?: Props['leads'] | null
  board?: Props['board'] | null
  team?: Props['team'] | null
  close?: Props['close'] | null
  locale?: AppLocale
}> = ({ leads, board, team, close, locale }) => (
  <>
    <RdSbLeads leads={leads} />
    <RdSbBoard board={board} />
    <RdSbTeam team={team} />
    <RdSbClose close={close} locale={locale} />
  </>
)

export const RdSb: React.FC<Props & { locale?: AppLocale }> = ({ anchorId, board, close, hero, leads, locale, team }) => {
  return (
    <>
      <section style={{
        background: "var(--tint)",
        borderBottom: "1px solid rgba(81, 71, 69, 0.16)"
      }} className="rd-sb" id={anchorId || 'top'} data-screen-label="Hero">
        <div style={{
          maxWidth: "1240px",
          margin: "0px auto",
          padding: "96px 20px 64px"
        }} data-d="pad">
          <h1 style={{
            fontFamily: "var(--nb1-font-primary)",
            fontWeight: "400",
            fontSize: "clamp(38px, 8cqi, 60px)",
            lineHeight: "1.02",
            letterSpacing: "-0.035em",
            maxWidth: "17ch",
            textWrap: "balance"
          }} data-d="bigh">{hero?.heading}</h1>
          <p style={{
            fontFamily: "var(--nb1-font-secondary)",
            fontSize: "clamp(17px, 2.2cqi, 20px)",
            lineHeight: "1.6",
            color: "rgba(81, 71, 69, 0.86)",
            marginTop: "24px",
            maxWidth: "56ch",
            textWrap: "pretty"
          }}>{hero?.intro}</p>
          <div style={{
            display: "grid",
            gridTemplateColumns: "repeat(4, 1fr)",
            gap: "14px",
            marginTop: "40px",
            maxWidth: "820px"
          }} data-m="abgrid">
            {(hero?.stats || []).map((s, si) => (
              <div key={si} style={{
                background: "rgb(255, 255, 255)",
                borderRadius: "16px",
                padding: "20px 22px",
                boxShadow: "inset 0 0 0 1px var(--nb1-hairline)"
              }}>
                <div style={{
                  fontFamily: "var(--nb1-font-primary)",
                  fontSize: "clamp(26px, 3.4cqi, 36px)",
                  lineHeight: "1",
                  letterSpacing: "-0.02em"
                }}>{s.value}</div>
                <div style={{
                  fontFamily: "var(--nb1-font-tertiary)",
                  textTransform: "uppercase",
                  letterSpacing: "0.1em",
                  fontSize: "12px",
                  color: "rgba(81, 71, 69, 0.8)",
                  marginTop: "10px"
                }}>{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>
      <RdSbRest leads={leads} board={board} team={team} close={close} locale={locale} />
    </>
  )
}

// RenderBlocks.client.tsx imports every block as `<Name>Component`; the alias
// keeps that one import name stable whatever the component itself is called.
export const RdSbComponent = RdSb

export default RdSb
