import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Add the `rdPgAthletes` block.
 *
 * GENERATED by tools/migrate_gen.py from the block's field schema — NOT by
 * `payload migrate:create`, whose snapshot in this repo is stale and emits DDL
 * for ~171 unrelated tables.
 *
 * Every statement is idempotent (IF NOT EXISTS / duplicate_object guards), so
 * it is safe to re-run over a partially applied attempt.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pg_athletes_athletes" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"photo_id" integer
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pg_athletes_athletes_locales" (
  	"quote" varchar,
  	"attribution" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pg_athletes" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pg_athletes_locales" (
  	"heading" jsonb,
  	"intro" varchar,
  	"record_label" varchar,
  	"record_value" varchar,
  	"record_place" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pg_athletes_athletes" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"photo_id" integer,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pg_athletes_athletes_locales" (
  	"quote" varchar,
  	"attribution" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pg_athletes" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pg_athletes_locales" (
  	"heading" jsonb,
  	"intro" varchar,
  	"record_label" varchar,
  	"record_value" varchar,
  	"record_place" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pg_athletes_athletes" ADD CONSTRAINT "pages_blocks_rd_pg_athletes_athletes_photo_id_media_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pg_athletes_athletes" ADD CONSTRAINT "pages_blocks_rd_pg_athletes_athletes_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pg_athletes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pg_athletes_athletes_locales" ADD CONSTRAINT "pages_blocks_rd_pg_athletes_athletes_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pg_athletes_athletes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pg_athletes" ADD CONSTRAINT "pages_blocks_rd_pg_athletes_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pg_athletes_locales" ADD CONSTRAINT "pages_blocks_rd_pg_athletes_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pg_athletes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pg_athletes_athletes" ADD CONSTRAINT "_pages_v_blocks_rd_pg_athletes_athletes_photo_id_media_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pg_athletes_athletes" ADD CONSTRAINT "_pages_v_blocks_rd_pg_athletes_athletes_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pg_athletes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pg_athletes_athletes_locales" ADD CONSTRAINT "_pages_v_blocks_rd_pg_athletes_athletes_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pg_athletes_athletes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pg_athletes" ADD CONSTRAINT "_pages_v_blocks_rd_pg_athletes_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pg_athletes_locales" ADD CONSTRAINT "_pages_v_blocks_rd_pg_athletes_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pg_athletes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pg_athletes_athletes_order_idx" ON "pages_blocks_rd_pg_athletes_athletes" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pg_athletes_athletes_parent_id_idx" ON "pages_blocks_rd_pg_athletes_athletes" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pg_athletes_athletes_photo_idx" ON "pages_blocks_rd_pg_athletes_athletes" USING btree ("photo_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_pg_athletes_athletes_locales_locale_parent_i" ON "pages_blocks_rd_pg_athletes_athletes_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pg_athletes_order_idx" ON "pages_blocks_rd_pg_athletes" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pg_athletes_parent_id_idx" ON "pages_blocks_rd_pg_athletes" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pg_athletes_path_idx" ON "pages_blocks_rd_pg_athletes" USING btree ("_path");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_pg_athletes_locales_locale_parent_id_unique" ON "pages_blocks_rd_pg_athletes_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pg_athletes_athletes_order_idx" ON "_pages_v_blocks_rd_pg_athletes_athletes" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pg_athletes_athletes_parent_id_idx" ON "_pages_v_blocks_rd_pg_athletes_athletes" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pg_athletes_athletes_photo_idx" ON "_pages_v_blocks_rd_pg_athletes_athletes" USING btree ("photo_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pg_athletes_athletes_locales_locale_paren" ON "_pages_v_blocks_rd_pg_athletes_athletes_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pg_athletes_order_idx" ON "_pages_v_blocks_rd_pg_athletes" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pg_athletes_parent_id_idx" ON "_pages_v_blocks_rd_pg_athletes" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pg_athletes_path_idx" ON "_pages_v_blocks_rd_pg_athletes" USING btree ("_path");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pg_athletes_locales_locale_parent_id_uniq" ON "_pages_v_blocks_rd_pg_athletes_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pg_athletes_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pg_athletes" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pg_athletes_athletes_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pg_athletes_athletes" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pg_athletes_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pg_athletes" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pg_athletes_athletes_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pg_athletes_athletes" CASCADE;`)
}

