import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Add the `rdProtocol` block.
 *
 * GENERATED by tools/migrate_gen.py from the block's field schema, verified
 * against Payload's own resync snapshot for the rdHero block (same tables, same
 * columns and types, same FK and index counts).
 *
 * Generated rather than produced by `migrate:create` because the snapshot
 * baseline was resynced while rdHero was already registered — see
 * 20260922_120000_rd_hero_block.ts for the full story and the ordering rule.
 * Going through migrate_gen keeps the snapshot untouched, so it stays a true
 * description of the database once these run.
 *
 * `callout` is a group and flattens into the parent table as `callout_*`.
 * `steps` is an array with a localized richText child, so it gets its own table
 * plus a `_locales` child keyed on the array row's varchar id.
 *
 * Every statement is idempotent.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_protocol_steps" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_protocol_steps_locales" (
  	"week" jsonb NOT NULL,
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_protocol" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_protocol_locales" (
  	"heading" varchar NOT NULL,
  	"intro" varchar,
  	"callout_label" varchar,
  	"callout_marker" varchar,
  	"callout_body" jsonb,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_protocol_steps" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_protocol_steps_locales" (
  	"week" jsonb NOT NULL,
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_protocol" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_protocol_locales" (
  	"heading" varchar NOT NULL,
  	"intro" varchar,
  	"callout_label" varchar,
  	"callout_marker" varchar,
  	"callout_body" jsonb,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_protocol_steps" ADD CONSTRAINT "pages_blocks_rd_protocol_steps_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_protocol"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_protocol_steps_locales" ADD CONSTRAINT "pages_blocks_rd_protocol_steps_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_protocol_steps"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_protocol" ADD CONSTRAINT "pages_blocks_rd_protocol_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_protocol_locales" ADD CONSTRAINT "pages_blocks_rd_protocol_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_protocol"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_protocol_steps" ADD CONSTRAINT "_pages_v_blocks_rd_protocol_steps_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_protocol"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_protocol_steps_locales" ADD CONSTRAINT "_pages_v_blocks_rd_protocol_steps_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_protocol_steps"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_protocol" ADD CONSTRAINT "_pages_v_blocks_rd_protocol_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_protocol_locales" ADD CONSTRAINT "_pages_v_blocks_rd_protocol_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_protocol"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_protocol_steps_order_idx" ON "pages_blocks_rd_protocol_steps" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_protocol_steps_parent_id_idx" ON "pages_blocks_rd_protocol_steps" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_protocol_steps_locales_locale_parent_id_uniq" ON "pages_blocks_rd_protocol_steps_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_protocol_order_idx" ON "pages_blocks_rd_protocol" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_protocol_parent_id_idx" ON "pages_blocks_rd_protocol" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_protocol_path_idx" ON "pages_blocks_rd_protocol" USING btree ("_path");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_protocol_locales_locale_parent_id_unique" ON "pages_blocks_rd_protocol_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_protocol_steps_order_idx" ON "_pages_v_blocks_rd_protocol_steps" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_protocol_steps_parent_id_idx" ON "_pages_v_blocks_rd_protocol_steps" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_protocol_steps_locales_locale_parent_id_u" ON "_pages_v_blocks_rd_protocol_steps_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_protocol_order_idx" ON "_pages_v_blocks_rd_protocol" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_protocol_parent_id_idx" ON "_pages_v_blocks_rd_protocol" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_protocol_path_idx" ON "_pages_v_blocks_rd_protocol" USING btree ("_path");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_protocol_locales_locale_parent_id_unique" ON "_pages_v_blocks_rd_protocol_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_protocol_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_protocol" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_protocol_steps_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_protocol_steps" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_protocol_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_protocol" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_protocol_steps_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_protocol_steps" CASCADE;`)
}

