import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Alter the `rdBiology` block.
 *
 * GENERATED by tools/migrate_gen.py --alter. The block's create-migration has
 * already run, so a field change needs a NEW migration that alters what exists —
 * regenerating the original file does nothing, because it is recorded as applied.
 *
 * Idempotent: IF EXISTS / IF NOT EXISTS / duplicate_object guards throughout.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  ALTER TABLE "pages_blocks_rd_biology_locales" ADD COLUMN IF NOT EXISTS "modal_eyebrow" varchar;
  ALTER TABLE "pages_blocks_rd_biology_locales" ADD COLUMN IF NOT EXISTS "modal_read_from_label" varchar;
  ALTER TABLE "pages_blocks_rd_biology_locales" ADD COLUMN IF NOT EXISTS "modal_close_label" varchar;
  ALTER TABLE "pages_blocks_rd_biology_bubbles_locales" ADD COLUMN IF NOT EXISTS "reveal_body" varchar;
  ALTER TABLE "pages_blocks_rd_biology_bubbles_locales" ADD COLUMN IF NOT EXISTS "read_from" varchar;
  ALTER TABLE "_pages_v_blocks_rd_biology_locales" ADD COLUMN IF NOT EXISTS "modal_eyebrow" varchar;
  ALTER TABLE "_pages_v_blocks_rd_biology_locales" ADD COLUMN IF NOT EXISTS "modal_read_from_label" varchar;
  ALTER TABLE "_pages_v_blocks_rd_biology_locales" ADD COLUMN IF NOT EXISTS "modal_close_label" varchar;
  ALTER TABLE "_pages_v_blocks_rd_biology_bubbles_locales" ADD COLUMN IF NOT EXISTS "reveal_body" varchar;
  ALTER TABLE "_pages_v_blocks_rd_biology_bubbles_locales" ADD COLUMN IF NOT EXISTS "read_from" varchar;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  ALTER TABLE "pages_blocks_rd_biology_locales" DROP COLUMN IF EXISTS "modal_eyebrow";
  ALTER TABLE "pages_blocks_rd_biology_locales" DROP COLUMN IF EXISTS "modal_read_from_label";
  ALTER TABLE "pages_blocks_rd_biology_locales" DROP COLUMN IF EXISTS "modal_close_label";
  ALTER TABLE "pages_blocks_rd_biology_bubbles_locales" DROP COLUMN IF EXISTS "reveal_body";
  ALTER TABLE "pages_blocks_rd_biology_bubbles_locales" DROP COLUMN IF EXISTS "read_from";
  ALTER TABLE "_pages_v_blocks_rd_biology_locales" DROP COLUMN IF EXISTS "modal_eyebrow";
  ALTER TABLE "_pages_v_blocks_rd_biology_locales" DROP COLUMN IF EXISTS "modal_read_from_label";
  ALTER TABLE "_pages_v_blocks_rd_biology_locales" DROP COLUMN IF EXISTS "modal_close_label";
  ALTER TABLE "_pages_v_blocks_rd_biology_bubbles_locales" DROP COLUMN IF EXISTS "reveal_body";
  ALTER TABLE "_pages_v_blocks_rd_biology_bubbles_locales" DROP COLUMN IF EXISTS "read_from";`)
}

