import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Add the `rdSt` block.
 *
 * GENERATED by tools/migrate_gen.py from the block's field schema — NOT by
 * `payload migrate:create`, whose snapshot in this repo is stale and emits DDL
 * for ~171 unrelated tables.
 *
 * Every statement is idempotent (IF NOT EXISTS / duplicate_object guards), so
 * it is safe to re-run over a partially applied attempt.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_rules_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_rules_items_locales" (
  	"num" varchar,
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_rules_nots" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_rules_nots_locales" (
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_source_cards" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"image_id" integer
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_source_cards_locales" (
  	"image_alt" varchar,
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_factory_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_factory_items_locales" (
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_clean_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_clean_items_locales" (
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_clean_strip" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"image_id" integer
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_clean_strip_locales" (
  	"image_alt" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_board_avatars" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"image_id" integer
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_board_avatars_locales" (
  	"image_alt" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_proof_docs" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"image_id" integer
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_proof_docs_locales" (
  	"image_alt" varchar,
  	"kicker" varchar,
  	"status" varchar,
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"rows" varchar,
  	"foot" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_plans_tiers" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_plans_tiers_locales" (
  	"name" varchar NOT NULL,
  	"badge" varchar,
  	"blurb" varchar,
  	"price" varchar,
  	"price_suffix" varchar,
  	"price_note" varchar,
  	"list_heading" varchar,
  	"features" varchar,
  	"cta_label" varchar,
  	"cta_href" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"factory_image_id" integer,
  	"clean_badge_id" integer,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_st_locales" (
  	"hero_heading" varchar NOT NULL,
  	"hero_intro" varchar,
  	"rules_heading" varchar NOT NULL,
  	"rules_panel_lead" varchar,
  	"rules_panel_em" varchar,
  	"rules_panel_tail" varchar,
  	"rules_panel_body" varchar,
  	"source_heading" varchar NOT NULL,
  	"source_intro" varchar,
  	"factory_heading_lead" varchar NOT NULL,
  	"factory_heading_em" varchar,
  	"factory_intro" varchar,
  	"factory_outro" varchar,
  	"factory_image_alt" varchar,
  	"clean_heading" varchar NOT NULL,
  	"clean_intro" varchar,
  	"clean_badge_alt" varchar,
  	"board_heading" varchar NOT NULL,
  	"board_body" varchar,
  	"board_cta_label" varchar,
  	"board_cta_href" varchar,
  	"board_stat_value" varchar,
  	"board_stat_line_one" varchar,
  	"board_stat_line_two" varchar,
  	"board_note" varchar,
  	"proof_heading" varchar NOT NULL,
  	"proof_intro" varchar,
  	"proof_note" varchar,
  	"plans_heading" varchar NOT NULL,
  	"plans_intro" varchar,
  	"plans_note" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_rules_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_rules_items_locales" (
  	"num" varchar,
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_rules_nots" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_rules_nots_locales" (
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_source_cards" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"image_id" integer,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_source_cards_locales" (
  	"image_alt" varchar,
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_factory_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_factory_items_locales" (
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_clean_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_clean_items_locales" (
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_clean_strip" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"image_id" integer,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_clean_strip_locales" (
  	"image_alt" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_board_avatars" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"image_id" integer,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_board_avatars_locales" (
  	"image_alt" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_proof_docs" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"image_id" integer,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_proof_docs_locales" (
  	"image_alt" varchar,
  	"kicker" varchar,
  	"status" varchar,
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"rows" varchar,
  	"foot" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_plans_tiers" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_plans_tiers_locales" (
  	"name" varchar NOT NULL,
  	"badge" varchar,
  	"blurb" varchar,
  	"price" varchar,
  	"price_suffix" varchar,
  	"price_note" varchar,
  	"list_heading" varchar,
  	"features" varchar,
  	"cta_label" varchar,
  	"cta_href" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"factory_image_id" integer,
  	"clean_badge_id" integer,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_st_locales" (
  	"hero_heading" varchar NOT NULL,
  	"hero_intro" varchar,
  	"rules_heading" varchar NOT NULL,
  	"rules_panel_lead" varchar,
  	"rules_panel_em" varchar,
  	"rules_panel_tail" varchar,
  	"rules_panel_body" varchar,
  	"source_heading" varchar NOT NULL,
  	"source_intro" varchar,
  	"factory_heading_lead" varchar NOT NULL,
  	"factory_heading_em" varchar,
  	"factory_intro" varchar,
  	"factory_outro" varchar,
  	"factory_image_alt" varchar,
  	"clean_heading" varchar NOT NULL,
  	"clean_intro" varchar,
  	"clean_badge_alt" varchar,
  	"board_heading" varchar NOT NULL,
  	"board_body" varchar,
  	"board_cta_label" varchar,
  	"board_cta_href" varchar,
  	"board_stat_value" varchar,
  	"board_stat_line_one" varchar,
  	"board_stat_line_two" varchar,
  	"board_note" varchar,
  	"proof_heading" varchar NOT NULL,
  	"proof_intro" varchar,
  	"proof_note" varchar,
  	"plans_heading" varchar NOT NULL,
  	"plans_intro" varchar,
  	"plans_note" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_rules_items" ADD CONSTRAINT "pages_blocks_rd_st_rules_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_rules_items_locales" ADD CONSTRAINT "pages_blocks_rd_st_rules_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st_rules_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_rules_nots" ADD CONSTRAINT "pages_blocks_rd_st_rules_nots_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_rules_nots_locales" ADD CONSTRAINT "pages_blocks_rd_st_rules_nots_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st_rules_nots"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_source_cards" ADD CONSTRAINT "pages_blocks_rd_st_source_cards_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_source_cards" ADD CONSTRAINT "pages_blocks_rd_st_source_cards_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_source_cards_locales" ADD CONSTRAINT "pages_blocks_rd_st_source_cards_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st_source_cards"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_factory_items" ADD CONSTRAINT "pages_blocks_rd_st_factory_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_factory_items_locales" ADD CONSTRAINT "pages_blocks_rd_st_factory_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st_factory_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_clean_items" ADD CONSTRAINT "pages_blocks_rd_st_clean_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_clean_items_locales" ADD CONSTRAINT "pages_blocks_rd_st_clean_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st_clean_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_clean_strip" ADD CONSTRAINT "pages_blocks_rd_st_clean_strip_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_clean_strip" ADD CONSTRAINT "pages_blocks_rd_st_clean_strip_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_clean_strip_locales" ADD CONSTRAINT "pages_blocks_rd_st_clean_strip_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st_clean_strip"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_board_avatars" ADD CONSTRAINT "pages_blocks_rd_st_board_avatars_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_board_avatars" ADD CONSTRAINT "pages_blocks_rd_st_board_avatars_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_board_avatars_locales" ADD CONSTRAINT "pages_blocks_rd_st_board_avatars_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st_board_avatars"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_proof_docs" ADD CONSTRAINT "pages_blocks_rd_st_proof_docs_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_proof_docs" ADD CONSTRAINT "pages_blocks_rd_st_proof_docs_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_proof_docs_locales" ADD CONSTRAINT "pages_blocks_rd_st_proof_docs_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st_proof_docs"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_plans_tiers" ADD CONSTRAINT "pages_blocks_rd_st_plans_tiers_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_plans_tiers_locales" ADD CONSTRAINT "pages_blocks_rd_st_plans_tiers_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st_plans_tiers"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st" ADD CONSTRAINT "pages_blocks_rd_st_factory_image_id_media_id_fk" FOREIGN KEY ("factory_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st" ADD CONSTRAINT "pages_blocks_rd_st_clean_badge_id_media_id_fk" FOREIGN KEY ("clean_badge_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st" ADD CONSTRAINT "pages_blocks_rd_st_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_st_locales" ADD CONSTRAINT "pages_blocks_rd_st_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_rules_items" ADD CONSTRAINT "_pages_v_blocks_rd_st_rules_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_rules_items_locales" ADD CONSTRAINT "_pages_v_blocks_rd_st_rules_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st_rules_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_rules_nots" ADD CONSTRAINT "_pages_v_blocks_rd_st_rules_nots_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_rules_nots_locales" ADD CONSTRAINT "_pages_v_blocks_rd_st_rules_nots_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st_rules_nots"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_source_cards" ADD CONSTRAINT "_pages_v_blocks_rd_st_source_cards_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_source_cards" ADD CONSTRAINT "_pages_v_blocks_rd_st_source_cards_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_source_cards_locales" ADD CONSTRAINT "_pages_v_blocks_rd_st_source_cards_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st_source_cards"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_factory_items" ADD CONSTRAINT "_pages_v_blocks_rd_st_factory_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_factory_items_locales" ADD CONSTRAINT "_pages_v_blocks_rd_st_factory_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st_factory_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_clean_items" ADD CONSTRAINT "_pages_v_blocks_rd_st_clean_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_clean_items_locales" ADD CONSTRAINT "_pages_v_blocks_rd_st_clean_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st_clean_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_clean_strip" ADD CONSTRAINT "_pages_v_blocks_rd_st_clean_strip_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_clean_strip" ADD CONSTRAINT "_pages_v_blocks_rd_st_clean_strip_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_clean_strip_locales" ADD CONSTRAINT "_pages_v_blocks_rd_st_clean_strip_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st_clean_strip"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_board_avatars" ADD CONSTRAINT "_pages_v_blocks_rd_st_board_avatars_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_board_avatars" ADD CONSTRAINT "_pages_v_blocks_rd_st_board_avatars_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_board_avatars_locales" ADD CONSTRAINT "_pages_v_blocks_rd_st_board_avatars_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st_board_avatars"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_proof_docs" ADD CONSTRAINT "_pages_v_blocks_rd_st_proof_docs_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_proof_docs" ADD CONSTRAINT "_pages_v_blocks_rd_st_proof_docs_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_proof_docs_locales" ADD CONSTRAINT "_pages_v_blocks_rd_st_proof_docs_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st_proof_docs"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_plans_tiers" ADD CONSTRAINT "_pages_v_blocks_rd_st_plans_tiers_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_plans_tiers_locales" ADD CONSTRAINT "_pages_v_blocks_rd_st_plans_tiers_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st_plans_tiers"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st" ADD CONSTRAINT "_pages_v_blocks_rd_st_factory_image_id_media_id_fk" FOREIGN KEY ("factory_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st" ADD CONSTRAINT "_pages_v_blocks_rd_st_clean_badge_id_media_id_fk" FOREIGN KEY ("clean_badge_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st" ADD CONSTRAINT "_pages_v_blocks_rd_st_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_st_locales" ADD CONSTRAINT "_pages_v_blocks_rd_st_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_st"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_rules_items_order_idx" ON "pages_blocks_rd_st_rules_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_rules_items_parent_id_idx" ON "pages_blocks_rd_st_rules_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_st_rules_items_locales_locale_parent_id_uniq" ON "pages_blocks_rd_st_rules_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_rules_nots_order_idx" ON "pages_blocks_rd_st_rules_nots" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_rules_nots_parent_id_idx" ON "pages_blocks_rd_st_rules_nots" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_st_rules_nots_locales_locale_parent_id_uniqu" ON "pages_blocks_rd_st_rules_nots_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_source_cards_order_idx" ON "pages_blocks_rd_st_source_cards" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_source_cards_parent_id_idx" ON "pages_blocks_rd_st_source_cards" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_source_cards_image_idx" ON "pages_blocks_rd_st_source_cards" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_st_source_cards_locales_locale_parent_id_uni" ON "pages_blocks_rd_st_source_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_factory_items_order_idx" ON "pages_blocks_rd_st_factory_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_factory_items_parent_id_idx" ON "pages_blocks_rd_st_factory_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_st_factory_items_locales_locale_parent_id_un" ON "pages_blocks_rd_st_factory_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_clean_items_order_idx" ON "pages_blocks_rd_st_clean_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_clean_items_parent_id_idx" ON "pages_blocks_rd_st_clean_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_st_clean_items_locales_locale_parent_id_uniq" ON "pages_blocks_rd_st_clean_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_clean_strip_order_idx" ON "pages_blocks_rd_st_clean_strip" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_clean_strip_parent_id_idx" ON "pages_blocks_rd_st_clean_strip" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_clean_strip_image_idx" ON "pages_blocks_rd_st_clean_strip" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_st_clean_strip_locales_locale_parent_id_uniq" ON "pages_blocks_rd_st_clean_strip_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_board_avatars_order_idx" ON "pages_blocks_rd_st_board_avatars" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_board_avatars_parent_id_idx" ON "pages_blocks_rd_st_board_avatars" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_board_avatars_image_idx" ON "pages_blocks_rd_st_board_avatars" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_st_board_avatars_locales_locale_parent_id_un" ON "pages_blocks_rd_st_board_avatars_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_proof_docs_order_idx" ON "pages_blocks_rd_st_proof_docs" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_proof_docs_parent_id_idx" ON "pages_blocks_rd_st_proof_docs" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_proof_docs_image_idx" ON "pages_blocks_rd_st_proof_docs" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_st_proof_docs_locales_locale_parent_id_uniqu" ON "pages_blocks_rd_st_proof_docs_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_plans_tiers_order_idx" ON "pages_blocks_rd_st_plans_tiers" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_plans_tiers_parent_id_idx" ON "pages_blocks_rd_st_plans_tiers" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_st_plans_tiers_locales_locale_parent_id_uniq" ON "pages_blocks_rd_st_plans_tiers_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_order_idx" ON "pages_blocks_rd_st" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_parent_id_idx" ON "pages_blocks_rd_st" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_path_idx" ON "pages_blocks_rd_st" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_factory_image_idx" ON "pages_blocks_rd_st" USING btree ("factory_image_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_st_clean_badge_idx" ON "pages_blocks_rd_st" USING btree ("clean_badge_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_st_locales_locale_parent_id_unique" ON "pages_blocks_rd_st_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_rules_items_order_idx" ON "_pages_v_blocks_rd_st_rules_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_rules_items_parent_id_idx" ON "_pages_v_blocks_rd_st_rules_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_rules_items_locales_locale_parent_id_u" ON "_pages_v_blocks_rd_st_rules_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_rules_nots_order_idx" ON "_pages_v_blocks_rd_st_rules_nots" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_rules_nots_parent_id_idx" ON "_pages_v_blocks_rd_st_rules_nots" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_rules_nots_locales_locale_parent_id_un" ON "_pages_v_blocks_rd_st_rules_nots_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_source_cards_order_idx" ON "_pages_v_blocks_rd_st_source_cards" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_source_cards_parent_id_idx" ON "_pages_v_blocks_rd_st_source_cards" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_source_cards_image_idx" ON "_pages_v_blocks_rd_st_source_cards" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_source_cards_locales_locale_parent_id_" ON "_pages_v_blocks_rd_st_source_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_factory_items_order_idx" ON "_pages_v_blocks_rd_st_factory_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_factory_items_parent_id_idx" ON "_pages_v_blocks_rd_st_factory_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_factory_items_locales_locale_parent_id" ON "_pages_v_blocks_rd_st_factory_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_clean_items_order_idx" ON "_pages_v_blocks_rd_st_clean_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_clean_items_parent_id_idx" ON "_pages_v_blocks_rd_st_clean_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_clean_items_locales_locale_parent_id_u" ON "_pages_v_blocks_rd_st_clean_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_clean_strip_order_idx" ON "_pages_v_blocks_rd_st_clean_strip" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_clean_strip_parent_id_idx" ON "_pages_v_blocks_rd_st_clean_strip" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_clean_strip_image_idx" ON "_pages_v_blocks_rd_st_clean_strip" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_clean_strip_locales_locale_parent_id_u" ON "_pages_v_blocks_rd_st_clean_strip_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_board_avatars_order_idx" ON "_pages_v_blocks_rd_st_board_avatars" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_board_avatars_parent_id_idx" ON "_pages_v_blocks_rd_st_board_avatars" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_board_avatars_image_idx" ON "_pages_v_blocks_rd_st_board_avatars" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_board_avatars_locales_locale_parent_id" ON "_pages_v_blocks_rd_st_board_avatars_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_proof_docs_order_idx" ON "_pages_v_blocks_rd_st_proof_docs" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_proof_docs_parent_id_idx" ON "_pages_v_blocks_rd_st_proof_docs" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_proof_docs_image_idx" ON "_pages_v_blocks_rd_st_proof_docs" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_proof_docs_locales_locale_parent_id_un" ON "_pages_v_blocks_rd_st_proof_docs_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_plans_tiers_order_idx" ON "_pages_v_blocks_rd_st_plans_tiers" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_plans_tiers_parent_id_idx" ON "_pages_v_blocks_rd_st_plans_tiers" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_plans_tiers_locales_locale_parent_id_u" ON "_pages_v_blocks_rd_st_plans_tiers_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_order_idx" ON "_pages_v_blocks_rd_st" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_parent_id_idx" ON "_pages_v_blocks_rd_st" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_path_idx" ON "_pages_v_blocks_rd_st" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_factory_image_idx" ON "_pages_v_blocks_rd_st" USING btree ("factory_image_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_clean_badge_idx" ON "_pages_v_blocks_rd_st" USING btree ("clean_badge_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_st_locales_locale_parent_id_unique" ON "_pages_v_blocks_rd_st_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_plans_tiers_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_plans_tiers" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_proof_docs_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_proof_docs" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_board_avatars_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_board_avatars" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_clean_strip_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_clean_strip" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_clean_items_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_clean_items" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_factory_items_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_factory_items" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_source_cards_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_source_cards" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_rules_nots_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_rules_nots" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_rules_items_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_st_rules_items" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_plans_tiers_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_plans_tiers" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_proof_docs_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_proof_docs" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_board_avatars_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_board_avatars" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_clean_strip_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_clean_strip" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_clean_items_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_clean_items" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_factory_items_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_factory_items" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_source_cards_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_source_cards" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_rules_nots_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_rules_nots" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_rules_items_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_st_rules_items" CASCADE;`)
}
