import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Give `rdPrBloodKit` a real photograph: `image` + `imageAlt`.
 *
 * GENERATED by tools/migrate_gen.py --alter. The block's create-migration has
 * already run, so a field change needs a NEW migration that alters what exists —
 * regenerating the original file does nothing, because it is recorded as applied.
 *
 * WHAT THIS REPLACES. The right column was the mockup's own empty box: a
 * bordered 4:5 panel with `role="img"` and the caption "Blood kit image". That
 * was the right call while the design had no photograph — inventing an <img>
 * the mockup has not got is how a block stops matching its design. It is the
 * wrong call now that one is wanted, so the box gains an image and keeps the
 * placeholder as its FALLBACK: the two placeholder fields stay, and a block
 * with no upload renders exactly what it rendered before this migration.
 *
 * `image` IS NOT LOCALIZED — the standing rule for this redesign; media fields
 * are shared across the nine locales and only the text around them is
 * translated. So its column lands on the BLOCK table with a plain index, not on
 * `_locales` with a composite one. `imageAlt` is localized and lands on
 * `_locales`, like every other string here. (The opposite case — a localized
 * upload — is `20260923_240000_rd_pg_data_report_avatar.ts`, and the two shapes
 * are genuinely different; see its note.)
 *
 * Idempotent: IF EXISTS / IF NOT EXISTS / duplicate_object guards throughout.
 * `down` drops the columns, which takes their foreign keys and indexes with
 * them, and the section falls back to the empty box it has today.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  ALTER TABLE "pages_blocks_rd_pr_blood_kit" ADD COLUMN IF NOT EXISTS "image_id" integer;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_blood_kit" ADD CONSTRAINT "pages_blocks_rd_pr_blood_kit_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_blood_kit_image_idx" ON "pages_blocks_rd_pr_blood_kit" USING btree ("image_id");
  ALTER TABLE "pages_blocks_rd_pr_blood_kit_locales" ADD COLUMN IF NOT EXISTS "image_alt" varchar;
  ALTER TABLE "_pages_v_blocks_rd_pr_blood_kit" ADD COLUMN IF NOT EXISTS "image_id" integer;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_blood_kit" ADD CONSTRAINT "_pages_v_blocks_rd_pr_blood_kit_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_blood_kit_image_idx" ON "_pages_v_blocks_rd_pr_blood_kit" USING btree ("image_id");
  ALTER TABLE "_pages_v_blocks_rd_pr_blood_kit_locales" ADD COLUMN IF NOT EXISTS "image_alt" varchar;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  ALTER TABLE "pages_blocks_rd_pr_blood_kit" DROP COLUMN IF EXISTS "image_id";
  ALTER TABLE "pages_blocks_rd_pr_blood_kit_locales" DROP COLUMN IF EXISTS "image_alt";
  ALTER TABLE "_pages_v_blocks_rd_pr_blood_kit" DROP COLUMN IF EXISTS "image_id";
  ALTER TABLE "_pages_v_blocks_rd_pr_blood_kit_locales" DROP COLUMN IF EXISTS "image_alt";`)
}

