import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Add the `rdLegal` block.
 *
 * GENERATED by tools/migrate_gen.py from the block's field schema — NOT by
 * `payload migrate:create`, whose snapshot in this repo is stale and emits DDL
 * for ~171 unrelated tables.
 *
 * Every statement is idempotent (IF NOT EXISTS / duplicate_object guards), so
 * it is safe to re-run over a partially applied attempt.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_legal_clauses_parts_kind" AS ENUM('item', 'panel', 'grid', 'prose');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_legal_clauses_parts_kind" AS ENUM('item', 'panel', 'grid', 'prose');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_legal_glance_points" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_legal_glance_points_locales" (
  	"body" jsonb NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_legal_clauses_parts_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_legal_clauses_parts_rows_locales" (
  	"label" varchar,
  	"body" jsonb,
  	"c1" varchar,
  	"c2" varchar,
  	"c3" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_legal_clauses_parts" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"kind" "enum_pages_blocks_rd_legal_clauses_parts_kind"
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_legal_clauses_parts_locales" (
  	"number" varchar,
  	"title" varchar,
  	"body" jsonb,
  	"caption" varchar,
  	"cols_c1" varchar,
  	"cols_c2" varchar,
  	"cols_c3" varchar,
  	"after" jsonb,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_legal_clauses" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"anchor_id" varchar NOT NULL,
  	"show_in_toc" boolean
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_legal_clauses_locales" (
  	"number" varchar,
  	"title" varchar NOT NULL,
  	"toc_label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_legal_contact_details" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_legal_contact_details_locales" (
  	"label" varchar NOT NULL,
  	"value" jsonb NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_legal" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"top_anchor_id" varchar,
  	"anchor_id" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_legal_locales" (
  	"top_title" varchar NOT NULL,
  	"top_intro" varchar,
  	"toc_label" varchar,
  	"glance_heading" varchar,
  	"glance_intro" varchar,
  	"contact_heading" varchar,
  	"contact_body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_legal_glance_points" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_legal_glance_points_locales" (
  	"body" jsonb NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses_parts_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses_parts_rows_locales" (
  	"label" varchar,
  	"body" jsonb,
  	"c1" varchar,
  	"c2" varchar,
  	"c3" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses_parts" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"kind" "enum__pages_v_blocks_rd_legal_clauses_parts_kind",
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses_parts_locales" (
  	"number" varchar,
  	"title" varchar,
  	"body" jsonb,
  	"caption" varchar,
  	"cols_c1" varchar,
  	"cols_c2" varchar,
  	"cols_c3" varchar,
  	"after" jsonb,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"anchor_id" varchar NOT NULL,
  	"show_in_toc" boolean,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses_locales" (
  	"number" varchar,
  	"title" varchar NOT NULL,
  	"toc_label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_legal_contact_details" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_legal_contact_details_locales" (
  	"label" varchar NOT NULL,
  	"value" jsonb NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_legal" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"top_anchor_id" varchar,
  	"anchor_id" varchar,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_legal_locales" (
  	"top_title" varchar NOT NULL,
  	"top_intro" varchar,
  	"toc_label" varchar,
  	"glance_heading" varchar,
  	"glance_intro" varchar,
  	"contact_heading" varchar,
  	"contact_body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_legal_glance_points" ADD CONSTRAINT "pages_blocks_rd_legal_glance_points_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_legal"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_legal_glance_points_locales" ADD CONSTRAINT "pages_blocks_rd_legal_glance_points_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_legal_glance_points"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_legal_clauses_parts_rows" ADD CONSTRAINT "pages_blocks_rd_legal_clauses_parts_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_legal_clauses_parts"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_legal_clauses_parts_rows_locales" ADD CONSTRAINT "pages_blocks_rd_legal_clauses_parts_rows_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_legal_clauses_parts_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_legal_clauses_parts" ADD CONSTRAINT "pages_blocks_rd_legal_clauses_parts_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_legal_clauses"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_legal_clauses_parts_locales" ADD CONSTRAINT "pages_blocks_rd_legal_clauses_parts_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_legal_clauses_parts"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_legal_clauses" ADD CONSTRAINT "pages_blocks_rd_legal_clauses_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_legal"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_legal_clauses_locales" ADD CONSTRAINT "pages_blocks_rd_legal_clauses_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_legal_clauses"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_legal_contact_details" ADD CONSTRAINT "pages_blocks_rd_legal_contact_details_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_legal"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_legal_contact_details_locales" ADD CONSTRAINT "pages_blocks_rd_legal_contact_details_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_legal_contact_details"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_legal" ADD CONSTRAINT "pages_blocks_rd_legal_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_legal_locales" ADD CONSTRAINT "pages_blocks_rd_legal_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_legal"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_legal_glance_points" ADD CONSTRAINT "_pages_v_blocks_rd_legal_glance_points_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_legal"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_legal_glance_points_locales" ADD CONSTRAINT "_pages_v_blocks_rd_legal_glance_points_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_legal_glance_points"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_legal_clauses_parts_rows" ADD CONSTRAINT "_pages_v_blocks_rd_legal_clauses_parts_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_legal_clauses_parts"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_legal_clauses_parts_rows_locales" ADD CONSTRAINT "_pages_v_blocks_rd_legal_clauses_parts_rows_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_legal_clauses_parts_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_legal_clauses_parts" ADD CONSTRAINT "_pages_v_blocks_rd_legal_clauses_parts_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_legal_clauses"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_legal_clauses_parts_locales" ADD CONSTRAINT "_pages_v_blocks_rd_legal_clauses_parts_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_legal_clauses_parts"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_legal_clauses" ADD CONSTRAINT "_pages_v_blocks_rd_legal_clauses_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_legal"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_legal_clauses_locales" ADD CONSTRAINT "_pages_v_blocks_rd_legal_clauses_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_legal_clauses"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_legal_contact_details" ADD CONSTRAINT "_pages_v_blocks_rd_legal_contact_details_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_legal"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_legal_contact_details_locales" ADD CONSTRAINT "_pages_v_blocks_rd_legal_contact_details_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_legal_contact_details"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_legal" ADD CONSTRAINT "_pages_v_blocks_rd_legal_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_legal_locales" ADD CONSTRAINT "_pages_v_blocks_rd_legal_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_legal"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_legal_glance_points_order_idx" ON "pages_blocks_rd_legal_glance_points" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_legal_glance_points_parent_id_idx" ON "pages_blocks_rd_legal_glance_points" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_legal_glance_points_locales_locale_parent_id" ON "pages_blocks_rd_legal_glance_points_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_legal_clauses_parts_rows_order_idx" ON "pages_blocks_rd_legal_clauses_parts_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_legal_clauses_parts_rows_parent_id_idx" ON "pages_blocks_rd_legal_clauses_parts_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_legal_clauses_parts_rows_locales_locale_pare" ON "pages_blocks_rd_legal_clauses_parts_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_legal_clauses_parts_order_idx" ON "pages_blocks_rd_legal_clauses_parts" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_legal_clauses_parts_parent_id_idx" ON "pages_blocks_rd_legal_clauses_parts" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_legal_clauses_parts_locales_locale_parent_id" ON "pages_blocks_rd_legal_clauses_parts_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_legal_clauses_order_idx" ON "pages_blocks_rd_legal_clauses" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_legal_clauses_parent_id_idx" ON "pages_blocks_rd_legal_clauses" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_legal_clauses_locales_locale_parent_id_uniqu" ON "pages_blocks_rd_legal_clauses_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_legal_contact_details_order_idx" ON "pages_blocks_rd_legal_contact_details" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_legal_contact_details_parent_id_idx" ON "pages_blocks_rd_legal_contact_details" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_legal_contact_details_locales_locale_parent_" ON "pages_blocks_rd_legal_contact_details_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_legal_order_idx" ON "pages_blocks_rd_legal" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_legal_parent_id_idx" ON "pages_blocks_rd_legal" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_legal_path_idx" ON "pages_blocks_rd_legal" USING btree ("_path");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_legal_locales_locale_parent_id_unique" ON "pages_blocks_rd_legal_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_glance_points_order_idx" ON "_pages_v_blocks_rd_legal_glance_points" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_glance_points_parent_id_idx" ON "_pages_v_blocks_rd_legal_glance_points" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_glance_points_locales_locale_parent" ON "_pages_v_blocks_rd_legal_glance_points_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses_parts_rows_order_idx" ON "_pages_v_blocks_rd_legal_clauses_parts_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses_parts_rows_parent_id_idx" ON "_pages_v_blocks_rd_legal_clauses_parts_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses_parts_rows_locales_locale_p" ON "_pages_v_blocks_rd_legal_clauses_parts_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses_parts_order_idx" ON "_pages_v_blocks_rd_legal_clauses_parts" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses_parts_parent_id_idx" ON "_pages_v_blocks_rd_legal_clauses_parts" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses_parts_locales_locale_parent" ON "_pages_v_blocks_rd_legal_clauses_parts_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses_order_idx" ON "_pages_v_blocks_rd_legal_clauses" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses_parent_id_idx" ON "_pages_v_blocks_rd_legal_clauses" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_clauses_locales_locale_parent_id_un" ON "_pages_v_blocks_rd_legal_clauses_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_contact_details_order_idx" ON "_pages_v_blocks_rd_legal_contact_details" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_contact_details_parent_id_idx" ON "_pages_v_blocks_rd_legal_contact_details" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_contact_details_locales_locale_pare" ON "_pages_v_blocks_rd_legal_contact_details_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_order_idx" ON "_pages_v_blocks_rd_legal" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_parent_id_idx" ON "_pages_v_blocks_rd_legal" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_path_idx" ON "_pages_v_blocks_rd_legal" USING btree ("_path");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_legal_locales_locale_parent_id_unique" ON "_pages_v_blocks_rd_legal_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_legal_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_legal" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_legal_contact_details_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_legal_contact_details" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_legal_clauses_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_legal_clauses" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_legal_clauses_parts_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_legal_clauses_parts" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_legal_clauses_parts_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_legal_clauses_parts_rows" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_legal_glance_points_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_legal_glance_points" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_legal_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_legal" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_legal_contact_details_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_legal_contact_details" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_legal_clauses_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_legal_clauses" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_legal_clauses_parts_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_legal_clauses_parts" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_legal_clauses_parts_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_legal_clauses_parts_rows" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_legal_glance_points_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_legal_glance_points" CASCADE;
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_legal_clauses_parts_kind";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_legal_clauses_parts_kind";`)
}

