import { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-postgres'
import { sql } from 'drizzle-orm'

export async function up({ db, payload }: MigrateUpArgs): Promise<void> {
  // Check that the headers table exists before trying to seed it.
  // This migration must run AFTER the DDL migration generated by `migrate:create`.
  const result = await db.execute(sql`
    SELECT EXISTS (
      SELECT FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = 'headers'
    ) AS exists
  `)

  const headersTableExists = result.rows[0]?.exists === true

  if (!headersTableExists) {
    payload.logger.warn(
      'headers/footers tables do not exist yet — skipping seed. ' +
        'Run `npx payload migrate:create` to generate the schema migration, then re-run migrate.',
    )
    return
  }

  // Do not use the current Payload Local API in a historical migration. Its
  // query shape includes fields/tables introduced by later migrations, which
  // makes a fresh replay fail before those tables exist.
  await db.execute(sql`
    INSERT INTO "headers" ("name", "is_default", "theme")
    SELECT 'Default', true, 'light'
    WHERE NOT EXISTS (SELECT 1 FROM "headers");
  `)

  const footersTableExists = await db.execute(sql`
    SELECT EXISTS (
      SELECT FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = 'footers'
    ) AS exists
  `)

  if (footersTableExists.rows[0]?.exists !== true) return

  await db.execute(sql`
    INSERT INTO "footers" ("name", "is_default", "theme")
    SELECT 'Default', true, 'light'
    WHERE NOT EXISTS (SELECT 1 FROM "footers");
  `)

  payload.logger.info('Ensured default header and footer documents exist.')
}

export async function down(_args: MigrateDownArgs): Promise<void> {
  // No destructive rollback.
}
