import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Add the `rdProof` block.
 *
 * GENERATED by tools/migrate_gen.py from the block's field schema — NOT by
 * `payload migrate:create`, whose snapshot in this repo is stale and emits DDL
 * for ~171 unrelated tables.
 *
 * Every statement is idempotent (IF NOT EXISTS / duplicate_object guards), so
 * it is safe to re-run over a partially applied attempt.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_proof_cards" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"image_id" integer,
  	"from" numeric NOT NULL,
  	"to" numeric NOT NULL,
  	"scale_max" numeric DEFAULT 10 NOT NULL,
  	"higher_is_better" boolean DEFAULT false,
  	"orb_id" integer
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_proof_cards_locales" (
  	"metric" varchar NOT NULL,
  	"goal" varchar,
  	"scale_suffix" varchar,
  	"scale_low" varchar,
  	"scale_high" varchar,
  	"summary" varchar,
  	"back_label" varchar,
  	"back_body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_proof" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"score_value" numeric DEFAULT 80.2 NOT NULL,
  	"score_prior" numeric DEFAULT 68.3 NOT NULL,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_proof_locales" (
  	"heading" varchar,
  	"intro" jsonb,
  	"score_scale" varchar,
  	"score_delta_unit" varchar,
  	"score_prior_prefix" varchar,
  	"score_caption" varchar,
  	"availability" jsonb,
  	"footnote" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_proof_cards" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"image_id" integer,
  	"from" numeric NOT NULL,
  	"to" numeric NOT NULL,
  	"scale_max" numeric DEFAULT 10 NOT NULL,
  	"higher_is_better" boolean DEFAULT false,
  	"orb_id" integer,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_proof_cards_locales" (
  	"metric" varchar NOT NULL,
  	"goal" varchar,
  	"scale_suffix" varchar,
  	"scale_low" varchar,
  	"scale_high" varchar,
  	"summary" varchar,
  	"back_label" varchar,
  	"back_body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_proof" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"score_value" numeric DEFAULT 80.2 NOT NULL,
  	"score_prior" numeric DEFAULT 68.3 NOT NULL,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_proof_locales" (
  	"heading" varchar,
  	"intro" jsonb,
  	"score_scale" varchar,
  	"score_delta_unit" varchar,
  	"score_prior_prefix" varchar,
  	"score_caption" varchar,
  	"availability" jsonb,
  	"footnote" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_proof_cards" ADD CONSTRAINT "pages_blocks_rd_proof_cards_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_proof_cards" ADD CONSTRAINT "pages_blocks_rd_proof_cards_orb_id_media_id_fk" FOREIGN KEY ("orb_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_proof_cards" ADD CONSTRAINT "pages_blocks_rd_proof_cards_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_proof"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_proof_cards_locales" ADD CONSTRAINT "pages_blocks_rd_proof_cards_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_proof_cards"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_proof" ADD CONSTRAINT "pages_blocks_rd_proof_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_proof_locales" ADD CONSTRAINT "pages_blocks_rd_proof_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_proof"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_proof_cards" ADD CONSTRAINT "_pages_v_blocks_rd_proof_cards_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_proof_cards" ADD CONSTRAINT "_pages_v_blocks_rd_proof_cards_orb_id_media_id_fk" FOREIGN KEY ("orb_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_proof_cards" ADD CONSTRAINT "_pages_v_blocks_rd_proof_cards_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_proof"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_proof_cards_locales" ADD CONSTRAINT "_pages_v_blocks_rd_proof_cards_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_proof_cards"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_proof" ADD CONSTRAINT "_pages_v_blocks_rd_proof_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_proof_locales" ADD CONSTRAINT "_pages_v_blocks_rd_proof_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_proof"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_proof_cards_order_idx" ON "pages_blocks_rd_proof_cards" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_proof_cards_parent_id_idx" ON "pages_blocks_rd_proof_cards" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_proof_cards_image_idx" ON "pages_blocks_rd_proof_cards" USING btree ("image_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_proof_cards_orb_idx" ON "pages_blocks_rd_proof_cards" USING btree ("orb_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_proof_cards_locales_locale_parent_id_unique" ON "pages_blocks_rd_proof_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_proof_order_idx" ON "pages_blocks_rd_proof" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_proof_parent_id_idx" ON "pages_blocks_rd_proof" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_proof_path_idx" ON "pages_blocks_rd_proof" USING btree ("_path");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_proof_locales_locale_parent_id_unique" ON "pages_blocks_rd_proof_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_proof_cards_order_idx" ON "_pages_v_blocks_rd_proof_cards" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_proof_cards_parent_id_idx" ON "_pages_v_blocks_rd_proof_cards" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_proof_cards_image_idx" ON "_pages_v_blocks_rd_proof_cards" USING btree ("image_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_proof_cards_orb_idx" ON "_pages_v_blocks_rd_proof_cards" USING btree ("orb_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_proof_cards_locales_locale_parent_id_uniq" ON "_pages_v_blocks_rd_proof_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_proof_order_idx" ON "_pages_v_blocks_rd_proof" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_proof_parent_id_idx" ON "_pages_v_blocks_rd_proof" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_proof_path_idx" ON "_pages_v_blocks_rd_proof" USING btree ("_path");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_proof_locales_locale_parent_id_unique" ON "_pages_v_blocks_rd_proof_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_proof_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_proof" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_proof_cards_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_proof_cards" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_proof_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_proof" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_proof_cards_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_proof_cards" CASCADE;`)
}

