import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Add the `rdPrHero` block.
 *
 * GENERATED by tools/migrate_gen.py from the block's field schema — NOT by
 * `payload migrate:create`, whose snapshot in this repo is stale and emits DDL
 * for ~171 unrelated tables.
 *
 * Every statement is idempotent (IF NOT EXISTS / duplicate_object guards), so
 * it is safe to re-run over a partially applied attempt.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_pr_hero_primary_cta_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_pr_hero_secondary_cta_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_pr_hero_primary_cta_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_pr_hero_secondary_cta_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_hero_trust_avatars" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"photo_id" integer
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_hero" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"primary_cta_type" "enum_pages_blocks_rd_pr_hero_primary_cta_type" DEFAULT 'custom',
  	"primary_cta_new_tab" boolean,
  	"secondary_cta_type" "enum_pages_blocks_rd_pr_hero_secondary_cta_type" DEFAULT 'custom',
  	"secondary_cta_new_tab" boolean,
  	"image_id" integer,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_hero_locales" (
  	"heading" jsonb NOT NULL,
  	"intro" varchar,
  	"primary_cta_url" varchar,
  	"primary_cta_label" varchar,
  	"secondary_cta_url" varchar,
  	"secondary_cta_label" varchar,
  	"trust_text" jsonb,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_hero_trust_avatars" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"photo_id" integer,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_hero" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"primary_cta_type" "enum__pages_v_blocks_rd_pr_hero_primary_cta_type" DEFAULT 'custom',
  	"primary_cta_new_tab" boolean,
  	"secondary_cta_type" "enum__pages_v_blocks_rd_pr_hero_secondary_cta_type" DEFAULT 'custom',
  	"secondary_cta_new_tab" boolean,
  	"image_id" integer,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_hero_locales" (
  	"heading" jsonb NOT NULL,
  	"intro" varchar,
  	"primary_cta_url" varchar,
  	"primary_cta_label" varchar,
  	"secondary_cta_url" varchar,
  	"secondary_cta_label" varchar,
  	"trust_text" jsonb,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_hero_trust_avatars" ADD CONSTRAINT "pages_blocks_rd_pr_hero_trust_avatars_photo_id_media_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_hero_trust_avatars" ADD CONSTRAINT "pages_blocks_rd_pr_hero_trust_avatars_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_hero"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_hero" ADD CONSTRAINT "pages_blocks_rd_pr_hero_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_hero" ADD CONSTRAINT "pages_blocks_rd_pr_hero_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_hero_locales" ADD CONSTRAINT "pages_blocks_rd_pr_hero_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_hero"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_hero_trust_avatars" ADD CONSTRAINT "_pages_v_blocks_rd_pr_hero_trust_avatars_photo_id_media_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_hero_trust_avatars" ADD CONSTRAINT "_pages_v_blocks_rd_pr_hero_trust_avatars_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_hero"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_hero" ADD CONSTRAINT "_pages_v_blocks_rd_pr_hero_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_hero" ADD CONSTRAINT "_pages_v_blocks_rd_pr_hero_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_hero_locales" ADD CONSTRAINT "_pages_v_blocks_rd_pr_hero_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_hero"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_hero_trust_avatars_order_idx" ON "pages_blocks_rd_pr_hero_trust_avatars" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_hero_trust_avatars_parent_id_idx" ON "pages_blocks_rd_pr_hero_trust_avatars" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_hero_trust_avatars_photo_idx" ON "pages_blocks_rd_pr_hero_trust_avatars" USING btree ("photo_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_hero_order_idx" ON "pages_blocks_rd_pr_hero" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_hero_parent_id_idx" ON "pages_blocks_rd_pr_hero" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_hero_path_idx" ON "pages_blocks_rd_pr_hero" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_hero_image_idx" ON "pages_blocks_rd_pr_hero" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_pr_hero_locales_locale_parent_id_unique" ON "pages_blocks_rd_pr_hero_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_hero_trust_avatars_order_idx" ON "_pages_v_blocks_rd_pr_hero_trust_avatars" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_hero_trust_avatars_parent_id_idx" ON "_pages_v_blocks_rd_pr_hero_trust_avatars" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_hero_trust_avatars_photo_idx" ON "_pages_v_blocks_rd_pr_hero_trust_avatars" USING btree ("photo_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_hero_order_idx" ON "_pages_v_blocks_rd_pr_hero" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_hero_parent_id_idx" ON "_pages_v_blocks_rd_pr_hero" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_hero_path_idx" ON "_pages_v_blocks_rd_pr_hero" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_hero_image_idx" ON "_pages_v_blocks_rd_pr_hero" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_hero_locales_locale_parent_id_unique" ON "_pages_v_blocks_rd_pr_hero_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_hero_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_hero" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_hero_trust_avatars" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_hero_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_hero" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_hero_trust_avatars" CASCADE;
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_pr_hero_primary_cta_type";
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_pr_hero_secondary_cta_type";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_pr_hero_primary_cta_type";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_pr_hero_secondary_cta_type";`)
}

