import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Add the `rdPrAnalyse` block.
 *
 * GENERATED by tools/migrate_gen.py from the block's field schema — NOT by
 * `payload migrate:create`, whose snapshot in this repo is stale and emits DDL
 * for ~171 unrelated tables.
 *
 * Every statement is idempotent (IF NOT EXISTS / duplicate_object guards), so
 * it is safe to re-run over a partially applied attempt.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_pr_analyse_board_link_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_pr_analyse_board_link_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_analyse_people" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"photo_id" integer,
  	"focal" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_analyse_people_locales" (
  	"role" varchar,
  	"name" varchar NOT NULL,
  	"credentials" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_analyse_steps" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_analyse_steps_locales" (
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_analyse" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"board_link_type" "enum_pages_blocks_rd_pr_analyse_board_link_type" DEFAULT 'custom',
  	"board_link_new_tab" boolean,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_analyse_locales" (
  	"heading" jsonb NOT NULL,
  	"intro" varchar,
  	"footer_text" varchar,
  	"board_link_url" varchar,
  	"board_link_label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_people" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"photo_id" integer,
  	"focal" varchar,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_people_locales" (
  	"role" varchar,
  	"name" varchar NOT NULL,
  	"credentials" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_steps" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_steps_locales" (
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"board_link_type" "enum__pages_v_blocks_rd_pr_analyse_board_link_type" DEFAULT 'custom',
  	"board_link_new_tab" boolean,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_locales" (
  	"heading" jsonb NOT NULL,
  	"intro" varchar,
  	"footer_text" varchar,
  	"board_link_url" varchar,
  	"board_link_label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_analyse_people" ADD CONSTRAINT "pages_blocks_rd_pr_analyse_people_photo_id_media_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_analyse_people" ADD CONSTRAINT "pages_blocks_rd_pr_analyse_people_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_analyse"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_analyse_people_locales" ADD CONSTRAINT "pages_blocks_rd_pr_analyse_people_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_analyse_people"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_analyse_steps" ADD CONSTRAINT "pages_blocks_rd_pr_analyse_steps_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_analyse"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_analyse_steps_locales" ADD CONSTRAINT "pages_blocks_rd_pr_analyse_steps_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_analyse_steps"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_analyse" ADD CONSTRAINT "pages_blocks_rd_pr_analyse_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_analyse_locales" ADD CONSTRAINT "pages_blocks_rd_pr_analyse_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_analyse"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_analyse_people" ADD CONSTRAINT "_pages_v_blocks_rd_pr_analyse_people_photo_id_media_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_analyse_people" ADD CONSTRAINT "_pages_v_blocks_rd_pr_analyse_people_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_analyse"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_analyse_people_locales" ADD CONSTRAINT "_pages_v_blocks_rd_pr_analyse_people_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_analyse_people"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_analyse_steps" ADD CONSTRAINT "_pages_v_blocks_rd_pr_analyse_steps_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_analyse"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_analyse_steps_locales" ADD CONSTRAINT "_pages_v_blocks_rd_pr_analyse_steps_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_analyse_steps"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_analyse" ADD CONSTRAINT "_pages_v_blocks_rd_pr_analyse_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_analyse_locales" ADD CONSTRAINT "_pages_v_blocks_rd_pr_analyse_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_analyse"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_analyse_people_order_idx" ON "pages_blocks_rd_pr_analyse_people" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_analyse_people_parent_id_idx" ON "pages_blocks_rd_pr_analyse_people" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_analyse_people_photo_idx" ON "pages_blocks_rd_pr_analyse_people" USING btree ("photo_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_pr_analyse_people_locales_locale_parent_id_u" ON "pages_blocks_rd_pr_analyse_people_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_analyse_steps_order_idx" ON "pages_blocks_rd_pr_analyse_steps" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_analyse_steps_parent_id_idx" ON "pages_blocks_rd_pr_analyse_steps" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_pr_analyse_steps_locales_locale_parent_id_un" ON "pages_blocks_rd_pr_analyse_steps_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_analyse_order_idx" ON "pages_blocks_rd_pr_analyse" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_analyse_parent_id_idx" ON "pages_blocks_rd_pr_analyse" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_analyse_path_idx" ON "pages_blocks_rd_pr_analyse" USING btree ("_path");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_pr_analyse_locales_locale_parent_id_unique" ON "pages_blocks_rd_pr_analyse_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_people_order_idx" ON "_pages_v_blocks_rd_pr_analyse_people" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_people_parent_id_idx" ON "_pages_v_blocks_rd_pr_analyse_people" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_people_photo_idx" ON "_pages_v_blocks_rd_pr_analyse_people" USING btree ("photo_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_people_locales_locale_parent_i" ON "_pages_v_blocks_rd_pr_analyse_people_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_steps_order_idx" ON "_pages_v_blocks_rd_pr_analyse_steps" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_steps_parent_id_idx" ON "_pages_v_blocks_rd_pr_analyse_steps" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_steps_locales_locale_parent_id" ON "_pages_v_blocks_rd_pr_analyse_steps_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_order_idx" ON "_pages_v_blocks_rd_pr_analyse" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_parent_id_idx" ON "_pages_v_blocks_rd_pr_analyse" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_path_idx" ON "_pages_v_blocks_rd_pr_analyse" USING btree ("_path");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_analyse_locales_locale_parent_id_uniqu" ON "_pages_v_blocks_rd_pr_analyse_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_analyse_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_analyse" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_analyse_steps_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_analyse_steps" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_analyse_people_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_analyse_people" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_analyse_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_analyse" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_analyse_steps_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_analyse_steps" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_analyse_people_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_analyse_people" CASCADE;
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_pr_analyse_board_link_type";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_pr_analyse_board_link_type";`)
}

