import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Add the `rdChk` block.
 *
 * GENERATED by tools/migrate_gen.py from the block's field schema — NOT by
 * `payload migrate:create`, whose snapshot in this repo is stale and emits DDL
 * for ~171 unrelated tables.
 *
 * Every statement is idempotent (IF NOT EXISTS / duplicate_object guards), so
 * it is safe to re-run over a partially applied attempt.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_chk_pay_methods_key" AS ENUM('card', 'klarna', 'paypal', 'dd');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_chk_pay_methods_key" AS ENUM('card', 'klarna', 'paypal', 'dd');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_steps_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_steps_items_locales" (
  	"label" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_acc_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_acc_items_locales" (
  	"title" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_adr_fields" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_adr_fields_locales" (
  	"label" varchar NOT NULL,
  	"placeholder" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_pay_card_fields" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_pay_card_fields_locales" (
  	"label" varchar NOT NULL,
  	"placeholder" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_pay_methods" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"key" "enum_pages_blocks_rd_chk_pay_methods_key" NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_pay_methods_locales" (
  	"label" varchar NOT NULL,
  	"meta" varchar,
  	"note" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_next_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_next_rows_locales" (
  	"text" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_done_time_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_done_time_rows_locales" (
  	"when" varchar NOT NULL,
  	"title" varchar,
  	"badge" varchar,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"steps_logo_id" integer,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_chk_locales" (
  	"steps_logo_alt" varchar,
  	"steps_home_slug" varchar,
  	"steps_back_label" varchar,
  	"steps_back_label_done" varchar,
  	"hero_heading" varchar NOT NULL,
  	"hero_intro" varchar,
  	"sum_toggle_label" varchar,
  	"sum_plan_label" varchar,
  	"sum_billing_label" varchar,
  	"sum_billing_flex" varchar,
  	"sum_billing_suffix" varchar,
  	"sum_analysis_label" varchar,
  	"sum_analysis_value" varchar,
  	"sum_ship_label" varchar,
  	"sum_ship_value" varchar,
  	"sum_per_label" varchar,
  	"sum_discount_label" varchar,
  	"sum_referral_label" varchar,
  	"sum_note_heading" varchar,
  	"sum_note" varchar,
  	"sum_secure_label" varchar,
  	"acc_next_label" varchar,
  	"acc_edit_label" varchar,
  	"eml_label" varchar,
  	"eml_help" varchar,
  	"eml_placeholder" varchar,
  	"adr_note" varchar,
  	"pay_or_label" varchar,
  	"pay_card_label" varchar,
  	"pay_card_meta" varchar,
  	"pay_billing_same" varchar,
  	"pay_cta" varchar,
  	"pay_terms" varchar,
  	"next_heading" varchar,
  	"done_order_prefix" varchar,
  	"done_head_prefix" varchar NOT NULL,
  	"done_head_suffix" varchar,
  	"done_intro" varchar,
  	"done_acct_heading" varchar,
  	"done_acct_body" varchar,
  	"done_acct_cta" varchar,
  	"done_acct_slug" varchar,
  	"done_surv_heading" varchar,
  	"done_surv_intro" varchar,
  	"done_surv_other" varchar,
  	"done_time_heading" varchar,
  	"done_sum_heading" varchar,
  	"done_sum_plan_label" varchar,
  	"done_sum_cycle_label" varchar,
  	"done_sum_deliv_label" varchar,
  	"done_sum_deliv_value" varchar,
  	"done_sum_per_label" varchar,
  	"done_charged_today" varchar,
  	"done_charge_prefix" varchar,
  	"done_charge_bold" varchar,
  	"done_charge_suffix" varchar,
  	"done_help_chat" varchar,
  	"done_help_chat_url" varchar,
  	"done_help_or" varchar,
  	"done_help_email" varchar,
  	"done_help_email_url" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_steps_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_steps_items_locales" (
  	"label" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_acc_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_acc_items_locales" (
  	"title" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_adr_fields" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_adr_fields_locales" (
  	"label" varchar NOT NULL,
  	"placeholder" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_pay_card_fields" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_pay_card_fields_locales" (
  	"label" varchar NOT NULL,
  	"placeholder" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_pay_methods" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"key" "enum__pages_v_blocks_rd_chk_pay_methods_key" NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_pay_methods_locales" (
  	"label" varchar NOT NULL,
  	"meta" varchar,
  	"note" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_next_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_next_rows_locales" (
  	"text" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_done_time_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_done_time_rows_locales" (
  	"when" varchar NOT NULL,
  	"title" varchar,
  	"badge" varchar,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"steps_logo_id" integer,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_chk_locales" (
  	"steps_logo_alt" varchar,
  	"steps_home_slug" varchar,
  	"steps_back_label" varchar,
  	"steps_back_label_done" varchar,
  	"hero_heading" varchar NOT NULL,
  	"hero_intro" varchar,
  	"sum_toggle_label" varchar,
  	"sum_plan_label" varchar,
  	"sum_billing_label" varchar,
  	"sum_billing_flex" varchar,
  	"sum_billing_suffix" varchar,
  	"sum_analysis_label" varchar,
  	"sum_analysis_value" varchar,
  	"sum_ship_label" varchar,
  	"sum_ship_value" varchar,
  	"sum_per_label" varchar,
  	"sum_discount_label" varchar,
  	"sum_referral_label" varchar,
  	"sum_note_heading" varchar,
  	"sum_note" varchar,
  	"sum_secure_label" varchar,
  	"acc_next_label" varchar,
  	"acc_edit_label" varchar,
  	"eml_label" varchar,
  	"eml_help" varchar,
  	"eml_placeholder" varchar,
  	"adr_note" varchar,
  	"pay_or_label" varchar,
  	"pay_card_label" varchar,
  	"pay_card_meta" varchar,
  	"pay_billing_same" varchar,
  	"pay_cta" varchar,
  	"pay_terms" varchar,
  	"next_heading" varchar,
  	"done_order_prefix" varchar,
  	"done_head_prefix" varchar NOT NULL,
  	"done_head_suffix" varchar,
  	"done_intro" varchar,
  	"done_acct_heading" varchar,
  	"done_acct_body" varchar,
  	"done_acct_cta" varchar,
  	"done_acct_slug" varchar,
  	"done_surv_heading" varchar,
  	"done_surv_intro" varchar,
  	"done_surv_other" varchar,
  	"done_time_heading" varchar,
  	"done_sum_heading" varchar,
  	"done_sum_plan_label" varchar,
  	"done_sum_cycle_label" varchar,
  	"done_sum_deliv_label" varchar,
  	"done_sum_deliv_value" varchar,
  	"done_sum_per_label" varchar,
  	"done_charged_today" varchar,
  	"done_charge_prefix" varchar,
  	"done_charge_bold" varchar,
  	"done_charge_suffix" varchar,
  	"done_help_chat" varchar,
  	"done_help_chat_url" varchar,
  	"done_help_or" varchar,
  	"done_help_email" varchar,
  	"done_help_email_url" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_steps_items" ADD CONSTRAINT "pages_blocks_rd_chk_steps_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_steps_items_locales" ADD CONSTRAINT "pages_blocks_rd_chk_steps_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk_steps_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_acc_items" ADD CONSTRAINT "pages_blocks_rd_chk_acc_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_acc_items_locales" ADD CONSTRAINT "pages_blocks_rd_chk_acc_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk_acc_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_adr_fields" ADD CONSTRAINT "pages_blocks_rd_chk_adr_fields_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_adr_fields_locales" ADD CONSTRAINT "pages_blocks_rd_chk_adr_fields_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk_adr_fields"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_pay_card_fields" ADD CONSTRAINT "pages_blocks_rd_chk_pay_card_fields_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_pay_card_fields_locales" ADD CONSTRAINT "pages_blocks_rd_chk_pay_card_fields_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk_pay_card_fields"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_pay_methods" ADD CONSTRAINT "pages_blocks_rd_chk_pay_methods_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_pay_methods_locales" ADD CONSTRAINT "pages_blocks_rd_chk_pay_methods_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk_pay_methods"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_next_rows" ADD CONSTRAINT "pages_blocks_rd_chk_next_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_next_rows_locales" ADD CONSTRAINT "pages_blocks_rd_chk_next_rows_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk_next_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_done_time_rows" ADD CONSTRAINT "pages_blocks_rd_chk_done_time_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_done_time_rows_locales" ADD CONSTRAINT "pages_blocks_rd_chk_done_time_rows_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk_done_time_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk" ADD CONSTRAINT "pages_blocks_rd_chk_steps_logo_id_media_id_fk" FOREIGN KEY ("steps_logo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk" ADD CONSTRAINT "pages_blocks_rd_chk_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_chk_locales" ADD CONSTRAINT "pages_blocks_rd_chk_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_steps_items" ADD CONSTRAINT "_pages_v_blocks_rd_chk_steps_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_steps_items_locales" ADD CONSTRAINT "_pages_v_blocks_rd_chk_steps_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk_steps_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_acc_items" ADD CONSTRAINT "_pages_v_blocks_rd_chk_acc_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_acc_items_locales" ADD CONSTRAINT "_pages_v_blocks_rd_chk_acc_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk_acc_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_adr_fields" ADD CONSTRAINT "_pages_v_blocks_rd_chk_adr_fields_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_adr_fields_locales" ADD CONSTRAINT "_pages_v_blocks_rd_chk_adr_fields_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk_adr_fields"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_pay_card_fields" ADD CONSTRAINT "_pages_v_blocks_rd_chk_pay_card_fields_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_pay_card_fields_locales" ADD CONSTRAINT "_pages_v_blocks_rd_chk_pay_card_fields_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk_pay_card_fields"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_pay_methods" ADD CONSTRAINT "_pages_v_blocks_rd_chk_pay_methods_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_pay_methods_locales" ADD CONSTRAINT "_pages_v_blocks_rd_chk_pay_methods_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk_pay_methods"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_next_rows" ADD CONSTRAINT "_pages_v_blocks_rd_chk_next_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_next_rows_locales" ADD CONSTRAINT "_pages_v_blocks_rd_chk_next_rows_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk_next_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_done_time_rows" ADD CONSTRAINT "_pages_v_blocks_rd_chk_done_time_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_done_time_rows_locales" ADD CONSTRAINT "_pages_v_blocks_rd_chk_done_time_rows_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk_done_time_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk" ADD CONSTRAINT "_pages_v_blocks_rd_chk_steps_logo_id_media_id_fk" FOREIGN KEY ("steps_logo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk" ADD CONSTRAINT "_pages_v_blocks_rd_chk_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_chk_locales" ADD CONSTRAINT "_pages_v_blocks_rd_chk_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_chk"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_steps_items_order_idx" ON "pages_blocks_rd_chk_steps_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_steps_items_parent_id_idx" ON "pages_blocks_rd_chk_steps_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_chk_steps_items_locales_locale_parent_id_uni" ON "pages_blocks_rd_chk_steps_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_acc_items_order_idx" ON "pages_blocks_rd_chk_acc_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_acc_items_parent_id_idx" ON "pages_blocks_rd_chk_acc_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_chk_acc_items_locales_locale_parent_id_uniqu" ON "pages_blocks_rd_chk_acc_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_adr_fields_order_idx" ON "pages_blocks_rd_chk_adr_fields" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_adr_fields_parent_id_idx" ON "pages_blocks_rd_chk_adr_fields" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_chk_adr_fields_locales_locale_parent_id_uniq" ON "pages_blocks_rd_chk_adr_fields_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_pay_card_fields_order_idx" ON "pages_blocks_rd_chk_pay_card_fields" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_pay_card_fields_parent_id_idx" ON "pages_blocks_rd_chk_pay_card_fields" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_chk_pay_card_fields_locales_locale_parent_id" ON "pages_blocks_rd_chk_pay_card_fields_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_pay_methods_order_idx" ON "pages_blocks_rd_chk_pay_methods" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_pay_methods_parent_id_idx" ON "pages_blocks_rd_chk_pay_methods" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_chk_pay_methods_locales_locale_parent_id_uni" ON "pages_blocks_rd_chk_pay_methods_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_next_rows_order_idx" ON "pages_blocks_rd_chk_next_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_next_rows_parent_id_idx" ON "pages_blocks_rd_chk_next_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_chk_next_rows_locales_locale_parent_id_uniqu" ON "pages_blocks_rd_chk_next_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_done_time_rows_order_idx" ON "pages_blocks_rd_chk_done_time_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_done_time_rows_parent_id_idx" ON "pages_blocks_rd_chk_done_time_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_chk_done_time_rows_locales_locale_parent_id_" ON "pages_blocks_rd_chk_done_time_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_order_idx" ON "pages_blocks_rd_chk" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_parent_id_idx" ON "pages_blocks_rd_chk" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_path_idx" ON "pages_blocks_rd_chk" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_chk_steps_logo_idx" ON "pages_blocks_rd_chk" USING btree ("steps_logo_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_chk_locales_locale_parent_id_unique" ON "pages_blocks_rd_chk_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_steps_items_order_idx" ON "_pages_v_blocks_rd_chk_steps_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_steps_items_parent_id_idx" ON "_pages_v_blocks_rd_chk_steps_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_steps_items_locales_locale_parent_id_" ON "_pages_v_blocks_rd_chk_steps_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_acc_items_order_idx" ON "_pages_v_blocks_rd_chk_acc_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_acc_items_parent_id_idx" ON "_pages_v_blocks_rd_chk_acc_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_acc_items_locales_locale_parent_id_un" ON "_pages_v_blocks_rd_chk_acc_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_adr_fields_order_idx" ON "_pages_v_blocks_rd_chk_adr_fields" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_adr_fields_parent_id_idx" ON "_pages_v_blocks_rd_chk_adr_fields" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_adr_fields_locales_locale_parent_id_u" ON "_pages_v_blocks_rd_chk_adr_fields_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_pay_card_fields_order_idx" ON "_pages_v_blocks_rd_chk_pay_card_fields" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_pay_card_fields_parent_id_idx" ON "_pages_v_blocks_rd_chk_pay_card_fields" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_pay_card_fields_locales_locale_parent" ON "_pages_v_blocks_rd_chk_pay_card_fields_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_pay_methods_order_idx" ON "_pages_v_blocks_rd_chk_pay_methods" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_pay_methods_parent_id_idx" ON "_pages_v_blocks_rd_chk_pay_methods" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_pay_methods_locales_locale_parent_id_" ON "_pages_v_blocks_rd_chk_pay_methods_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_next_rows_order_idx" ON "_pages_v_blocks_rd_chk_next_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_next_rows_parent_id_idx" ON "_pages_v_blocks_rd_chk_next_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_next_rows_locales_locale_parent_id_un" ON "_pages_v_blocks_rd_chk_next_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_done_time_rows_order_idx" ON "_pages_v_blocks_rd_chk_done_time_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_done_time_rows_parent_id_idx" ON "_pages_v_blocks_rd_chk_done_time_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_done_time_rows_locales_locale_parent_" ON "_pages_v_blocks_rd_chk_done_time_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_order_idx" ON "_pages_v_blocks_rd_chk" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_parent_id_idx" ON "_pages_v_blocks_rd_chk" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_path_idx" ON "_pages_v_blocks_rd_chk" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_steps_logo_idx" ON "_pages_v_blocks_rd_chk" USING btree ("steps_logo_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_chk_locales_locale_parent_id_unique" ON "_pages_v_blocks_rd_chk_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_done_time_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_done_time_rows" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_next_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_next_rows" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_pay_methods_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_pay_methods" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_pay_card_fields_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_pay_card_fields" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_adr_fields_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_adr_fields" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_acc_items_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_acc_items" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_steps_items_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_chk_steps_items" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_done_time_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_done_time_rows" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_next_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_next_rows" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_pay_methods_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_pay_methods" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_pay_card_fields_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_pay_card_fields" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_adr_fields_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_adr_fields" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_acc_items_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_acc_items" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_steps_items_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_chk_steps_items" CASCADE;
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_chk_pay_methods_key";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_chk_pay_methods_key";`)
}

