import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Add the `rdHero` block.
 *
 * WHY THIS IS HAND-GENERATED RATHER THAN FROM `migrate:create`
 *
 * `db:resync-snapshot` was run AFTER the block was registered in
 * Pages.layout.blocks, so the new baseline (20260922_112204_resync_baseline.json)
 * records all twelve `pages_blocks_rd_hero*` tables as already existing. They did
 * not. A resync ASSERTS "the database already matches the config" — asserting
 * that while a genuine change is pending is exactly what check-schema-drift.ts
 * warns about, and it makes the change permanently invisible to `migrate:create`,
 * which now correctly emits nothing.
 *
 * The ordering rule: resync BEFORE registering a new block, never after.
 *
 * This file closes the gap. It is generated by tools/migrate_gen.py from the
 * block's field schema, which never reads or writes the snapshot, and was
 * verified AGAINST that snapshot: same 12 tables, same columns, same types, 14
 * foreign keys, 22 indexes. Once it has run, the snapshot's claim is true again.
 *
 * Every statement is idempotent, so it is safe to re-run over a partial attempt.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_hero_primary_cta_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_hero_secondary_cta_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_hero_primary_cta_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_hero_secondary_cta_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_hero_bubbles" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_hero_bubbles_locales" (
  	"label" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_hero_claims" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_hero_claims_locales" (
  	"body" jsonb NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_hero" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"hero_image_id" integer,
  	"primary_cta_type" "enum_pages_blocks_rd_hero_primary_cta_type" DEFAULT 'custom',
  	"primary_cta_new_tab" boolean,
  	"secondary_cta_type" "enum_pages_blocks_rd_hero_secondary_cta_type" DEFAULT 'custom',
  	"secondary_cta_new_tab" boolean,
  	"show_trustpilot_rating" boolean DEFAULT true,
  	"trust_cycle_ms" numeric DEFAULT 3400,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_hero_locales" (
  	"heading" varchar NOT NULL,
  	"intro" varchar,
  	"primary_cta_url" varchar,
  	"primary_cta_label" varchar,
  	"secondary_cta_url" varchar,
  	"secondary_cta_label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_hero_bubbles" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_hero_bubbles_locales" (
  	"label" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_hero_claims" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_hero_claims_locales" (
  	"body" jsonb NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_hero" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"hero_image_id" integer,
  	"primary_cta_type" "enum__pages_v_blocks_rd_hero_primary_cta_type" DEFAULT 'custom',
  	"primary_cta_new_tab" boolean,
  	"secondary_cta_type" "enum__pages_v_blocks_rd_hero_secondary_cta_type" DEFAULT 'custom',
  	"secondary_cta_new_tab" boolean,
  	"show_trustpilot_rating" boolean DEFAULT true,
  	"trust_cycle_ms" numeric DEFAULT 3400,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_hero_locales" (
  	"heading" varchar NOT NULL,
  	"intro" varchar,
  	"primary_cta_url" varchar,
  	"primary_cta_label" varchar,
  	"secondary_cta_url" varchar,
  	"secondary_cta_label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_hero_bubbles" ADD CONSTRAINT "pages_blocks_rd_hero_bubbles_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_hero"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_hero_bubbles_locales" ADD CONSTRAINT "pages_blocks_rd_hero_bubbles_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_hero_bubbles"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_hero_claims" ADD CONSTRAINT "pages_blocks_rd_hero_claims_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_hero"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_hero_claims_locales" ADD CONSTRAINT "pages_blocks_rd_hero_claims_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_hero_claims"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_hero" ADD CONSTRAINT "pages_blocks_rd_hero_hero_image_id_media_id_fk" FOREIGN KEY ("hero_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_hero" ADD CONSTRAINT "pages_blocks_rd_hero_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_hero_locales" ADD CONSTRAINT "pages_blocks_rd_hero_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_hero"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_hero_bubbles" ADD CONSTRAINT "_pages_v_blocks_rd_hero_bubbles_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_hero"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_hero_bubbles_locales" ADD CONSTRAINT "_pages_v_blocks_rd_hero_bubbles_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_hero_bubbles"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_hero_claims" ADD CONSTRAINT "_pages_v_blocks_rd_hero_claims_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_hero"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_hero_claims_locales" ADD CONSTRAINT "_pages_v_blocks_rd_hero_claims_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_hero_claims"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_hero" ADD CONSTRAINT "_pages_v_blocks_rd_hero_hero_image_id_media_id_fk" FOREIGN KEY ("hero_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_hero" ADD CONSTRAINT "_pages_v_blocks_rd_hero_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_hero_locales" ADD CONSTRAINT "_pages_v_blocks_rd_hero_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_hero"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_hero_bubbles_order_idx" ON "pages_blocks_rd_hero_bubbles" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_hero_bubbles_parent_id_idx" ON "pages_blocks_rd_hero_bubbles" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_hero_bubbles_locales_locale_parent_id_unique" ON "pages_blocks_rd_hero_bubbles_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_hero_claims_order_idx" ON "pages_blocks_rd_hero_claims" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_hero_claims_parent_id_idx" ON "pages_blocks_rd_hero_claims" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_hero_claims_locales_locale_parent_id_unique" ON "pages_blocks_rd_hero_claims_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_hero_order_idx" ON "pages_blocks_rd_hero" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_hero_parent_id_idx" ON "pages_blocks_rd_hero" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_hero_path_idx" ON "pages_blocks_rd_hero" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_hero_hero_image_idx" ON "pages_blocks_rd_hero" USING btree ("hero_image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_hero_locales_locale_parent_id_unique" ON "pages_blocks_rd_hero_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_hero_bubbles_order_idx" ON "_pages_v_blocks_rd_hero_bubbles" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_hero_bubbles_parent_id_idx" ON "_pages_v_blocks_rd_hero_bubbles" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_hero_bubbles_locales_locale_parent_id_uni" ON "_pages_v_blocks_rd_hero_bubbles_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_hero_claims_order_idx" ON "_pages_v_blocks_rd_hero_claims" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_hero_claims_parent_id_idx" ON "_pages_v_blocks_rd_hero_claims" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_hero_claims_locales_locale_parent_id_uniq" ON "_pages_v_blocks_rd_hero_claims_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_hero_order_idx" ON "_pages_v_blocks_rd_hero" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_hero_parent_id_idx" ON "_pages_v_blocks_rd_hero" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_hero_path_idx" ON "_pages_v_blocks_rd_hero" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_hero_hero_image_idx" ON "_pages_v_blocks_rd_hero" USING btree ("hero_image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_hero_locales_locale_parent_id_unique" ON "_pages_v_blocks_rd_hero_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_hero_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_hero" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_hero_claims_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_hero_claims" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_hero_bubbles_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_hero_bubbles" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_hero_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_hero" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_hero_claims_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_hero_claims" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_hero_bubbles_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_hero_bubbles" CASCADE;
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_hero_primary_cta_type";
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_hero_secondary_cta_type";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_hero_primary_cta_type";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_hero_secondary_cta_type";`)
}

