import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Add the `rdPrArrives` block.
 *
 * GENERATED by tools/migrate_gen.py from the block's field schema — NOT by
 * `payload migrate:create`, whose snapshot in this repo is stale and emits DDL
 * for ~171 unrelated tables.
 *
 * Every statement is idempotent (IF NOT EXISTS / duplicate_object guards), so
 * it is safe to re-run over a partially applied attempt.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_pr_arrives_packs_domain" AS ENUM('gut', 'energy', 'resilience', 'immunity', 'sleep');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_pr_arrives_packs_accent" AS ENUM('lime', 'blue-grey', 'blue', 'soft-pink', 'orange');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_pr_arrives_shots_plate" AS ENUM('cool-grey', 'tint');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_pr_arrives_packs_domain" AS ENUM('gut', 'energy', 'resilience', 'immunity', 'sleep');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_pr_arrives_packs_accent" AS ENUM('lime', 'blue-grey', 'blue', 'soft-pink', 'orange');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_pr_arrives_shots_plate" AS ENUM('cool-grey', 'tint');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_arrives_packs_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_arrives_packs_items_locales" (
  	"text" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_arrives_packs" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"domain" "enum_pages_blocks_rd_pr_arrives_packs_domain",
  	"accent" "enum_pages_blocks_rd_pr_arrives_packs_accent"
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_arrives_packs_locales" (
  	"name" varchar NOT NULL,
  	"timing" varchar,
  	"form" varchar,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_arrives_shots" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"image_id" integer,
  	"plate" "enum_pages_blocks_rd_pr_arrives_shots_plate"
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_arrives_shots_locales" (
  	"alt" varchar,
  	"caption" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_arrives_benefits" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_arrives_benefits_locales" (
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_arrives" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"proof_image_id" integer,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_arrives_locales" (
  	"heading" jsonb NOT NULL,
  	"intro" varchar,
  	"midline" varchar,
  	"proof_alt" varchar,
  	"quote" varchar,
  	"attribution" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_packs_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_packs_items_locales" (
  	"text" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_packs" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"domain" "enum__pages_v_blocks_rd_pr_arrives_packs_domain",
  	"accent" "enum__pages_v_blocks_rd_pr_arrives_packs_accent",
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_packs_locales" (
  	"name" varchar NOT NULL,
  	"timing" varchar,
  	"form" varchar,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_shots" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"image_id" integer,
  	"plate" "enum__pages_v_blocks_rd_pr_arrives_shots_plate",
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_shots_locales" (
  	"alt" varchar,
  	"caption" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_benefits" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_benefits_locales" (
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"proof_image_id" integer,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_locales" (
  	"heading" jsonb NOT NULL,
  	"intro" varchar,
  	"midline" varchar,
  	"proof_alt" varchar,
  	"quote" varchar,
  	"attribution" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_arrives_packs_items" ADD CONSTRAINT "pages_blocks_rd_pr_arrives_packs_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_arrives_packs"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_arrives_packs_items_locales" ADD CONSTRAINT "pages_blocks_rd_pr_arrives_packs_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_arrives_packs_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_arrives_packs" ADD CONSTRAINT "pages_blocks_rd_pr_arrives_packs_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_arrives"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_arrives_packs_locales" ADD CONSTRAINT "pages_blocks_rd_pr_arrives_packs_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_arrives_packs"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_arrives_shots" ADD CONSTRAINT "pages_blocks_rd_pr_arrives_shots_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_arrives_shots" ADD CONSTRAINT "pages_blocks_rd_pr_arrives_shots_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_arrives"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_arrives_shots_locales" ADD CONSTRAINT "pages_blocks_rd_pr_arrives_shots_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_arrives_shots"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_arrives_benefits" ADD CONSTRAINT "pages_blocks_rd_pr_arrives_benefits_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_arrives"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_arrives_benefits_locales" ADD CONSTRAINT "pages_blocks_rd_pr_arrives_benefits_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_arrives_benefits"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_arrives" ADD CONSTRAINT "pages_blocks_rd_pr_arrives_proof_image_id_media_id_fk" FOREIGN KEY ("proof_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_arrives" ADD CONSTRAINT "pages_blocks_rd_pr_arrives_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_arrives_locales" ADD CONSTRAINT "pages_blocks_rd_pr_arrives_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_arrives"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_arrives_packs_items" ADD CONSTRAINT "_pages_v_blocks_rd_pr_arrives_packs_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_arrives_packs"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_arrives_packs_items_locales" ADD CONSTRAINT "_pages_v_blocks_rd_pr_arrives_packs_items_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_arrives_packs_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_arrives_packs" ADD CONSTRAINT "_pages_v_blocks_rd_pr_arrives_packs_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_arrives"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_arrives_packs_locales" ADD CONSTRAINT "_pages_v_blocks_rd_pr_arrives_packs_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_arrives_packs"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_arrives_shots" ADD CONSTRAINT "_pages_v_blocks_rd_pr_arrives_shots_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_arrives_shots" ADD CONSTRAINT "_pages_v_blocks_rd_pr_arrives_shots_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_arrives"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_arrives_shots_locales" ADD CONSTRAINT "_pages_v_blocks_rd_pr_arrives_shots_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_arrives_shots"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_arrives_benefits" ADD CONSTRAINT "_pages_v_blocks_rd_pr_arrives_benefits_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_arrives"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_arrives_benefits_locales" ADD CONSTRAINT "_pages_v_blocks_rd_pr_arrives_benefits_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_arrives_benefits"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_arrives" ADD CONSTRAINT "_pages_v_blocks_rd_pr_arrives_proof_image_id_media_id_fk" FOREIGN KEY ("proof_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_arrives" ADD CONSTRAINT "_pages_v_blocks_rd_pr_arrives_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_arrives_locales" ADD CONSTRAINT "_pages_v_blocks_rd_pr_arrives_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_arrives"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_packs_items_order_idx" ON "pages_blocks_rd_pr_arrives_packs_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_packs_items_parent_id_idx" ON "pages_blocks_rd_pr_arrives_packs_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_packs_items_locales_locale_parent" ON "pages_blocks_rd_pr_arrives_packs_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_packs_order_idx" ON "pages_blocks_rd_pr_arrives_packs" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_packs_parent_id_idx" ON "pages_blocks_rd_pr_arrives_packs" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_packs_locales_locale_parent_id_un" ON "pages_blocks_rd_pr_arrives_packs_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_shots_order_idx" ON "pages_blocks_rd_pr_arrives_shots" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_shots_parent_id_idx" ON "pages_blocks_rd_pr_arrives_shots" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_shots_image_idx" ON "pages_blocks_rd_pr_arrives_shots" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_shots_locales_locale_parent_id_un" ON "pages_blocks_rd_pr_arrives_shots_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_benefits_order_idx" ON "pages_blocks_rd_pr_arrives_benefits" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_benefits_parent_id_idx" ON "pages_blocks_rd_pr_arrives_benefits" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_benefits_locales_locale_parent_id" ON "pages_blocks_rd_pr_arrives_benefits_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_order_idx" ON "pages_blocks_rd_pr_arrives" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_parent_id_idx" ON "pages_blocks_rd_pr_arrives" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_path_idx" ON "pages_blocks_rd_pr_arrives" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_proof_image_idx" ON "pages_blocks_rd_pr_arrives" USING btree ("proof_image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_pr_arrives_locales_locale_parent_id_unique" ON "pages_blocks_rd_pr_arrives_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_packs_items_order_idx" ON "_pages_v_blocks_rd_pr_arrives_packs_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_packs_items_parent_id_idx" ON "_pages_v_blocks_rd_pr_arrives_packs_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_packs_items_locales_locale_par" ON "_pages_v_blocks_rd_pr_arrives_packs_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_packs_order_idx" ON "_pages_v_blocks_rd_pr_arrives_packs" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_packs_parent_id_idx" ON "_pages_v_blocks_rd_pr_arrives_packs" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_packs_locales_locale_parent_id" ON "_pages_v_blocks_rd_pr_arrives_packs_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_shots_order_idx" ON "_pages_v_blocks_rd_pr_arrives_shots" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_shots_parent_id_idx" ON "_pages_v_blocks_rd_pr_arrives_shots" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_shots_image_idx" ON "_pages_v_blocks_rd_pr_arrives_shots" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_shots_locales_locale_parent_id" ON "_pages_v_blocks_rd_pr_arrives_shots_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_benefits_order_idx" ON "_pages_v_blocks_rd_pr_arrives_benefits" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_benefits_parent_id_idx" ON "_pages_v_blocks_rd_pr_arrives_benefits" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_benefits_locales_locale_parent" ON "_pages_v_blocks_rd_pr_arrives_benefits_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_order_idx" ON "_pages_v_blocks_rd_pr_arrives" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_parent_id_idx" ON "_pages_v_blocks_rd_pr_arrives" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_path_idx" ON "_pages_v_blocks_rd_pr_arrives" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_proof_image_idx" ON "_pages_v_blocks_rd_pr_arrives" USING btree ("proof_image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_arrives_locales_locale_parent_id_uniqu" ON "_pages_v_blocks_rd_pr_arrives_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_arrives_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_arrives" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_arrives_benefits_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_arrives_benefits" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_arrives_shots_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_arrives_shots" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_arrives_packs_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_arrives_packs" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_arrives_packs_items_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_arrives_packs_items" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_arrives_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_arrives" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_arrives_benefits_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_arrives_benefits" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_arrives_shots_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_arrives_shots" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_arrives_packs_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_arrives_packs" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_arrives_packs_items_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_arrives_packs_items" CASCADE;
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_pr_arrives_packs_domain";
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_pr_arrives_packs_accent";
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_pr_arrives_shots_plate";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_pr_arrives_packs_domain";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_pr_arrives_packs_accent";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_pr_arrives_shots_plate";`)
}

