import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Add the `rdPlans` block.
 *
 * GENERATED by tools/migrate_gen.py from the block's field schema — NOT by
 * `payload migrate:create`, whose snapshot in this repo is stale and emits DDL
 * for ~171 unrelated tables.
 *
 * Every statement is idempotent (IF NOT EXISTS / duplicate_object guards), so
 * it is safe to re-run over a partially applied attempt.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_plans_core_cta_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_plans_advanced_cta_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_plans_compare_rows_core_kind" AS ENUM('included', 'excluded', 'text');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_plans_compare_rows_advanced_kind" AS ENUM('included', 'excluded', 'text');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_plans_core_cta_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_plans_advanced_cta_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_plans_compare_rows_core_kind" AS ENUM('included', 'excluded', 'text');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_plans_compare_rows_advanced_kind" AS ENUM('included', 'excluded', 'text');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_plans_core_features" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_plans_core_features_locales" (
  	"label" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_plans_advanced_features" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_plans_advanced_features_locales" (
  	"label" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_plans_assurances" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_plans_assurances_locales" (
  	"label" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_plans_compare_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"core_kind" "enum_pages_blocks_rd_plans_compare_rows_core_kind",
  	"advanced_kind" "enum_pages_blocks_rd_plans_compare_rows_advanced_kind"
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_plans_compare_rows_locales" (
  	"label" varchar NOT NULL,
  	"core_text" varchar,
  	"advanced_text" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_plans_compare" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_plans_compare_locales" (
  	"title" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_plans" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"core_cta_type" "enum_pages_blocks_rd_plans_core_cta_type" DEFAULT 'custom',
  	"core_cta_new_tab" boolean,
  	"advanced_cta_type" "enum_pages_blocks_rd_plans_advanced_cta_type" DEFAULT 'custom',
  	"advanced_cta_new_tab" boolean,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_plans_locales" (
  	"heading" varchar NOT NULL,
  	"intro" varchar,
  	"core_name" varchar NOT NULL,
  	"core_tagline" varchar,
  	"core_price" varchar,
  	"core_price_suffix" varchar,
  	"core_price_note" varchar,
  	"core_list_label" varchar,
  	"core_cta_url" varchar,
  	"core_cta_label" varchar,
  	"core_cta_note" varchar,
  	"advanced_badge" varchar,
  	"advanced_name" varchar NOT NULL,
  	"advanced_tagline" varchar,
  	"advanced_price" varchar,
  	"advanced_price_suffix" varchar,
  	"advanced_price_note" varchar,
  	"advanced_list_label" varchar,
  	"advanced_cta_url" varchar,
  	"advanced_cta_label" varchar,
  	"advanced_cta_note" varchar,
  	"compare_open_label" varchar,
  	"compare_close_label" varchar,
  	"compare_cta_core_url" varchar,
  	"compare_cta_core_label" varchar,
  	"compare_cta_advanced_url" varchar,
  	"compare_cta_advanced_label" varchar,
  	"compare_footnote" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_plans_core_features" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_plans_core_features_locales" (
  	"label" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_plans_advanced_features" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_plans_advanced_features_locales" (
  	"label" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_plans_assurances" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_plans_assurances_locales" (
  	"label" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_plans_compare_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"core_kind" "enum__pages_v_blocks_rd_plans_compare_rows_core_kind",
  	"advanced_kind" "enum__pages_v_blocks_rd_plans_compare_rows_advanced_kind",
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_plans_compare_rows_locales" (
  	"label" varchar NOT NULL,
  	"core_text" varchar,
  	"advanced_text" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_plans_compare" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_plans_compare_locales" (
  	"title" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_plans" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"core_cta_type" "enum__pages_v_blocks_rd_plans_core_cta_type" DEFAULT 'custom',
  	"core_cta_new_tab" boolean,
  	"advanced_cta_type" "enum__pages_v_blocks_rd_plans_advanced_cta_type" DEFAULT 'custom',
  	"advanced_cta_new_tab" boolean,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_plans_locales" (
  	"heading" varchar NOT NULL,
  	"intro" varchar,
  	"core_name" varchar NOT NULL,
  	"core_tagline" varchar,
  	"core_price" varchar,
  	"core_price_suffix" varchar,
  	"core_price_note" varchar,
  	"core_list_label" varchar,
  	"core_cta_url" varchar,
  	"core_cta_label" varchar,
  	"core_cta_note" varchar,
  	"advanced_badge" varchar,
  	"advanced_name" varchar NOT NULL,
  	"advanced_tagline" varchar,
  	"advanced_price" varchar,
  	"advanced_price_suffix" varchar,
  	"advanced_price_note" varchar,
  	"advanced_list_label" varchar,
  	"advanced_cta_url" varchar,
  	"advanced_cta_label" varchar,
  	"advanced_cta_note" varchar,
  	"compare_open_label" varchar,
  	"compare_close_label" varchar,
  	"compare_cta_core_url" varchar,
  	"compare_cta_core_label" varchar,
  	"compare_cta_advanced_url" varchar,
  	"compare_cta_advanced_label" varchar,
  	"compare_footnote" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_plans_core_features" ADD CONSTRAINT "pages_blocks_rd_plans_core_features_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_plans"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_plans_core_features_locales" ADD CONSTRAINT "pages_blocks_rd_plans_core_features_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_plans_core_features"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_plans_advanced_features" ADD CONSTRAINT "pages_blocks_rd_plans_advanced_features_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_plans"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_plans_advanced_features_locales" ADD CONSTRAINT "pages_blocks_rd_plans_advanced_features_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_plans_advanced_features"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_plans_assurances" ADD CONSTRAINT "pages_blocks_rd_plans_assurances_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_plans"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_plans_assurances_locales" ADD CONSTRAINT "pages_blocks_rd_plans_assurances_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_plans_assurances"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_plans_compare_rows" ADD CONSTRAINT "pages_blocks_rd_plans_compare_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_plans_compare"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_plans_compare_rows_locales" ADD CONSTRAINT "pages_blocks_rd_plans_compare_rows_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_plans_compare_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_plans_compare" ADD CONSTRAINT "pages_blocks_rd_plans_compare_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_plans"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_plans_compare_locales" ADD CONSTRAINT "pages_blocks_rd_plans_compare_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_plans_compare"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_plans" ADD CONSTRAINT "pages_blocks_rd_plans_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_plans_locales" ADD CONSTRAINT "pages_blocks_rd_plans_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_plans"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_plans_core_features" ADD CONSTRAINT "_pages_v_blocks_rd_plans_core_features_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_plans"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_plans_core_features_locales" ADD CONSTRAINT "_pages_v_blocks_rd_plans_core_features_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_plans_core_features"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_plans_advanced_features" ADD CONSTRAINT "_pages_v_blocks_rd_plans_advanced_features_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_plans"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_plans_advanced_features_locales" ADD CONSTRAINT "_pages_v_blocks_rd_plans_advanced_features_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_plans_advanced_features"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_plans_assurances" ADD CONSTRAINT "_pages_v_blocks_rd_plans_assurances_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_plans"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_plans_assurances_locales" ADD CONSTRAINT "_pages_v_blocks_rd_plans_assurances_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_plans_assurances"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_plans_compare_rows" ADD CONSTRAINT "_pages_v_blocks_rd_plans_compare_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_plans_compare"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_plans_compare_rows_locales" ADD CONSTRAINT "_pages_v_blocks_rd_plans_compare_rows_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_plans_compare_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_plans_compare" ADD CONSTRAINT "_pages_v_blocks_rd_plans_compare_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_plans"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_plans_compare_locales" ADD CONSTRAINT "_pages_v_blocks_rd_plans_compare_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_plans_compare"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_plans" ADD CONSTRAINT "_pages_v_blocks_rd_plans_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_plans_locales" ADD CONSTRAINT "_pages_v_blocks_rd_plans_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_plans"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_plans_core_features_order_idx" ON "pages_blocks_rd_plans_core_features" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_plans_core_features_parent_id_idx" ON "pages_blocks_rd_plans_core_features" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_plans_core_features_locales_locale_parent_id" ON "pages_blocks_rd_plans_core_features_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_plans_advanced_features_order_idx" ON "pages_blocks_rd_plans_advanced_features" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_plans_advanced_features_parent_id_idx" ON "pages_blocks_rd_plans_advanced_features" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_plans_advanced_features_locales_locale_paren" ON "pages_blocks_rd_plans_advanced_features_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_plans_assurances_order_idx" ON "pages_blocks_rd_plans_assurances" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_plans_assurances_parent_id_idx" ON "pages_blocks_rd_plans_assurances" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_plans_assurances_locales_locale_parent_id_un" ON "pages_blocks_rd_plans_assurances_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_plans_compare_rows_order_idx" ON "pages_blocks_rd_plans_compare_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_plans_compare_rows_parent_id_idx" ON "pages_blocks_rd_plans_compare_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_plans_compare_rows_locales_locale_parent_id_" ON "pages_blocks_rd_plans_compare_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_plans_compare_order_idx" ON "pages_blocks_rd_plans_compare" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_plans_compare_parent_id_idx" ON "pages_blocks_rd_plans_compare" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_plans_compare_locales_locale_parent_id_uniqu" ON "pages_blocks_rd_plans_compare_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_plans_order_idx" ON "pages_blocks_rd_plans" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_plans_parent_id_idx" ON "pages_blocks_rd_plans" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_plans_path_idx" ON "pages_blocks_rd_plans" USING btree ("_path");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_plans_locales_locale_parent_id_unique" ON "pages_blocks_rd_plans_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_core_features_order_idx" ON "_pages_v_blocks_rd_plans_core_features" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_core_features_parent_id_idx" ON "_pages_v_blocks_rd_plans_core_features" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_core_features_locales_locale_parent" ON "_pages_v_blocks_rd_plans_core_features_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_advanced_features_order_idx" ON "_pages_v_blocks_rd_plans_advanced_features" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_advanced_features_parent_id_idx" ON "_pages_v_blocks_rd_plans_advanced_features" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_advanced_features_locales_locale_pa" ON "_pages_v_blocks_rd_plans_advanced_features_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_assurances_order_idx" ON "_pages_v_blocks_rd_plans_assurances" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_assurances_parent_id_idx" ON "_pages_v_blocks_rd_plans_assurances" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_assurances_locales_locale_parent_id" ON "_pages_v_blocks_rd_plans_assurances_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_compare_rows_order_idx" ON "_pages_v_blocks_rd_plans_compare_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_compare_rows_parent_id_idx" ON "_pages_v_blocks_rd_plans_compare_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_compare_rows_locales_locale_parent_" ON "_pages_v_blocks_rd_plans_compare_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_compare_order_idx" ON "_pages_v_blocks_rd_plans_compare" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_compare_parent_id_idx" ON "_pages_v_blocks_rd_plans_compare" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_compare_locales_locale_parent_id_un" ON "_pages_v_blocks_rd_plans_compare_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_order_idx" ON "_pages_v_blocks_rd_plans" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_parent_id_idx" ON "_pages_v_blocks_rd_plans" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_path_idx" ON "_pages_v_blocks_rd_plans" USING btree ("_path");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_plans_locales_locale_parent_id_unique" ON "_pages_v_blocks_rd_plans_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_plans_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_plans" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_plans_compare_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_plans_compare" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_plans_compare_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_plans_compare_rows" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_plans_assurances_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_plans_assurances" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_plans_advanced_features_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_plans_advanced_features" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_plans_core_features_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_plans_core_features" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_plans_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_plans" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_plans_compare_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_plans_compare" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_plans_compare_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_plans_compare_rows" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_plans_assurances_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_plans_assurances" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_plans_advanced_features_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_plans_advanced_features" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_plans_core_features_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_plans_core_features" CASCADE;
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_plans_core_cta_type";
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_plans_advanced_cta_type";
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_plans_compare_rows_core_kind";
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_plans_compare_rows_advanced_kind";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_plans_core_cta_type";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_plans_advanced_cta_type";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_plans_compare_rows_core_kind";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_plans_compare_rows_advanced_kind";`)
}

