import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Add the `rdLbReading` block.
 *
 * GENERATED by tools/migrate_gen.py from the block's field schema — NOT by
 * `payload migrate:create`, whose snapshot in this repo is stale and emits DDL
 * for ~171 unrelated tables.
 *
 * Every statement is idempotent (IF NOT EXISTS / duplicate_object guards), so
 * it is safe to re-run over a partially applied attempt.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_inventory_species" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_inventory_species_locales" (
  	"name" varchar NOT NULL,
  	"value" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_analysis_passes" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_analysis_passes_locales" (
  	"number" varchar,
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_archetypes_teams" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"value" numeric
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_archetypes_ratios" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"value" numeric
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_archetypes_pillars" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"value" numeric
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_archetypes" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"score" numeric
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_archetypes_locales" (
  	"card_label" varchar NOT NULL,
  	"name" varchar NOT NULL,
  	"whats" varchar,
  	"focus" varchar,
  	"band" varchar,
  	"note" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_team_defs" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"low" numeric,
  	"high" numeric
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_team_defs_locales" (
  	"name" varchar NOT NULL,
  	"sub" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_ratio_defs" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_ratio_defs_locales" (
  	"name" varchar NOT NULL,
  	"bad" varchar,
  	"good" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_pillar_names" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_pillar_names_locales" (
  	"name" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_seals" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_seals_locales" (
  	"number" varchar NOT NULL,
  	"long" varchar,
  	"short" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"phone_logo_id" integer,
  	"phone_avatar_id" integer,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_lb_reading_locales" (
  	"heading" jsonb NOT NULL,
  	"intro" varchar,
  	"inventory_label" varchar,
  	"inventory_more_label" varchar,
  	"inventory_note" varchar,
  	"analysis_heading" varchar,
  	"analysis_intro" varchar,
  	"mechanisms_heading" varchar,
  	"mechanisms_intro" varchar,
  	"result_label" varchar,
  	"teams_tab_label" varchar,
  	"teams_tab_blurb" varchar,
  	"ratios_tab_label" varchar,
  	"ratios_tab_blurb" varchar,
  	"slider_labels_this_reading" varchar,
  	"slider_labels_healthy_prefix" varchar,
  	"slider_labels_in_range" varchar,
  	"slider_labels_over_range" varchar,
  	"slider_labels_under_range" varchar,
  	"focus_label" varchar,
  	"phone_time" varchar,
  	"phone_score_label" varchar,
  	"phone_out_of_label" varchar,
  	"phone_caption" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_inventory_species" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_inventory_species_locales" (
  	"name" varchar NOT NULL,
  	"value" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_analysis_passes" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_analysis_passes_locales" (
  	"number" varchar,
  	"title" varchar NOT NULL,
  	"body" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_teams" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"value" numeric,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_ratios" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"value" numeric,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_pillars" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"value" numeric,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_archetypes" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"score" numeric,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_locales" (
  	"card_label" varchar NOT NULL,
  	"name" varchar NOT NULL,
  	"whats" varchar,
  	"focus" varchar,
  	"band" varchar,
  	"note" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_team_defs" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"low" numeric,
  	"high" numeric,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_team_defs_locales" (
  	"name" varchar NOT NULL,
  	"sub" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_ratio_defs" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_ratio_defs_locales" (
  	"name" varchar NOT NULL,
  	"bad" varchar,
  	"good" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_pillar_names" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_pillar_names_locales" (
  	"name" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_seals" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_seals_locales" (
  	"number" varchar NOT NULL,
  	"long" varchar,
  	"short" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"phone_logo_id" integer,
  	"phone_avatar_id" integer,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_locales" (
  	"heading" jsonb NOT NULL,
  	"intro" varchar,
  	"inventory_label" varchar,
  	"inventory_more_label" varchar,
  	"inventory_note" varchar,
  	"analysis_heading" varchar,
  	"analysis_intro" varchar,
  	"mechanisms_heading" varchar,
  	"mechanisms_intro" varchar,
  	"result_label" varchar,
  	"teams_tab_label" varchar,
  	"teams_tab_blurb" varchar,
  	"ratios_tab_label" varchar,
  	"ratios_tab_blurb" varchar,
  	"slider_labels_this_reading" varchar,
  	"slider_labels_healthy_prefix" varchar,
  	"slider_labels_in_range" varchar,
  	"slider_labels_over_range" varchar,
  	"slider_labels_under_range" varchar,
  	"focus_label" varchar,
  	"phone_time" varchar,
  	"phone_score_label" varchar,
  	"phone_out_of_label" varchar,
  	"phone_caption" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_inventory_species" ADD CONSTRAINT "pages_blocks_rd_lb_reading_inventory_species_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_inventory_species_locales" ADD CONSTRAINT "pages_blocks_rd_lb_reading_inventory_species_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading_inventory_species"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_analysis_passes" ADD CONSTRAINT "pages_blocks_rd_lb_reading_analysis_passes_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_analysis_passes_locales" ADD CONSTRAINT "pages_blocks_rd_lb_reading_analysis_passes_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading_analysis_passes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_archetypes_teams" ADD CONSTRAINT "pages_blocks_rd_lb_reading_archetypes_teams_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading_archetypes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_archetypes_ratios" ADD CONSTRAINT "pages_blocks_rd_lb_reading_archetypes_ratios_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading_archetypes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_archetypes_pillars" ADD CONSTRAINT "pages_blocks_rd_lb_reading_archetypes_pillars_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading_archetypes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_archetypes" ADD CONSTRAINT "pages_blocks_rd_lb_reading_archetypes_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_archetypes_locales" ADD CONSTRAINT "pages_blocks_rd_lb_reading_archetypes_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading_archetypes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_team_defs" ADD CONSTRAINT "pages_blocks_rd_lb_reading_team_defs_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_team_defs_locales" ADD CONSTRAINT "pages_blocks_rd_lb_reading_team_defs_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading_team_defs"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_ratio_defs" ADD CONSTRAINT "pages_blocks_rd_lb_reading_ratio_defs_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_ratio_defs_locales" ADD CONSTRAINT "pages_blocks_rd_lb_reading_ratio_defs_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading_ratio_defs"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_pillar_names" ADD CONSTRAINT "pages_blocks_rd_lb_reading_pillar_names_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_pillar_names_locales" ADD CONSTRAINT "pages_blocks_rd_lb_reading_pillar_names_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading_pillar_names"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_seals" ADD CONSTRAINT "pages_blocks_rd_lb_reading_seals_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_seals_locales" ADD CONSTRAINT "pages_blocks_rd_lb_reading_seals_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading_seals"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading" ADD CONSTRAINT "pages_blocks_rd_lb_reading_phone_logo_id_media_id_fk" FOREIGN KEY ("phone_logo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading" ADD CONSTRAINT "pages_blocks_rd_lb_reading_phone_avatar_id_media_id_fk" FOREIGN KEY ("phone_avatar_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading" ADD CONSTRAINT "pages_blocks_rd_lb_reading_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_lb_reading_locales" ADD CONSTRAINT "pages_blocks_rd_lb_reading_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_inventory_species" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_inventory_species_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_inventory_species_locales" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_inventory_species_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading_inventory_species"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_analysis_passes" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_analysis_passes_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_analysis_passes_locales" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_analysis_passes_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading_analysis_passes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_archetypes_teams" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_archetypes_teams_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading_archetypes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_archetypes_ratios" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_archetypes_ratios_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading_archetypes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_archetypes_pillars" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_archetypes_pillars_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading_archetypes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_archetypes" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_archetypes_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_archetypes_locales" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_archetypes_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading_archetypes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_team_defs" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_team_defs_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_team_defs_locales" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_team_defs_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading_team_defs"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_ratio_defs" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_ratio_defs_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_ratio_defs_locales" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_ratio_defs_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading_ratio_defs"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_pillar_names" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_pillar_names_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_pillar_names_locales" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_pillar_names_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading_pillar_names"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_seals" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_seals_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_seals_locales" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_seals_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading_seals"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_phone_logo_id_media_id_fk" FOREIGN KEY ("phone_logo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_phone_avatar_id_media_id_fk" FOREIGN KEY ("phone_avatar_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_lb_reading_locales" ADD CONSTRAINT "_pages_v_blocks_rd_lb_reading_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_lb_reading"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_inventory_species_order_idx" ON "pages_blocks_rd_lb_reading_inventory_species" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_inventory_species_parent_id_idx" ON "pages_blocks_rd_lb_reading_inventory_species" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_inventory_species_locales_locale_" ON "pages_blocks_rd_lb_reading_inventory_species_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_analysis_passes_order_idx" ON "pages_blocks_rd_lb_reading_analysis_passes" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_analysis_passes_parent_id_idx" ON "pages_blocks_rd_lb_reading_analysis_passes" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_analysis_passes_locales_locale_pa" ON "pages_blocks_rd_lb_reading_analysis_passes_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_archetypes_teams_order_idx" ON "pages_blocks_rd_lb_reading_archetypes_teams" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_archetypes_teams_parent_id_idx" ON "pages_blocks_rd_lb_reading_archetypes_teams" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_archetypes_ratios_order_idx" ON "pages_blocks_rd_lb_reading_archetypes_ratios" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_archetypes_ratios_parent_id_idx" ON "pages_blocks_rd_lb_reading_archetypes_ratios" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_archetypes_pillars_order_idx" ON "pages_blocks_rd_lb_reading_archetypes_pillars" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_archetypes_pillars_parent_id_idx" ON "pages_blocks_rd_lb_reading_archetypes_pillars" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_archetypes_order_idx" ON "pages_blocks_rd_lb_reading_archetypes" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_archetypes_parent_id_idx" ON "pages_blocks_rd_lb_reading_archetypes" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_archetypes_locales_locale_parent_" ON "pages_blocks_rd_lb_reading_archetypes_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_team_defs_order_idx" ON "pages_blocks_rd_lb_reading_team_defs" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_team_defs_parent_id_idx" ON "pages_blocks_rd_lb_reading_team_defs" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_team_defs_locales_locale_parent_i" ON "pages_blocks_rd_lb_reading_team_defs_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_ratio_defs_order_idx" ON "pages_blocks_rd_lb_reading_ratio_defs" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_ratio_defs_parent_id_idx" ON "pages_blocks_rd_lb_reading_ratio_defs" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_ratio_defs_locales_locale_parent_" ON "pages_blocks_rd_lb_reading_ratio_defs_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_pillar_names_order_idx" ON "pages_blocks_rd_lb_reading_pillar_names" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_pillar_names_parent_id_idx" ON "pages_blocks_rd_lb_reading_pillar_names" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_pillar_names_locales_locale_paren" ON "pages_blocks_rd_lb_reading_pillar_names_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_seals_order_idx" ON "pages_blocks_rd_lb_reading_seals" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_seals_parent_id_idx" ON "pages_blocks_rd_lb_reading_seals" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_seals_locales_locale_parent_id_un" ON "pages_blocks_rd_lb_reading_seals_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_order_idx" ON "pages_blocks_rd_lb_reading" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_parent_id_idx" ON "pages_blocks_rd_lb_reading" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_path_idx" ON "pages_blocks_rd_lb_reading" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_phone_logo_idx" ON "pages_blocks_rd_lb_reading" USING btree ("phone_logo_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_phone_avatar_idx" ON "pages_blocks_rd_lb_reading" USING btree ("phone_avatar_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_lb_reading_locales_locale_parent_id_unique" ON "pages_blocks_rd_lb_reading_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_inventory_species_order_idx" ON "_pages_v_blocks_rd_lb_reading_inventory_species" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_inventory_species_parent_id_idx" ON "_pages_v_blocks_rd_lb_reading_inventory_species" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_inventory_species_locales_loca" ON "_pages_v_blocks_rd_lb_reading_inventory_species_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_analysis_passes_order_idx" ON "_pages_v_blocks_rd_lb_reading_analysis_passes" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_analysis_passes_parent_id_idx" ON "_pages_v_blocks_rd_lb_reading_analysis_passes" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_analysis_passes_locales_locale" ON "_pages_v_blocks_rd_lb_reading_analysis_passes_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_teams_order_idx" ON "_pages_v_blocks_rd_lb_reading_archetypes_teams" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_teams_parent_id_idx" ON "_pages_v_blocks_rd_lb_reading_archetypes_teams" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_ratios_order_idx" ON "_pages_v_blocks_rd_lb_reading_archetypes_ratios" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_ratios_parent_id_idx" ON "_pages_v_blocks_rd_lb_reading_archetypes_ratios" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_pillars_order_idx" ON "_pages_v_blocks_rd_lb_reading_archetypes_pillars" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_pillars_parent_id_idx" ON "_pages_v_blocks_rd_lb_reading_archetypes_pillars" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_order_idx" ON "_pages_v_blocks_rd_lb_reading_archetypes" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_parent_id_idx" ON "_pages_v_blocks_rd_lb_reading_archetypes" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_locales_locale_pare" ON "_pages_v_blocks_rd_lb_reading_archetypes_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_team_defs_order_idx" ON "_pages_v_blocks_rd_lb_reading_team_defs" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_team_defs_parent_id_idx" ON "_pages_v_blocks_rd_lb_reading_team_defs" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_team_defs_locales_locale_paren" ON "_pages_v_blocks_rd_lb_reading_team_defs_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_ratio_defs_order_idx" ON "_pages_v_blocks_rd_lb_reading_ratio_defs" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_ratio_defs_parent_id_idx" ON "_pages_v_blocks_rd_lb_reading_ratio_defs" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_ratio_defs_locales_locale_pare" ON "_pages_v_blocks_rd_lb_reading_ratio_defs_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_pillar_names_order_idx" ON "_pages_v_blocks_rd_lb_reading_pillar_names" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_pillar_names_parent_id_idx" ON "_pages_v_blocks_rd_lb_reading_pillar_names" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_pillar_names_locales_locale_pa" ON "_pages_v_blocks_rd_lb_reading_pillar_names_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_seals_order_idx" ON "_pages_v_blocks_rd_lb_reading_seals" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_seals_parent_id_idx" ON "_pages_v_blocks_rd_lb_reading_seals" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_seals_locales_locale_parent_id" ON "_pages_v_blocks_rd_lb_reading_seals_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_order_idx" ON "_pages_v_blocks_rd_lb_reading" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_parent_id_idx" ON "_pages_v_blocks_rd_lb_reading" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_path_idx" ON "_pages_v_blocks_rd_lb_reading" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_phone_logo_idx" ON "_pages_v_blocks_rd_lb_reading" USING btree ("phone_logo_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_phone_avatar_idx" ON "_pages_v_blocks_rd_lb_reading" USING btree ("phone_avatar_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_lb_reading_locales_locale_parent_id_uniqu" ON "_pages_v_blocks_rd_lb_reading_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_seals_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_seals" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_pillar_names_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_pillar_names" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_ratio_defs_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_ratio_defs" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_team_defs_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_team_defs" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_archetypes" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_pillars" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_ratios" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_archetypes_teams" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_analysis_passes_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_analysis_passes" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_inventory_species_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_lb_reading_inventory_species" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_seals_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_seals" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_pillar_names_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_pillar_names" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_ratio_defs_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_ratio_defs" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_team_defs_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_team_defs" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_archetypes_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_archetypes" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_archetypes_pillars" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_archetypes_ratios" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_archetypes_teams" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_analysis_passes_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_analysis_passes" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_inventory_species_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_lb_reading_inventory_species" CASCADE;`)
}

