import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Add the `rdOrder` block — the order page, step 1 of a three-step funnel.
 *
 * GENERATED by tools/migrate_gen.py from the block's field schema — NOT by
 * `payload migrate:create`, whose snapshot in this repo is stale and emits DDL
 * for ~171 unrelated tables.
 *
 * Every statement is idempotent (IF NOT EXISTS / duplicate_object guards), so
 * it is safe to re-run over a partially applied attempt. `up()` contains no
 * DROP of any kind: this block is additive and nothing that exists today is
 * touched, including every block the order funnel replaces.
 *
 * IDENTIFIER LENGTH. Postgres truncates an identifier at 63 BYTES, silently,
 * and two names that truncate to the same string make `CREATE TABLE IF NOT
 * EXISTS` skip a table that does not exist — which surfaces eighty statements
 * later as `column "_locale" does not exist`. That is exactly how the rdLegal
 * migration failed. migrate_gen.py refuses to emit until every identifier is
 * checked, and it refused this schema twice: `plans.cards.summaryBenefits`
 * produced a 71-byte foreign key. It is `plans.cards.ticks` now.
 */

/**
 * Add the `rdOrder` block.
 *
 * GENERATED by tools/migrate_gen.py from the block's field schema — NOT by
 * `payload migrate:create`, whose snapshot in this repo is stale and emits DDL
 * for ~171 unrelated tables.
 *
 * Every statement is idempotent (IF NOT EXISTS / duplicate_object guards), so
 * it is safe to re-run over a partially applied attempt.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_order_plans_cards_key" AS ENUM('core', 'advanced');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_order_cost_rows_variant" AS ENUM('row', 'sum', 'advancedOnly');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_order_plans_cards_key" AS ENUM('core', 'advanced');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_order_cost_rows_variant" AS ENUM('row', 'sum', 'advancedOnly');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_steps_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_steps_items_locales" (
  	"label" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_plans_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_plans_items_locales" (
  	"label" varchar NOT NULL,
  	"price" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_plans_cards_ticks" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_plans_cards_ticks_locales" (
  	"label" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_plans_cards_feats" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_plans_cards_feats_locales" (
  	"text" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_plans_cards" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"key" "enum_pages_blocks_rd_order_plans_cards_key" NOT NULL,
  	"icon_id" integer,
  	"icon2_id" integer
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_plans_cards_locales" (
  	"badge" varchar,
  	"name" varchar NOT NULL,
  	"meta" varchar,
  	"per_label" varchar,
  	"seeded_price" varchar,
  	"eyebrow" varchar,
  	"foot" varchar,
  	"blurb" varchar,
  	"retest_note" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_cost_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"variant" "enum_pages_blocks_rd_order_cost_rows_variant",
  	"soft_value" boolean
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_cost_rows_locales" (
  	"label" varchar NOT NULL,
  	"detail" varchar,
  	"value" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_cost_how_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_cost_how_rows_locales" (
  	"label" varchar NOT NULL,
  	"detail" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_timeline_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"is_payment" boolean,
  	"is_retest" boolean
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_timeline_rows_locales" (
  	"week" varchar NOT NULL,
  	"title" varchar,
  	"detail" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_timeline_changes" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"from" numeric,
  	"to" numeric
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_timeline_changes_locales" (
  	"label" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_faq_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"open_by_default" boolean
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_faq_rows_locales" (
  	"q" varchar NOT NULL,
  	"a" jsonb,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_faq_stories" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"image_id" integer
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_faq_stories_locales" (
  	"name" varchar NOT NULL,
  	"quote" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"steps_logo_id" integer,
  	"proof_portrait_id" integer,
  	"proof_image_id" integer,
  	"cost_aside_image_id" integer,
  	"cost_figure_image_id" integer,
  	"timeline_figure_image_id" integer,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_order_locales" (
  	"steps_logo_alt" varchar,
  	"steps_home_slug" varchar,
  	"steps_back_label" varchar,
  	"hero_heading" varchar NOT NULL,
  	"hero_intro" varchar,
  	"proof_quote" varchar,
  	"proof_attribution" varchar,
  	"proof_attribution_note" varchar,
  	"proof_reveal_label" varchar,
  	"proof_caption" varchar,
  	"plans_heading" varchar,
  	"plans_subheading" varchar,
  	"plans_was_price" varchar,
  	"plans_now_price" varchar,
  	"plans_note_heading" varchar,
  	"plans_note" varchar,
  	"plans_trust_label" varchar,
  	"plans_trust_name" varchar,
  	"cost_heading" varchar,
  	"cost_intro" varchar,
  	"cost_column_label" varchar,
  	"cost_how_label" varchar,
  	"cost_how_label_open" varchar,
  	"cost_note" varchar,
  	"cost_aside_brand" varchar,
  	"cost_aside_per_month" varchar,
  	"cost_aside_name" varchar,
  	"cost_aside_note" varchar,
  	"cost_figure_name" varchar,
  	"cost_figure_note" varchar,
  	"cost_figure_quote" varchar,
  	"timeline_heading" varchar,
  	"timeline_note" varchar,
  	"timeline_changes_heading" varchar,
  	"timeline_score_value" varchar,
  	"timeline_score_label" varchar,
  	"timeline_score_delta" varchar,
  	"timeline_score_source" varchar,
  	"timeline_scale_min" varchar,
  	"timeline_scale_max" varchar,
  	"timeline_bars_label" varchar,
  	"timeline_figure_quote" varchar,
  	"timeline_figure_attribution" varchar,
  	"timeline_advanced_badge" varchar,
  	"timeline_advanced_cadence" varchar,
  	"timeline_advanced_note" varchar,
  	"timeline_advanced_lead" varchar,
  	"faq_heading" varchar,
  	"faq_closing_heading" varchar,
  	"faq_closing_body" varchar,
  	"sticky_selected_prefix" varchar,
  	"sticky_selected_suffix" varchar,
  	"sticky_switch_label" varchar,
  	"sticky_note" varchar,
  	"sticky_cta_prefix" varchar,
  	"sticky_next_slug_core" varchar,
  	"sticky_next_slug_advanced" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_steps_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_steps_items_locales" (
  	"label" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_plans_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_plans_items_locales" (
  	"label" varchar NOT NULL,
  	"price" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_ticks" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_ticks_locales" (
  	"label" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_feats" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_feats_locales" (
  	"text" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"key" "enum__pages_v_blocks_rd_order_plans_cards_key" NOT NULL,
  	"icon_id" integer,
  	"icon2_id" integer,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_locales" (
  	"badge" varchar,
  	"name" varchar NOT NULL,
  	"meta" varchar,
  	"per_label" varchar,
  	"seeded_price" varchar,
  	"eyebrow" varchar,
  	"foot" varchar,
  	"blurb" varchar,
  	"retest_note" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_cost_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"variant" "enum__pages_v_blocks_rd_order_cost_rows_variant",
  	"soft_value" boolean,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_cost_rows_locales" (
  	"label" varchar NOT NULL,
  	"detail" varchar,
  	"value" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_cost_how_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_cost_how_rows_locales" (
  	"label" varchar NOT NULL,
  	"detail" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_timeline_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"is_payment" boolean,
  	"is_retest" boolean,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_timeline_rows_locales" (
  	"week" varchar NOT NULL,
  	"title" varchar,
  	"detail" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_timeline_changes" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"from" numeric,
  	"to" numeric,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_timeline_changes_locales" (
  	"label" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_faq_rows" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"open_by_default" boolean,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_faq_rows_locales" (
  	"q" varchar NOT NULL,
  	"a" jsonb,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_faq_stories" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"image_id" integer,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_faq_stories_locales" (
  	"name" varchar NOT NULL,
  	"quote" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"steps_logo_id" integer,
  	"proof_portrait_id" integer,
  	"proof_image_id" integer,
  	"cost_aside_image_id" integer,
  	"cost_figure_image_id" integer,
  	"timeline_figure_image_id" integer,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_order_locales" (
  	"steps_logo_alt" varchar,
  	"steps_home_slug" varchar,
  	"steps_back_label" varchar,
  	"hero_heading" varchar NOT NULL,
  	"hero_intro" varchar,
  	"proof_quote" varchar,
  	"proof_attribution" varchar,
  	"proof_attribution_note" varchar,
  	"proof_reveal_label" varchar,
  	"proof_caption" varchar,
  	"plans_heading" varchar,
  	"plans_subheading" varchar,
  	"plans_was_price" varchar,
  	"plans_now_price" varchar,
  	"plans_note_heading" varchar,
  	"plans_note" varchar,
  	"plans_trust_label" varchar,
  	"plans_trust_name" varchar,
  	"cost_heading" varchar,
  	"cost_intro" varchar,
  	"cost_column_label" varchar,
  	"cost_how_label" varchar,
  	"cost_how_label_open" varchar,
  	"cost_note" varchar,
  	"cost_aside_brand" varchar,
  	"cost_aside_per_month" varchar,
  	"cost_aside_name" varchar,
  	"cost_aside_note" varchar,
  	"cost_figure_name" varchar,
  	"cost_figure_note" varchar,
  	"cost_figure_quote" varchar,
  	"timeline_heading" varchar,
  	"timeline_note" varchar,
  	"timeline_changes_heading" varchar,
  	"timeline_score_value" varchar,
  	"timeline_score_label" varchar,
  	"timeline_score_delta" varchar,
  	"timeline_score_source" varchar,
  	"timeline_scale_min" varchar,
  	"timeline_scale_max" varchar,
  	"timeline_bars_label" varchar,
  	"timeline_figure_quote" varchar,
  	"timeline_figure_attribution" varchar,
  	"timeline_advanced_badge" varchar,
  	"timeline_advanced_cadence" varchar,
  	"timeline_advanced_note" varchar,
  	"timeline_advanced_lead" varchar,
  	"faq_heading" varchar,
  	"faq_closing_heading" varchar,
  	"faq_closing_body" varchar,
  	"sticky_selected_prefix" varchar,
  	"sticky_selected_suffix" varchar,
  	"sticky_switch_label" varchar,
  	"sticky_note" varchar,
  	"sticky_cta_prefix" varchar,
  	"sticky_next_slug_core" varchar,
  	"sticky_next_slug_advanced" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_steps_items" ADD CONSTRAINT "pages_blocks_rd_order_steps_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_steps_items_locales" ADD CONSTRAINT "pages_blocks_rd_order_steps_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order_steps_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_plans_items" ADD CONSTRAINT "pages_blocks_rd_order_plans_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_plans_items_locales" ADD CONSTRAINT "pages_blocks_rd_order_plans_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order_plans_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_plans_cards_ticks" ADD CONSTRAINT "pages_blocks_rd_order_plans_cards_ticks_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order_plans_cards"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_plans_cards_ticks_locales" ADD CONSTRAINT "pages_blocks_rd_order_plans_cards_ticks_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order_plans_cards_ticks"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_plans_cards_feats" ADD CONSTRAINT "pages_blocks_rd_order_plans_cards_feats_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order_plans_cards"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_plans_cards_feats_locales" ADD CONSTRAINT "pages_blocks_rd_order_plans_cards_feats_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order_plans_cards_feats"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_plans_cards" ADD CONSTRAINT "pages_blocks_rd_order_plans_cards_icon_id_media_id_fk" FOREIGN KEY ("icon_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_plans_cards" ADD CONSTRAINT "pages_blocks_rd_order_plans_cards_icon2_id_media_id_fk" FOREIGN KEY ("icon2_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_plans_cards" ADD CONSTRAINT "pages_blocks_rd_order_plans_cards_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_plans_cards_locales" ADD CONSTRAINT "pages_blocks_rd_order_plans_cards_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order_plans_cards"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_cost_rows" ADD CONSTRAINT "pages_blocks_rd_order_cost_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_cost_rows_locales" ADD CONSTRAINT "pages_blocks_rd_order_cost_rows_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order_cost_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_cost_how_rows" ADD CONSTRAINT "pages_blocks_rd_order_cost_how_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_cost_how_rows_locales" ADD CONSTRAINT "pages_blocks_rd_order_cost_how_rows_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order_cost_how_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_timeline_rows" ADD CONSTRAINT "pages_blocks_rd_order_timeline_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_timeline_rows_locales" ADD CONSTRAINT "pages_blocks_rd_order_timeline_rows_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order_timeline_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_timeline_changes" ADD CONSTRAINT "pages_blocks_rd_order_timeline_changes_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_timeline_changes_locales" ADD CONSTRAINT "pages_blocks_rd_order_timeline_changes_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order_timeline_changes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_faq_rows" ADD CONSTRAINT "pages_blocks_rd_order_faq_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_faq_rows_locales" ADD CONSTRAINT "pages_blocks_rd_order_faq_rows_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order_faq_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_faq_stories" ADD CONSTRAINT "pages_blocks_rd_order_faq_stories_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_faq_stories" ADD CONSTRAINT "pages_blocks_rd_order_faq_stories_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_faq_stories_locales" ADD CONSTRAINT "pages_blocks_rd_order_faq_stories_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order_faq_stories"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order" ADD CONSTRAINT "pages_blocks_rd_order_steps_logo_id_media_id_fk" FOREIGN KEY ("steps_logo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order" ADD CONSTRAINT "pages_blocks_rd_order_proof_portrait_id_media_id_fk" FOREIGN KEY ("proof_portrait_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order" ADD CONSTRAINT "pages_blocks_rd_order_proof_image_id_media_id_fk" FOREIGN KEY ("proof_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order" ADD CONSTRAINT "pages_blocks_rd_order_cost_aside_image_id_media_id_fk" FOREIGN KEY ("cost_aside_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order" ADD CONSTRAINT "pages_blocks_rd_order_cost_figure_image_id_media_id_fk" FOREIGN KEY ("cost_figure_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order" ADD CONSTRAINT "pages_blocks_rd_order_timeline_figure_image_id_media_id_fk" FOREIGN KEY ("timeline_figure_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order" ADD CONSTRAINT "pages_blocks_rd_order_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_order_locales" ADD CONSTRAINT "pages_blocks_rd_order_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_steps_items" ADD CONSTRAINT "_pages_v_blocks_rd_order_steps_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_steps_items_locales" ADD CONSTRAINT "_pages_v_blocks_rd_order_steps_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order_steps_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_plans_items" ADD CONSTRAINT "_pages_v_blocks_rd_order_plans_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_plans_items_locales" ADD CONSTRAINT "_pages_v_blocks_rd_order_plans_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order_plans_items"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_plans_cards_ticks" ADD CONSTRAINT "_pages_v_blocks_rd_order_plans_cards_ticks_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order_plans_cards"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_plans_cards_ticks_locales" ADD CONSTRAINT "_pages_v_blocks_rd_order_plans_cards_ticks_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order_plans_cards_ticks"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_plans_cards_feats" ADD CONSTRAINT "_pages_v_blocks_rd_order_plans_cards_feats_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order_plans_cards"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_plans_cards_feats_locales" ADD CONSTRAINT "_pages_v_blocks_rd_order_plans_cards_feats_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order_plans_cards_feats"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_plans_cards" ADD CONSTRAINT "_pages_v_blocks_rd_order_plans_cards_icon_id_media_id_fk" FOREIGN KEY ("icon_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_plans_cards" ADD CONSTRAINT "_pages_v_blocks_rd_order_plans_cards_icon2_id_media_id_fk" FOREIGN KEY ("icon2_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_plans_cards" ADD CONSTRAINT "_pages_v_blocks_rd_order_plans_cards_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_plans_cards_locales" ADD CONSTRAINT "_pages_v_blocks_rd_order_plans_cards_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order_plans_cards"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_cost_rows" ADD CONSTRAINT "_pages_v_blocks_rd_order_cost_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_cost_rows_locales" ADD CONSTRAINT "_pages_v_blocks_rd_order_cost_rows_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order_cost_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_cost_how_rows" ADD CONSTRAINT "_pages_v_blocks_rd_order_cost_how_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_cost_how_rows_locales" ADD CONSTRAINT "_pages_v_blocks_rd_order_cost_how_rows_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order_cost_how_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_timeline_rows" ADD CONSTRAINT "_pages_v_blocks_rd_order_timeline_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_timeline_rows_locales" ADD CONSTRAINT "_pages_v_blocks_rd_order_timeline_rows_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order_timeline_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_timeline_changes" ADD CONSTRAINT "_pages_v_blocks_rd_order_timeline_changes_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_timeline_changes_locales" ADD CONSTRAINT "_pages_v_blocks_rd_order_timeline_changes_locales_parent_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order_timeline_changes"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_faq_rows" ADD CONSTRAINT "_pages_v_blocks_rd_order_faq_rows_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_faq_rows_locales" ADD CONSTRAINT "_pages_v_blocks_rd_order_faq_rows_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order_faq_rows"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_faq_stories" ADD CONSTRAINT "_pages_v_blocks_rd_order_faq_stories_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_faq_stories" ADD CONSTRAINT "_pages_v_blocks_rd_order_faq_stories_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_faq_stories_locales" ADD CONSTRAINT "_pages_v_blocks_rd_order_faq_stories_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order_faq_stories"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order" ADD CONSTRAINT "_pages_v_blocks_rd_order_steps_logo_id_media_id_fk" FOREIGN KEY ("steps_logo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order" ADD CONSTRAINT "_pages_v_blocks_rd_order_proof_portrait_id_media_id_fk" FOREIGN KEY ("proof_portrait_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order" ADD CONSTRAINT "_pages_v_blocks_rd_order_proof_image_id_media_id_fk" FOREIGN KEY ("proof_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order" ADD CONSTRAINT "_pages_v_blocks_rd_order_cost_aside_image_id_media_id_fk" FOREIGN KEY ("cost_aside_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order" ADD CONSTRAINT "_pages_v_blocks_rd_order_cost_figure_image_id_media_id_fk" FOREIGN KEY ("cost_figure_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order" ADD CONSTRAINT "_pages_v_blocks_rd_order_timeline_figure_image_id_media_id_fk" FOREIGN KEY ("timeline_figure_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order" ADD CONSTRAINT "_pages_v_blocks_rd_order_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_order_locales" ADD CONSTRAINT "_pages_v_blocks_rd_order_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_order"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_steps_items_order_idx" ON "pages_blocks_rd_order_steps_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_steps_items_parent_id_idx" ON "pages_blocks_rd_order_steps_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_order_steps_items_locales_locale_parent_id_u" ON "pages_blocks_rd_order_steps_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_plans_items_order_idx" ON "pages_blocks_rd_order_plans_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_plans_items_parent_id_idx" ON "pages_blocks_rd_order_plans_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_order_plans_items_locales_locale_parent_id_u" ON "pages_blocks_rd_order_plans_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_plans_cards_ticks_order_idx" ON "pages_blocks_rd_order_plans_cards_ticks" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_plans_cards_ticks_parent_id_idx" ON "pages_blocks_rd_order_plans_cards_ticks" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_order_plans_cards_ticks_locales_locale_paren" ON "pages_blocks_rd_order_plans_cards_ticks_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_plans_cards_feats_order_idx" ON "pages_blocks_rd_order_plans_cards_feats" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_plans_cards_feats_parent_id_idx" ON "pages_blocks_rd_order_plans_cards_feats" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_order_plans_cards_feats_locales_locale_paren" ON "pages_blocks_rd_order_plans_cards_feats_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_plans_cards_order_idx" ON "pages_blocks_rd_order_plans_cards" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_plans_cards_parent_id_idx" ON "pages_blocks_rd_order_plans_cards" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_plans_cards_icon_idx" ON "pages_blocks_rd_order_plans_cards" USING btree ("icon_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_plans_cards_icon2_idx" ON "pages_blocks_rd_order_plans_cards" USING btree ("icon2_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_order_plans_cards_locales_locale_parent_id_u" ON "pages_blocks_rd_order_plans_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_cost_rows_order_idx" ON "pages_blocks_rd_order_cost_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_cost_rows_parent_id_idx" ON "pages_blocks_rd_order_cost_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_order_cost_rows_locales_locale_parent_id_uni" ON "pages_blocks_rd_order_cost_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_cost_how_rows_order_idx" ON "pages_blocks_rd_order_cost_how_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_cost_how_rows_parent_id_idx" ON "pages_blocks_rd_order_cost_how_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_order_cost_how_rows_locales_locale_parent_id" ON "pages_blocks_rd_order_cost_how_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_timeline_rows_order_idx" ON "pages_blocks_rd_order_timeline_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_timeline_rows_parent_id_idx" ON "pages_blocks_rd_order_timeline_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_order_timeline_rows_locales_locale_parent_id" ON "pages_blocks_rd_order_timeline_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_timeline_changes_order_idx" ON "pages_blocks_rd_order_timeline_changes" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_timeline_changes_parent_id_idx" ON "pages_blocks_rd_order_timeline_changes" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_order_timeline_changes_locales_locale_parent" ON "pages_blocks_rd_order_timeline_changes_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_faq_rows_order_idx" ON "pages_blocks_rd_order_faq_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_faq_rows_parent_id_idx" ON "pages_blocks_rd_order_faq_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_order_faq_rows_locales_locale_parent_id_uniq" ON "pages_blocks_rd_order_faq_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_faq_stories_order_idx" ON "pages_blocks_rd_order_faq_stories" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_faq_stories_parent_id_idx" ON "pages_blocks_rd_order_faq_stories" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_faq_stories_image_idx" ON "pages_blocks_rd_order_faq_stories" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_order_faq_stories_locales_locale_parent_id_u" ON "pages_blocks_rd_order_faq_stories_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_order_idx" ON "pages_blocks_rd_order" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_parent_id_idx" ON "pages_blocks_rd_order" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_path_idx" ON "pages_blocks_rd_order" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_steps_logo_idx" ON "pages_blocks_rd_order" USING btree ("steps_logo_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_proof_portrait_idx" ON "pages_blocks_rd_order" USING btree ("proof_portrait_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_proof_image_idx" ON "pages_blocks_rd_order" USING btree ("proof_image_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_cost_aside_image_idx" ON "pages_blocks_rd_order" USING btree ("cost_aside_image_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_cost_figure_image_idx" ON "pages_blocks_rd_order" USING btree ("cost_figure_image_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_order_timeline_figure_image_idx" ON "pages_blocks_rd_order" USING btree ("timeline_figure_image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_order_locales_locale_parent_id_unique" ON "pages_blocks_rd_order_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_steps_items_order_idx" ON "_pages_v_blocks_rd_order_steps_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_steps_items_parent_id_idx" ON "_pages_v_blocks_rd_order_steps_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_steps_items_locales_locale_parent_i" ON "_pages_v_blocks_rd_order_steps_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_plans_items_order_idx" ON "_pages_v_blocks_rd_order_plans_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_plans_items_parent_id_idx" ON "_pages_v_blocks_rd_order_plans_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_plans_items_locales_locale_parent_i" ON "_pages_v_blocks_rd_order_plans_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_ticks_order_idx" ON "_pages_v_blocks_rd_order_plans_cards_ticks" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_ticks_parent_id_idx" ON "_pages_v_blocks_rd_order_plans_cards_ticks" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_ticks_locales_locale_pa" ON "_pages_v_blocks_rd_order_plans_cards_ticks_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_feats_order_idx" ON "_pages_v_blocks_rd_order_plans_cards_feats" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_feats_parent_id_idx" ON "_pages_v_blocks_rd_order_plans_cards_feats" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_feats_locales_locale_pa" ON "_pages_v_blocks_rd_order_plans_cards_feats_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_order_idx" ON "_pages_v_blocks_rd_order_plans_cards" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_parent_id_idx" ON "_pages_v_blocks_rd_order_plans_cards" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_icon_idx" ON "_pages_v_blocks_rd_order_plans_cards" USING btree ("icon_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_icon2_idx" ON "_pages_v_blocks_rd_order_plans_cards" USING btree ("icon2_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_plans_cards_locales_locale_parent_i" ON "_pages_v_blocks_rd_order_plans_cards_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_cost_rows_order_idx" ON "_pages_v_blocks_rd_order_cost_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_cost_rows_parent_id_idx" ON "_pages_v_blocks_rd_order_cost_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_cost_rows_locales_locale_parent_id_" ON "_pages_v_blocks_rd_order_cost_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_cost_how_rows_order_idx" ON "_pages_v_blocks_rd_order_cost_how_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_cost_how_rows_parent_id_idx" ON "_pages_v_blocks_rd_order_cost_how_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_cost_how_rows_locales_locale_parent" ON "_pages_v_blocks_rd_order_cost_how_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_timeline_rows_order_idx" ON "_pages_v_blocks_rd_order_timeline_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_timeline_rows_parent_id_idx" ON "_pages_v_blocks_rd_order_timeline_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_timeline_rows_locales_locale_parent" ON "_pages_v_blocks_rd_order_timeline_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_timeline_changes_order_idx" ON "_pages_v_blocks_rd_order_timeline_changes" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_timeline_changes_parent_id_idx" ON "_pages_v_blocks_rd_order_timeline_changes" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_timeline_changes_locales_locale_par" ON "_pages_v_blocks_rd_order_timeline_changes_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_faq_rows_order_idx" ON "_pages_v_blocks_rd_order_faq_rows" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_faq_rows_parent_id_idx" ON "_pages_v_blocks_rd_order_faq_rows" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_faq_rows_locales_locale_parent_id_u" ON "_pages_v_blocks_rd_order_faq_rows_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_faq_stories_order_idx" ON "_pages_v_blocks_rd_order_faq_stories" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_faq_stories_parent_id_idx" ON "_pages_v_blocks_rd_order_faq_stories" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_faq_stories_image_idx" ON "_pages_v_blocks_rd_order_faq_stories" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_faq_stories_locales_locale_parent_i" ON "_pages_v_blocks_rd_order_faq_stories_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_order_idx" ON "_pages_v_blocks_rd_order" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_parent_id_idx" ON "_pages_v_blocks_rd_order" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_path_idx" ON "_pages_v_blocks_rd_order" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_steps_logo_idx" ON "_pages_v_blocks_rd_order" USING btree ("steps_logo_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_proof_portrait_idx" ON "_pages_v_blocks_rd_order" USING btree ("proof_portrait_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_proof_image_idx" ON "_pages_v_blocks_rd_order" USING btree ("proof_image_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_cost_aside_image_idx" ON "_pages_v_blocks_rd_order" USING btree ("cost_aside_image_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_cost_figure_image_idx" ON "_pages_v_blocks_rd_order" USING btree ("cost_figure_image_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_timeline_figure_image_idx" ON "_pages_v_blocks_rd_order" USING btree ("timeline_figure_image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_order_locales_locale_parent_id_unique" ON "_pages_v_blocks_rd_order_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_faq_stories_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_faq_stories" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_faq_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_faq_rows" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_timeline_changes_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_timeline_changes" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_timeline_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_timeline_rows" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_cost_how_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_cost_how_rows" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_cost_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_cost_rows" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_plans_cards_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_plans_cards" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_plans_cards_feats_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_plans_cards_feats" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_plans_cards_ticks_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_plans_cards_ticks" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_plans_items_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_plans_items" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_steps_items_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_order_steps_items" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_faq_stories_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_faq_stories" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_faq_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_faq_rows" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_timeline_changes_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_timeline_changes" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_timeline_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_timeline_rows" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_cost_how_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_cost_how_rows" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_cost_rows_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_cost_rows" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_plans_cards_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_plans_cards" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_plans_cards_feats_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_plans_cards_feats" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_plans_cards_ticks_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_plans_cards_ticks" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_plans_items_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_plans_items" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_steps_items_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_order_steps_items" CASCADE;
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_order_plans_cards_key";
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_order_cost_rows_variant";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_order_plans_cards_key";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_order_cost_rows_variant";`)
}

