import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

// Generated by `migrate:create`, then EDITED BY HAND to remove the `hubs`
// statements.
//
// WHY IT NEEDED EDITING
//
// `migrate:create` diffs the config against the last schema SNAPSHOT (.json),
// not against the database. The two hubs migrations before this one were
// hand-written, and a hand-written migration updates neither the snapshot nor
// drizzle's idea of the world — so the generator still believed `hubs` did not
// exist and emitted CREATE TABLE for it alongside the pillars tables. Running it
// failed on `relation "hubs" already exists`, with the pillars tables never
// reached.
//
// Everything hubs-related has been stripped: the enum, both tables, their FKs
// and indexes, and the `payload_locked_documents_rels.hubs_id` column. All of it
// is already in the database from 20260825_120000_hubs and
// 20260825_130000_hubs_locked_documents_rel. What remains is pillars only, plus
// the `pillars_id` column on the locked-documents join table.
//
// The lesson for next time: hand-written migrations leave the snapshot behind,
// and the next generated migration inherits that gap. Either generate every
// migration, or run `db:resync-snapshot` after hand-writing one.

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE TYPE "public"."enum_pillars_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__pillars_v_published_locale" AS ENUM('en', 'de', 'fr', 'nl', 'ch', 'be', 'uk', 'uae');
  CREATE TYPE "public"."enum__pillars_v_version_status" AS ENUM('draft', 'published');
  
  CREATE TABLE "pillars_faq" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"question" varchar,
  	"answer" varchar
  );
  
  CREATE TABLE "pillars_references" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"text" varchar,
  	"url" varchar
  );
  
  CREATE TABLE "pillars" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"hub_id" integer,
  	"hero_image_id" integer,
  	"reviewer_id" integer,
  	"published_at" timestamp(3) with time zone,
  	"noindex" boolean DEFAULT false,
  	"external_id" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "pillars_locales" (
  	"title" varchar,
  	"slug" varchar,
  	"standfirst" varchar,
  	"content" jsonb,
  	"_status" "enum_pillars_status" DEFAULT 'draft',
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  
  CREATE TABLE "pillars_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"authors_id" integer,
  	"pillars_id" integer
  );
  
  CREATE TABLE "_pillars_v_version_faq" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"question" varchar,
  	"answer" varchar,
  	"_uuid" varchar
  );
  
  CREATE TABLE "_pillars_v_version_references" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"text" varchar,
  	"url" varchar,
  	"_uuid" varchar
  );
  
  CREATE TABLE "_pillars_v" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"parent_id" integer,
  	"version_hub_id" integer,
  	"version_hero_image_id" integer,
  	"version_reviewer_id" integer,
  	"version_published_at" timestamp(3) with time zone,
  	"version_noindex" boolean DEFAULT false,
  	"version_external_id" varchar,
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"snapshot" boolean,
  	"published_locale" "enum__pillars_v_published_locale",
  	"latest" boolean
  );
  
  CREATE TABLE "_pillars_v_locales" (
  	"version_title" varchar,
  	"version_slug" varchar,
  	"version_standfirst" varchar,
  	"version_content" jsonb,
  	"version__status" "enum__pillars_v_version_status" DEFAULT 'draft',
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  
  CREATE TABLE "_pillars_v_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"authors_id" integer,
  	"pillars_id" integer
  );
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "pillars_id" integer;
  ALTER TABLE "pillars_faq" ADD CONSTRAINT "pillars_faq_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pillars"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "pillars_references" ADD CONSTRAINT "pillars_references_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pillars"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "pillars" ADD CONSTRAINT "pillars_hub_id_hubs_id_fk" FOREIGN KEY ("hub_id") REFERENCES "public"."hubs"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pillars" ADD CONSTRAINT "pillars_hero_image_id_media_id_fk" FOREIGN KEY ("hero_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pillars" ADD CONSTRAINT "pillars_reviewer_id_authors_id_fk" FOREIGN KEY ("reviewer_id") REFERENCES "public"."authors"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pillars_locales" ADD CONSTRAINT "pillars_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pillars"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "pillars_rels" ADD CONSTRAINT "pillars_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."pillars"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "pillars_rels" ADD CONSTRAINT "pillars_rels_authors_fk" FOREIGN KEY ("authors_id") REFERENCES "public"."authors"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "pillars_rels" ADD CONSTRAINT "pillars_rels_pillars_fk" FOREIGN KEY ("pillars_id") REFERENCES "public"."pillars"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pillars_v_version_faq" ADD CONSTRAINT "_pillars_v_version_faq_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pillars_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pillars_v_version_references" ADD CONSTRAINT "_pillars_v_version_references_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pillars_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pillars_v" ADD CONSTRAINT "_pillars_v_parent_id_pillars_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."pillars"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pillars_v" ADD CONSTRAINT "_pillars_v_version_hub_id_hubs_id_fk" FOREIGN KEY ("version_hub_id") REFERENCES "public"."hubs"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pillars_v" ADD CONSTRAINT "_pillars_v_version_hero_image_id_media_id_fk" FOREIGN KEY ("version_hero_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pillars_v" ADD CONSTRAINT "_pillars_v_version_reviewer_id_authors_id_fk" FOREIGN KEY ("version_reviewer_id") REFERENCES "public"."authors"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pillars_v_locales" ADD CONSTRAINT "_pillars_v_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pillars_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pillars_v_rels" ADD CONSTRAINT "_pillars_v_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."_pillars_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pillars_v_rels" ADD CONSTRAINT "_pillars_v_rels_authors_fk" FOREIGN KEY ("authors_id") REFERENCES "public"."authors"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pillars_v_rels" ADD CONSTRAINT "_pillars_v_rels_pillars_fk" FOREIGN KEY ("pillars_id") REFERENCES "public"."pillars"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "pillars_faq_order_idx" ON "pillars_faq" USING btree ("_order");
  CREATE INDEX "pillars_faq_parent_id_idx" ON "pillars_faq" USING btree ("_parent_id");
  CREATE INDEX "pillars_faq_locale_idx" ON "pillars_faq" USING btree ("_locale");
  CREATE INDEX "pillars_references_order_idx" ON "pillars_references" USING btree ("_order");
  CREATE INDEX "pillars_references_parent_id_idx" ON "pillars_references" USING btree ("_parent_id");
  CREATE INDEX "pillars_references_locale_idx" ON "pillars_references" USING btree ("_locale");
  CREATE INDEX "pillars_hub_idx" ON "pillars" USING btree ("hub_id");
  CREATE INDEX "pillars_hero_image_idx" ON "pillars" USING btree ("hero_image_id");
  CREATE INDEX "pillars_reviewer_idx" ON "pillars" USING btree ("reviewer_id");
  CREATE UNIQUE INDEX "pillars_external_id_idx" ON "pillars" USING btree ("external_id");
  CREATE INDEX "pillars_updated_at_idx" ON "pillars" USING btree ("updated_at");
  CREATE INDEX "pillars_created_at_idx" ON "pillars" USING btree ("created_at");
  CREATE INDEX "pillars_slug_idx" ON "pillars_locales" USING btree ("slug","_locale");
  CREATE INDEX "pillars__status_idx" ON "pillars_locales" USING btree ("_status","_locale");
  CREATE UNIQUE INDEX "pillars_locales_locale_parent_id_unique" ON "pillars_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pillars_rels_order_idx" ON "pillars_rels" USING btree ("order");
  CREATE INDEX "pillars_rels_parent_idx" ON "pillars_rels" USING btree ("parent_id");
  CREATE INDEX "pillars_rels_path_idx" ON "pillars_rels" USING btree ("path");
  CREATE INDEX "pillars_rels_authors_id_idx" ON "pillars_rels" USING btree ("authors_id");
  CREATE INDEX "pillars_rels_pillars_id_idx" ON "pillars_rels" USING btree ("pillars_id");
  CREATE INDEX "_pillars_v_version_faq_order_idx" ON "_pillars_v_version_faq" USING btree ("_order");
  CREATE INDEX "_pillars_v_version_faq_parent_id_idx" ON "_pillars_v_version_faq" USING btree ("_parent_id");
  CREATE INDEX "_pillars_v_version_faq_locale_idx" ON "_pillars_v_version_faq" USING btree ("_locale");
  CREATE INDEX "_pillars_v_version_references_order_idx" ON "_pillars_v_version_references" USING btree ("_order");
  CREATE INDEX "_pillars_v_version_references_parent_id_idx" ON "_pillars_v_version_references" USING btree ("_parent_id");
  CREATE INDEX "_pillars_v_version_references_locale_idx" ON "_pillars_v_version_references" USING btree ("_locale");
  CREATE INDEX "_pillars_v_parent_idx" ON "_pillars_v" USING btree ("parent_id");
  CREATE INDEX "_pillars_v_version_version_hub_idx" ON "_pillars_v" USING btree ("version_hub_id");
  CREATE INDEX "_pillars_v_version_version_hero_image_idx" ON "_pillars_v" USING btree ("version_hero_image_id");
  CREATE INDEX "_pillars_v_version_version_reviewer_idx" ON "_pillars_v" USING btree ("version_reviewer_id");
  CREATE INDEX "_pillars_v_version_version_external_id_idx" ON "_pillars_v" USING btree ("version_external_id");
  CREATE INDEX "_pillars_v_version_version_updated_at_idx" ON "_pillars_v" USING btree ("version_updated_at");
  CREATE INDEX "_pillars_v_version_version_created_at_idx" ON "_pillars_v" USING btree ("version_created_at");
  CREATE INDEX "_pillars_v_created_at_idx" ON "_pillars_v" USING btree ("created_at");
  CREATE INDEX "_pillars_v_updated_at_idx" ON "_pillars_v" USING btree ("updated_at");
  CREATE INDEX "_pillars_v_snapshot_idx" ON "_pillars_v" USING btree ("snapshot");
  CREATE INDEX "_pillars_v_published_locale_idx" ON "_pillars_v" USING btree ("published_locale");
  CREATE INDEX "_pillars_v_latest_idx" ON "_pillars_v" USING btree ("latest");
  CREATE INDEX "_pillars_v_version_version_slug_idx" ON "_pillars_v_locales" USING btree ("version_slug","_locale");
  CREATE INDEX "_pillars_v_version_version__status_idx" ON "_pillars_v_locales" USING btree ("version__status","_locale");
  CREATE UNIQUE INDEX "_pillars_v_locales_locale_parent_id_unique" ON "_pillars_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_pillars_v_rels_order_idx" ON "_pillars_v_rels" USING btree ("order");
  CREATE INDEX "_pillars_v_rels_parent_idx" ON "_pillars_v_rels" USING btree ("parent_id");
  CREATE INDEX "_pillars_v_rels_path_idx" ON "_pillars_v_rels" USING btree ("path");
  CREATE INDEX "_pillars_v_rels_authors_id_idx" ON "_pillars_v_rels" USING btree ("authors_id");
  CREATE INDEX "_pillars_v_rels_pillars_id_idx" ON "_pillars_v_rels" USING btree ("pillars_id");
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_pillars_fk" FOREIGN KEY ("pillars_id") REFERENCES "public"."pillars"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "payload_locked_documents_rels_pillars_id_idx" ON "payload_locked_documents_rels" USING btree ("pillars_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  ALTER TABLE "pillars_faq" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pillars_references" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pillars" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pillars_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pillars_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pillars_v_version_faq" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pillars_v_version_references" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pillars_v" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pillars_v_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pillars_v_rels" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "pillars_faq" CASCADE;
  DROP TABLE "pillars_references" CASCADE;
  DROP TABLE "pillars" CASCADE;
  DROP TABLE "pillars_locales" CASCADE;
  DROP TABLE "pillars_rels" CASCADE;
  DROP TABLE "_pillars_v_version_faq" CASCADE;
  DROP TABLE "_pillars_v_version_references" CASCADE;
  DROP TABLE "_pillars_v" CASCADE;
  DROP TABLE "_pillars_v_locales" CASCADE;
  DROP TABLE "_pillars_v_rels" CASCADE;
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_pillars_fk";
  DROP INDEX "payload_locked_documents_rels_pillars_id_idx";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "pillars_id";
  DROP TYPE "public"."enum_pillars_status";
  DROP TYPE "public"."enum__pillars_v_published_locale";
  DROP TYPE "public"."enum__pillars_v_version_status";`)
}
