import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Add the `rdPrKit` block.
 *
 * GENERATED by tools/migrate_gen.py from the block's field schema — NOT by
 * `payload migrate:create`, whose snapshot in this repo is stale and emits DDL
 * for ~171 unrelated tables.
 *
 * Every statement is idempotent (IF NOT EXISTS / duplicate_object guards), so
 * it is safe to re-run over a partially applied attempt.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  DO $$ BEGIN
   CREATE TYPE "public"."enum_pages_blocks_rd_pr_kit_guide_link_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   CREATE TYPE "public"."enum__pages_v_blocks_rd_pr_kit_guide_link_type" AS ENUM('reference', 'custom');
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_kit_facts" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_kit_facts_locales" (
  	"label" varchar NOT NULL,
  	"value" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_kit" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"guide_link_type" "enum_pages_blocks_rd_pr_kit_guide_link_type" DEFAULT 'custom',
  	"guide_link_new_tab" boolean,
  	"image_id" integer,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "pages_blocks_rd_pr_kit_locales" (
  	"heading" jsonb NOT NULL,
  	"intro" varchar,
  	"detail" varchar,
  	"guide_link_url" varchar,
  	"guide_link_label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_kit_facts" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_uuid" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_kit_facts_locales" (
  	"label" varchar NOT NULL,
  	"value" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_kit" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"anchor_id" varchar,
  	"guide_link_type" "enum__pages_v_blocks_rd_pr_kit_guide_link_type" DEFAULT 'custom',
  	"guide_link_new_tab" boolean,
  	"image_id" integer,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  CREATE TABLE IF NOT EXISTS "_pages_v_blocks_rd_pr_kit_locales" (
  	"heading" jsonb NOT NULL,
  	"intro" varchar,
  	"detail" varchar,
  	"guide_link_url" varchar,
  	"guide_link_label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_kit_facts" ADD CONSTRAINT "pages_blocks_rd_pr_kit_facts_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_kit"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_kit_facts_locales" ADD CONSTRAINT "pages_blocks_rd_pr_kit_facts_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_kit_facts"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_kit" ADD CONSTRAINT "pages_blocks_rd_pr_kit_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_kit" ADD CONSTRAINT "pages_blocks_rd_pr_kit_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "pages_blocks_rd_pr_kit_locales" ADD CONSTRAINT "pages_blocks_rd_pr_kit_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_rd_pr_kit"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_kit_facts" ADD CONSTRAINT "_pages_v_blocks_rd_pr_kit_facts_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_kit"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_kit_facts_locales" ADD CONSTRAINT "_pages_v_blocks_rd_pr_kit_facts_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_kit_facts"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_kit" ADD CONSTRAINT "_pages_v_blocks_rd_pr_kit_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_kit" ADD CONSTRAINT "_pages_v_blocks_rd_pr_kit_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  DO $$ BEGIN
   ALTER TABLE "_pages_v_blocks_rd_pr_kit_locales" ADD CONSTRAINT "_pages_v_blocks_rd_pr_kit_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_rd_pr_kit"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null;
  END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_kit_facts_order_idx" ON "pages_blocks_rd_pr_kit_facts" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_kit_facts_parent_id_idx" ON "pages_blocks_rd_pr_kit_facts" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_pr_kit_facts_locales_locale_parent_id_unique" ON "pages_blocks_rd_pr_kit_facts_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_kit_order_idx" ON "pages_blocks_rd_pr_kit" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_kit_parent_id_idx" ON "pages_blocks_rd_pr_kit" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_kit_path_idx" ON "pages_blocks_rd_pr_kit" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "pages_blocks_rd_pr_kit_image_idx" ON "pages_blocks_rd_pr_kit" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_rd_pr_kit_locales_locale_parent_id_unique" ON "pages_blocks_rd_pr_kit_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_kit_facts_order_idx" ON "_pages_v_blocks_rd_pr_kit_facts" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_kit_facts_parent_id_idx" ON "_pages_v_blocks_rd_pr_kit_facts" USING btree ("_parent_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_kit_facts_locales_locale_parent_id_uni" ON "_pages_v_blocks_rd_pr_kit_facts_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_kit_order_idx" ON "_pages_v_blocks_rd_pr_kit" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_kit_parent_id_idx" ON "_pages_v_blocks_rd_pr_kit" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_kit_path_idx" ON "_pages_v_blocks_rd_pr_kit" USING btree ("_path");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_kit_image_idx" ON "_pages_v_blocks_rd_pr_kit" USING btree ("image_id");
  CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_rd_pr_kit_locales_locale_parent_id_unique" ON "_pages_v_blocks_rd_pr_kit_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_kit_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_kit" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_kit_facts_locales" CASCADE;
  DROP TABLE IF EXISTS "_pages_v_blocks_rd_pr_kit_facts" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_kit_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_kit" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_kit_facts_locales" CASCADE;
  DROP TABLE IF EXISTS "pages_blocks_rd_pr_kit_facts" CASCADE;
  DROP TYPE IF EXISTS "public"."enum_pages_blocks_rd_pr_kit_guide_link_type";
  DROP TYPE IF EXISTS "public"."enum__pages_v_blocks_rd_pr_kit_guide_link_type";`)
}

